// Code generated by ent, DO NOT EDIT.

package temporaryfile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/simpledms/simpledms/db/entmain/predicate"
	"github.com/simpledms/simpledms/db/entx"
	"github.com/simpledms/simpledms/model/common/storagetype"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldID, id))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v entx.CIText) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldPublicID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldDeletedAt, v))
}

// UploadStartedAt applies equality check predicate on the "upload_started_at" field. It's identical to UploadStartedAtEQ.
func UploadStartedAt(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldUploadStartedAt, v))
}

// UploadFailedAt applies equality check predicate on the "upload_failed_at" field. It's identical to UploadFailedAtEQ.
func UploadFailedAt(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldUploadFailedAt, v))
}

// UploadSucceededAt applies equality check predicate on the "upload_succeeded_at" field. It's identical to UploadSucceededAtEQ.
func UploadSucceededAt(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldUploadSucceededAt, v))
}

// OwnerID applies equality check predicate on the "owner_id" field. It's identical to OwnerIDEQ.
func OwnerID(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldOwnerID, v))
}

// Filename applies equality check predicate on the "filename" field. It's identical to FilenameEQ.
func Filename(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldFilename, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldSize, v))
}

// SizeInStorage applies equality check predicate on the "size_in_storage" field. It's identical to SizeInStorageEQ.
func SizeInStorage(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldSizeInStorage, v))
}

// Sha256 applies equality check predicate on the "sha256" field. It's identical to Sha256EQ.
func Sha256(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldSha256, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldMimeType, v))
}

// BucketName applies equality check predicate on the "bucket_name" field. It's identical to BucketNameEQ.
func BucketName(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldBucketName, v))
}

// StoragePath applies equality check predicate on the "storage_path" field. It's identical to StoragePathEQ.
func StoragePath(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldStoragePath, v))
}

// StorageFilename applies equality check predicate on the "storage_filename" field. It's identical to StorageFilenameEQ.
func StorageFilename(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldStorageFilename, v))
}

// UploadToken applies equality check predicate on the "upload_token" field. It's identical to UploadTokenEQ.
func UploadToken(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldUploadToken, v))
}

// ConvertedToStoredFileAt applies equality check predicate on the "converted_to_stored_file_at" field. It's identical to ConvertedToStoredFileAtEQ.
func ConvertedToStoredFileAt(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldConvertedToStoredFileAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldExpiresAt, v))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v entx.CIText) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v entx.CIText) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...entx.CIText) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...entx.CIText) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v entx.CIText) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v entx.CIText) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v entx.CIText) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v entx.CIText) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldPublicID, v))
}

// PublicIDContains applies the Contains predicate on the "public_id" field.
func PublicIDContains(v entx.CIText) predicate.TemporaryFile {
	vc := string(v)
	return predicate.TemporaryFile(sql.FieldContains(FieldPublicID, vc))
}

// PublicIDHasPrefix applies the HasPrefix predicate on the "public_id" field.
func PublicIDHasPrefix(v entx.CIText) predicate.TemporaryFile {
	vc := string(v)
	return predicate.TemporaryFile(sql.FieldHasPrefix(FieldPublicID, vc))
}

// PublicIDHasSuffix applies the HasSuffix predicate on the "public_id" field.
func PublicIDHasSuffix(v entx.CIText) predicate.TemporaryFile {
	vc := string(v)
	return predicate.TemporaryFile(sql.FieldHasSuffix(FieldPublicID, vc))
}

// PublicIDEqualFold applies the EqualFold predicate on the "public_id" field.
func PublicIDEqualFold(v entx.CIText) predicate.TemporaryFile {
	vc := string(v)
	return predicate.TemporaryFile(sql.FieldEqualFold(FieldPublicID, vc))
}

// PublicIDContainsFold applies the ContainsFold predicate on the "public_id" field.
func PublicIDContainsFold(v entx.CIText) predicate.TemporaryFile {
	vc := string(v)
	return predicate.TemporaryFile(sql.FieldContainsFold(FieldPublicID, vc))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotNull(FieldUpdatedBy))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotNull(FieldDeletedBy))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotNull(FieldDeletedAt))
}

// UploadStartedAtEQ applies the EQ predicate on the "upload_started_at" field.
func UploadStartedAtEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldUploadStartedAt, v))
}

// UploadStartedAtNEQ applies the NEQ predicate on the "upload_started_at" field.
func UploadStartedAtNEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldUploadStartedAt, v))
}

// UploadStartedAtIn applies the In predicate on the "upload_started_at" field.
func UploadStartedAtIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldUploadStartedAt, vs...))
}

// UploadStartedAtNotIn applies the NotIn predicate on the "upload_started_at" field.
func UploadStartedAtNotIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldUploadStartedAt, vs...))
}

// UploadStartedAtGT applies the GT predicate on the "upload_started_at" field.
func UploadStartedAtGT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldUploadStartedAt, v))
}

// UploadStartedAtGTE applies the GTE predicate on the "upload_started_at" field.
func UploadStartedAtGTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldUploadStartedAt, v))
}

// UploadStartedAtLT applies the LT predicate on the "upload_started_at" field.
func UploadStartedAtLT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldUploadStartedAt, v))
}

// UploadStartedAtLTE applies the LTE predicate on the "upload_started_at" field.
func UploadStartedAtLTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldUploadStartedAt, v))
}

// UploadStartedAtIsNil applies the IsNil predicate on the "upload_started_at" field.
func UploadStartedAtIsNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIsNull(FieldUploadStartedAt))
}

// UploadStartedAtNotNil applies the NotNil predicate on the "upload_started_at" field.
func UploadStartedAtNotNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotNull(FieldUploadStartedAt))
}

// UploadFailedAtEQ applies the EQ predicate on the "upload_failed_at" field.
func UploadFailedAtEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldUploadFailedAt, v))
}

// UploadFailedAtNEQ applies the NEQ predicate on the "upload_failed_at" field.
func UploadFailedAtNEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldUploadFailedAt, v))
}

// UploadFailedAtIn applies the In predicate on the "upload_failed_at" field.
func UploadFailedAtIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldUploadFailedAt, vs...))
}

// UploadFailedAtNotIn applies the NotIn predicate on the "upload_failed_at" field.
func UploadFailedAtNotIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldUploadFailedAt, vs...))
}

// UploadFailedAtGT applies the GT predicate on the "upload_failed_at" field.
func UploadFailedAtGT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldUploadFailedAt, v))
}

// UploadFailedAtGTE applies the GTE predicate on the "upload_failed_at" field.
func UploadFailedAtGTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldUploadFailedAt, v))
}

// UploadFailedAtLT applies the LT predicate on the "upload_failed_at" field.
func UploadFailedAtLT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldUploadFailedAt, v))
}

// UploadFailedAtLTE applies the LTE predicate on the "upload_failed_at" field.
func UploadFailedAtLTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldUploadFailedAt, v))
}

// UploadFailedAtIsNil applies the IsNil predicate on the "upload_failed_at" field.
func UploadFailedAtIsNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIsNull(FieldUploadFailedAt))
}

// UploadFailedAtNotNil applies the NotNil predicate on the "upload_failed_at" field.
func UploadFailedAtNotNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotNull(FieldUploadFailedAt))
}

// UploadSucceededAtEQ applies the EQ predicate on the "upload_succeeded_at" field.
func UploadSucceededAtEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldUploadSucceededAt, v))
}

// UploadSucceededAtNEQ applies the NEQ predicate on the "upload_succeeded_at" field.
func UploadSucceededAtNEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldUploadSucceededAt, v))
}

// UploadSucceededAtIn applies the In predicate on the "upload_succeeded_at" field.
func UploadSucceededAtIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldUploadSucceededAt, vs...))
}

// UploadSucceededAtNotIn applies the NotIn predicate on the "upload_succeeded_at" field.
func UploadSucceededAtNotIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldUploadSucceededAt, vs...))
}

// UploadSucceededAtGT applies the GT predicate on the "upload_succeeded_at" field.
func UploadSucceededAtGT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldUploadSucceededAt, v))
}

// UploadSucceededAtGTE applies the GTE predicate on the "upload_succeeded_at" field.
func UploadSucceededAtGTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldUploadSucceededAt, v))
}

// UploadSucceededAtLT applies the LT predicate on the "upload_succeeded_at" field.
func UploadSucceededAtLT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldUploadSucceededAt, v))
}

// UploadSucceededAtLTE applies the LTE predicate on the "upload_succeeded_at" field.
func UploadSucceededAtLTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldUploadSucceededAt, v))
}

// UploadSucceededAtIsNil applies the IsNil predicate on the "upload_succeeded_at" field.
func UploadSucceededAtIsNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIsNull(FieldUploadSucceededAt))
}

// UploadSucceededAtNotNil applies the NotNil predicate on the "upload_succeeded_at" field.
func UploadSucceededAtNotNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotNull(FieldUploadSucceededAt))
}

// OwnerIDEQ applies the EQ predicate on the "owner_id" field.
func OwnerIDEQ(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldOwnerID, v))
}

// OwnerIDNEQ applies the NEQ predicate on the "owner_id" field.
func OwnerIDNEQ(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldOwnerID, v))
}

// OwnerIDIn applies the In predicate on the "owner_id" field.
func OwnerIDIn(vs ...int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldOwnerID, vs...))
}

// OwnerIDNotIn applies the NotIn predicate on the "owner_id" field.
func OwnerIDNotIn(vs ...int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldOwnerID, vs...))
}

// FilenameEQ applies the EQ predicate on the "filename" field.
func FilenameEQ(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldFilename, v))
}

// FilenameNEQ applies the NEQ predicate on the "filename" field.
func FilenameNEQ(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldFilename, v))
}

// FilenameIn applies the In predicate on the "filename" field.
func FilenameIn(vs ...string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldFilename, vs...))
}

// FilenameNotIn applies the NotIn predicate on the "filename" field.
func FilenameNotIn(vs ...string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldFilename, vs...))
}

// FilenameGT applies the GT predicate on the "filename" field.
func FilenameGT(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldFilename, v))
}

// FilenameGTE applies the GTE predicate on the "filename" field.
func FilenameGTE(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldFilename, v))
}

// FilenameLT applies the LT predicate on the "filename" field.
func FilenameLT(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldFilename, v))
}

// FilenameLTE applies the LTE predicate on the "filename" field.
func FilenameLTE(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldFilename, v))
}

// FilenameContains applies the Contains predicate on the "filename" field.
func FilenameContains(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldContains(FieldFilename, v))
}

// FilenameHasPrefix applies the HasPrefix predicate on the "filename" field.
func FilenameHasPrefix(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldHasPrefix(FieldFilename, v))
}

// FilenameHasSuffix applies the HasSuffix predicate on the "filename" field.
func FilenameHasSuffix(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldHasSuffix(FieldFilename, v))
}

// FilenameEqualFold applies the EqualFold predicate on the "filename" field.
func FilenameEqualFold(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEqualFold(FieldFilename, v))
}

// FilenameContainsFold applies the ContainsFold predicate on the "filename" field.
func FilenameContainsFold(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldContainsFold(FieldFilename, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldSize, v))
}

// SizeIsNil applies the IsNil predicate on the "size" field.
func SizeIsNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIsNull(FieldSize))
}

// SizeNotNil applies the NotNil predicate on the "size" field.
func SizeNotNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotNull(FieldSize))
}

// SizeInStorageEQ applies the EQ predicate on the "size_in_storage" field.
func SizeInStorageEQ(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldSizeInStorage, v))
}

// SizeInStorageNEQ applies the NEQ predicate on the "size_in_storage" field.
func SizeInStorageNEQ(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldSizeInStorage, v))
}

// SizeInStorageIn applies the In predicate on the "size_in_storage" field.
func SizeInStorageIn(vs ...int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldSizeInStorage, vs...))
}

// SizeInStorageNotIn applies the NotIn predicate on the "size_in_storage" field.
func SizeInStorageNotIn(vs ...int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldSizeInStorage, vs...))
}

// SizeInStorageGT applies the GT predicate on the "size_in_storage" field.
func SizeInStorageGT(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldSizeInStorage, v))
}

// SizeInStorageGTE applies the GTE predicate on the "size_in_storage" field.
func SizeInStorageGTE(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldSizeInStorage, v))
}

// SizeInStorageLT applies the LT predicate on the "size_in_storage" field.
func SizeInStorageLT(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldSizeInStorage, v))
}

// SizeInStorageLTE applies the LTE predicate on the "size_in_storage" field.
func SizeInStorageLTE(v int64) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldSizeInStorage, v))
}

// Sha256EQ applies the EQ predicate on the "sha256" field.
func Sha256EQ(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldSha256, v))
}

// Sha256NEQ applies the NEQ predicate on the "sha256" field.
func Sha256NEQ(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldSha256, v))
}

// Sha256In applies the In predicate on the "sha256" field.
func Sha256In(vs ...string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldSha256, vs...))
}

// Sha256NotIn applies the NotIn predicate on the "sha256" field.
func Sha256NotIn(vs ...string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldSha256, vs...))
}

// Sha256GT applies the GT predicate on the "sha256" field.
func Sha256GT(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldSha256, v))
}

// Sha256GTE applies the GTE predicate on the "sha256" field.
func Sha256GTE(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldSha256, v))
}

// Sha256LT applies the LT predicate on the "sha256" field.
func Sha256LT(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldSha256, v))
}

// Sha256LTE applies the LTE predicate on the "sha256" field.
func Sha256LTE(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldSha256, v))
}

// Sha256Contains applies the Contains predicate on the "sha256" field.
func Sha256Contains(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldContains(FieldSha256, v))
}

// Sha256HasPrefix applies the HasPrefix predicate on the "sha256" field.
func Sha256HasPrefix(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldHasPrefix(FieldSha256, v))
}

// Sha256HasSuffix applies the HasSuffix predicate on the "sha256" field.
func Sha256HasSuffix(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldHasSuffix(FieldSha256, v))
}

// Sha256IsNil applies the IsNil predicate on the "sha256" field.
func Sha256IsNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIsNull(FieldSha256))
}

// Sha256NotNil applies the NotNil predicate on the "sha256" field.
func Sha256NotNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotNull(FieldSha256))
}

// Sha256EqualFold applies the EqualFold predicate on the "sha256" field.
func Sha256EqualFold(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEqualFold(FieldSha256, v))
}

// Sha256ContainsFold applies the ContainsFold predicate on the "sha256" field.
func Sha256ContainsFold(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldContainsFold(FieldSha256, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeIsNil applies the IsNil predicate on the "mime_type" field.
func MimeTypeIsNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIsNull(FieldMimeType))
}

// MimeTypeNotNil applies the NotNil predicate on the "mime_type" field.
func MimeTypeNotNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotNull(FieldMimeType))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldContainsFold(FieldMimeType, v))
}

// StorageTypeEQ applies the EQ predicate on the "storage_type" field.
func StorageTypeEQ(v storagetype.StorageType) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldStorageType, v))
}

// StorageTypeNEQ applies the NEQ predicate on the "storage_type" field.
func StorageTypeNEQ(v storagetype.StorageType) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldStorageType, v))
}

// StorageTypeIn applies the In predicate on the "storage_type" field.
func StorageTypeIn(vs ...storagetype.StorageType) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldStorageType, vs...))
}

// StorageTypeNotIn applies the NotIn predicate on the "storage_type" field.
func StorageTypeNotIn(vs ...storagetype.StorageType) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldStorageType, vs...))
}

// BucketNameEQ applies the EQ predicate on the "bucket_name" field.
func BucketNameEQ(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldBucketName, v))
}

// BucketNameNEQ applies the NEQ predicate on the "bucket_name" field.
func BucketNameNEQ(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldBucketName, v))
}

// BucketNameIn applies the In predicate on the "bucket_name" field.
func BucketNameIn(vs ...string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldBucketName, vs...))
}

// BucketNameNotIn applies the NotIn predicate on the "bucket_name" field.
func BucketNameNotIn(vs ...string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldBucketName, vs...))
}

// BucketNameGT applies the GT predicate on the "bucket_name" field.
func BucketNameGT(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldBucketName, v))
}

// BucketNameGTE applies the GTE predicate on the "bucket_name" field.
func BucketNameGTE(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldBucketName, v))
}

// BucketNameLT applies the LT predicate on the "bucket_name" field.
func BucketNameLT(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldBucketName, v))
}

// BucketNameLTE applies the LTE predicate on the "bucket_name" field.
func BucketNameLTE(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldBucketName, v))
}

// BucketNameContains applies the Contains predicate on the "bucket_name" field.
func BucketNameContains(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldContains(FieldBucketName, v))
}

// BucketNameHasPrefix applies the HasPrefix predicate on the "bucket_name" field.
func BucketNameHasPrefix(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldHasPrefix(FieldBucketName, v))
}

// BucketNameHasSuffix applies the HasSuffix predicate on the "bucket_name" field.
func BucketNameHasSuffix(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldHasSuffix(FieldBucketName, v))
}

// BucketNameIsNil applies the IsNil predicate on the "bucket_name" field.
func BucketNameIsNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIsNull(FieldBucketName))
}

// BucketNameNotNil applies the NotNil predicate on the "bucket_name" field.
func BucketNameNotNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotNull(FieldBucketName))
}

// BucketNameEqualFold applies the EqualFold predicate on the "bucket_name" field.
func BucketNameEqualFold(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEqualFold(FieldBucketName, v))
}

// BucketNameContainsFold applies the ContainsFold predicate on the "bucket_name" field.
func BucketNameContainsFold(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldContainsFold(FieldBucketName, v))
}

// StoragePathEQ applies the EQ predicate on the "storage_path" field.
func StoragePathEQ(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldStoragePath, v))
}

// StoragePathNEQ applies the NEQ predicate on the "storage_path" field.
func StoragePathNEQ(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldStoragePath, v))
}

// StoragePathIn applies the In predicate on the "storage_path" field.
func StoragePathIn(vs ...string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldStoragePath, vs...))
}

// StoragePathNotIn applies the NotIn predicate on the "storage_path" field.
func StoragePathNotIn(vs ...string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldStoragePath, vs...))
}

// StoragePathGT applies the GT predicate on the "storage_path" field.
func StoragePathGT(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldStoragePath, v))
}

// StoragePathGTE applies the GTE predicate on the "storage_path" field.
func StoragePathGTE(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldStoragePath, v))
}

// StoragePathLT applies the LT predicate on the "storage_path" field.
func StoragePathLT(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldStoragePath, v))
}

// StoragePathLTE applies the LTE predicate on the "storage_path" field.
func StoragePathLTE(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldStoragePath, v))
}

// StoragePathContains applies the Contains predicate on the "storage_path" field.
func StoragePathContains(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldContains(FieldStoragePath, v))
}

// StoragePathHasPrefix applies the HasPrefix predicate on the "storage_path" field.
func StoragePathHasPrefix(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldHasPrefix(FieldStoragePath, v))
}

// StoragePathHasSuffix applies the HasSuffix predicate on the "storage_path" field.
func StoragePathHasSuffix(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldHasSuffix(FieldStoragePath, v))
}

// StoragePathEqualFold applies the EqualFold predicate on the "storage_path" field.
func StoragePathEqualFold(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEqualFold(FieldStoragePath, v))
}

// StoragePathContainsFold applies the ContainsFold predicate on the "storage_path" field.
func StoragePathContainsFold(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldContainsFold(FieldStoragePath, v))
}

// StorageFilenameEQ applies the EQ predicate on the "storage_filename" field.
func StorageFilenameEQ(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldStorageFilename, v))
}

// StorageFilenameNEQ applies the NEQ predicate on the "storage_filename" field.
func StorageFilenameNEQ(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldStorageFilename, v))
}

// StorageFilenameIn applies the In predicate on the "storage_filename" field.
func StorageFilenameIn(vs ...string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldStorageFilename, vs...))
}

// StorageFilenameNotIn applies the NotIn predicate on the "storage_filename" field.
func StorageFilenameNotIn(vs ...string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldStorageFilename, vs...))
}

// StorageFilenameGT applies the GT predicate on the "storage_filename" field.
func StorageFilenameGT(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldStorageFilename, v))
}

// StorageFilenameGTE applies the GTE predicate on the "storage_filename" field.
func StorageFilenameGTE(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldStorageFilename, v))
}

// StorageFilenameLT applies the LT predicate on the "storage_filename" field.
func StorageFilenameLT(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldStorageFilename, v))
}

// StorageFilenameLTE applies the LTE predicate on the "storage_filename" field.
func StorageFilenameLTE(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldStorageFilename, v))
}

// StorageFilenameContains applies the Contains predicate on the "storage_filename" field.
func StorageFilenameContains(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldContains(FieldStorageFilename, v))
}

// StorageFilenameHasPrefix applies the HasPrefix predicate on the "storage_filename" field.
func StorageFilenameHasPrefix(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldHasPrefix(FieldStorageFilename, v))
}

// StorageFilenameHasSuffix applies the HasSuffix predicate on the "storage_filename" field.
func StorageFilenameHasSuffix(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldHasSuffix(FieldStorageFilename, v))
}

// StorageFilenameEqualFold applies the EqualFold predicate on the "storage_filename" field.
func StorageFilenameEqualFold(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEqualFold(FieldStorageFilename, v))
}

// StorageFilenameContainsFold applies the ContainsFold predicate on the "storage_filename" field.
func StorageFilenameContainsFold(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldContainsFold(FieldStorageFilename, v))
}

// UploadTokenEQ applies the EQ predicate on the "upload_token" field.
func UploadTokenEQ(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldUploadToken, v))
}

// UploadTokenNEQ applies the NEQ predicate on the "upload_token" field.
func UploadTokenNEQ(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldUploadToken, v))
}

// UploadTokenIn applies the In predicate on the "upload_token" field.
func UploadTokenIn(vs ...string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldUploadToken, vs...))
}

// UploadTokenNotIn applies the NotIn predicate on the "upload_token" field.
func UploadTokenNotIn(vs ...string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldUploadToken, vs...))
}

// UploadTokenGT applies the GT predicate on the "upload_token" field.
func UploadTokenGT(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldUploadToken, v))
}

// UploadTokenGTE applies the GTE predicate on the "upload_token" field.
func UploadTokenGTE(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldUploadToken, v))
}

// UploadTokenLT applies the LT predicate on the "upload_token" field.
func UploadTokenLT(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldUploadToken, v))
}

// UploadTokenLTE applies the LTE predicate on the "upload_token" field.
func UploadTokenLTE(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldUploadToken, v))
}

// UploadTokenContains applies the Contains predicate on the "upload_token" field.
func UploadTokenContains(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldContains(FieldUploadToken, v))
}

// UploadTokenHasPrefix applies the HasPrefix predicate on the "upload_token" field.
func UploadTokenHasPrefix(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldHasPrefix(FieldUploadToken, v))
}

// UploadTokenHasSuffix applies the HasSuffix predicate on the "upload_token" field.
func UploadTokenHasSuffix(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldHasSuffix(FieldUploadToken, v))
}

// UploadTokenEqualFold applies the EqualFold predicate on the "upload_token" field.
func UploadTokenEqualFold(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEqualFold(FieldUploadToken, v))
}

// UploadTokenContainsFold applies the ContainsFold predicate on the "upload_token" field.
func UploadTokenContainsFold(v string) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldContainsFold(FieldUploadToken, v))
}

// ConvertedToStoredFileAtEQ applies the EQ predicate on the "converted_to_stored_file_at" field.
func ConvertedToStoredFileAtEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldConvertedToStoredFileAt, v))
}

// ConvertedToStoredFileAtNEQ applies the NEQ predicate on the "converted_to_stored_file_at" field.
func ConvertedToStoredFileAtNEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldConvertedToStoredFileAt, v))
}

// ConvertedToStoredFileAtIn applies the In predicate on the "converted_to_stored_file_at" field.
func ConvertedToStoredFileAtIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldConvertedToStoredFileAt, vs...))
}

// ConvertedToStoredFileAtNotIn applies the NotIn predicate on the "converted_to_stored_file_at" field.
func ConvertedToStoredFileAtNotIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldConvertedToStoredFileAt, vs...))
}

// ConvertedToStoredFileAtGT applies the GT predicate on the "converted_to_stored_file_at" field.
func ConvertedToStoredFileAtGT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldConvertedToStoredFileAt, v))
}

// ConvertedToStoredFileAtGTE applies the GTE predicate on the "converted_to_stored_file_at" field.
func ConvertedToStoredFileAtGTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldConvertedToStoredFileAt, v))
}

// ConvertedToStoredFileAtLT applies the LT predicate on the "converted_to_stored_file_at" field.
func ConvertedToStoredFileAtLT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldConvertedToStoredFileAt, v))
}

// ConvertedToStoredFileAtLTE applies the LTE predicate on the "converted_to_stored_file_at" field.
func ConvertedToStoredFileAtLTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldConvertedToStoredFileAt, v))
}

// ConvertedToStoredFileAtIsNil applies the IsNil predicate on the "converted_to_stored_file_at" field.
func ConvertedToStoredFileAtIsNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIsNull(FieldConvertedToStoredFileAt))
}

// ConvertedToStoredFileAtNotNil applies the NotNil predicate on the "converted_to_stored_file_at" field.
func ConvertedToStoredFileAtNotNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotNull(FieldConvertedToStoredFileAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.FieldNotNull(FieldExpiresAt))
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.TemporaryFile {
	return predicate.TemporaryFile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.Account) predicate.TemporaryFile {
	return predicate.TemporaryFile(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUpdater applies the HasEdge predicate on the "updater" edge.
func HasUpdater() predicate.TemporaryFile {
	return predicate.TemporaryFile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UpdaterTable, UpdaterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUpdaterWith applies the HasEdge predicate on the "updater" edge with a given conditions (other predicates).
func HasUpdaterWith(preds ...predicate.Account) predicate.TemporaryFile {
	return predicate.TemporaryFile(func(s *sql.Selector) {
		step := newUpdaterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDeleter applies the HasEdge predicate on the "deleter" edge.
func HasDeleter() predicate.TemporaryFile {
	return predicate.TemporaryFile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, DeleterTable, DeleterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeleterWith applies the HasEdge predicate on the "deleter" edge with a given conditions (other predicates).
func HasDeleterWith(preds ...predicate.Account) predicate.TemporaryFile {
	return predicate.TemporaryFile(func(s *sql.Selector) {
		step := newDeleterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.TemporaryFile {
	return predicate.TemporaryFile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.Account) predicate.TemporaryFile {
	return predicate.TemporaryFile(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TemporaryFile) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TemporaryFile) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TemporaryFile) predicate.TemporaryFile {
	return predicate.TemporaryFile(sql.NotPredicates(p))
}
