// Code generated by ent, DO NOT EDIT.

package fileversion

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the fileversion type in the database.
	Label = "file_version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldFileID holds the string denoting the file_id field in the database.
	FieldFileID = "file_id"
	// FieldStoredFileID holds the string denoting the stored_file_id field in the database.
	FieldStoredFileID = "stored_file_id"
	// FieldVersionNumber holds the string denoting the version_number field in the database.
	FieldVersionNumber = "version_number"
	// FieldNote holds the string denoting the note field in the database.
	FieldNote = "note"
	// EdgeFile holds the string denoting the file edge name in mutations.
	EdgeFile = "file"
	// EdgeStoredFile holds the string denoting the stored_file edge name in mutations.
	EdgeStoredFile = "stored_file"
	// Table holds the table name of the fileversion in the database.
	Table = "file_versions"
	// FileTable is the table that holds the file relation/edge.
	FileTable = "file_versions"
	// FileInverseTable is the table name for the File entity.
	// It exists in this package in order to avoid circular dependency with the "file" package.
	FileInverseTable = "files"
	// FileColumn is the table column denoting the file relation/edge.
	FileColumn = "file_id"
	// StoredFileTable is the table that holds the stored_file relation/edge.
	StoredFileTable = "file_versions"
	// StoredFileInverseTable is the table name for the StoredFile entity.
	// It exists in this package in order to avoid circular dependency with the "storedfile" package.
	StoredFileInverseTable = "stored_files"
	// StoredFileColumn is the table column denoting the stored_file relation/edge.
	StoredFileColumn = "stored_file_id"
)

// Columns holds all SQL columns for fileversion fields.
var Columns = []string{
	FieldID,
	FieldFileID,
	FieldStoredFileID,
	FieldVersionNumber,
	FieldNote,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultVersionNumber holds the default value on creation for the "version_number" field.
	DefaultVersionNumber int
)

// OrderOption defines the ordering options for the FileVersion queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByFileID orders the results by the file_id field.
func ByFileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileID, opts...).ToFunc()
}

// ByStoredFileID orders the results by the stored_file_id field.
func ByStoredFileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoredFileID, opts...).ToFunc()
}

// ByVersionNumber orders the results by the version_number field.
func ByVersionNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersionNumber, opts...).ToFunc()
}

// ByNote orders the results by the note field.
func ByNote(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNote, opts...).ToFunc()
}

// ByFileField orders the results by file field.
func ByFileField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFileStep(), sql.OrderByField(field, opts...))
	}
}

// ByStoredFileField orders the results by stored_file field.
func ByStoredFileField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStoredFileStep(), sql.OrderByField(field, opts...))
	}
}
func newFileStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FileInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, FileTable, FileColumn),
	)
}
func newStoredFileStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StoredFileInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, StoredFileTable, StoredFileColumn),
	)
}
