// Code generated by ent, DO NOT EDIT.

package entmain

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/simpledms/simpledms/entmain/account"
	"github.com/simpledms/simpledms/entmain/predicate"
	"github.com/simpledms/simpledms/entmain/temporaryfile"
	"github.com/simpledms/simpledms/model/common/storagetype"
)

// TemporaryFileUpdate is the builder for updating TemporaryFile entities.
type TemporaryFileUpdate struct {
	config
	hooks     []Hook
	mutation  *TemporaryFileMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TemporaryFileUpdate builder.
func (tfu *TemporaryFileUpdate) Where(ps ...predicate.TemporaryFile) *TemporaryFileUpdate {
	tfu.mutation.Where(ps...)
	return tfu
}

// SetUpdatedAt sets the "updated_at" field.
func (tfu *TemporaryFileUpdate) SetUpdatedAt(t time.Time) *TemporaryFileUpdate {
	tfu.mutation.SetUpdatedAt(t)
	return tfu
}

// SetUpdatedBy sets the "updated_by" field.
func (tfu *TemporaryFileUpdate) SetUpdatedBy(i int64) *TemporaryFileUpdate {
	tfu.mutation.SetUpdatedBy(i)
	return tfu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableUpdatedBy(i *int64) *TemporaryFileUpdate {
	if i != nil {
		tfu.SetUpdatedBy(*i)
	}
	return tfu
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (tfu *TemporaryFileUpdate) ClearUpdatedBy() *TemporaryFileUpdate {
	tfu.mutation.ClearUpdatedBy()
	return tfu
}

// SetDeletedBy sets the "deleted_by" field.
func (tfu *TemporaryFileUpdate) SetDeletedBy(i int64) *TemporaryFileUpdate {
	tfu.mutation.SetDeletedBy(i)
	return tfu
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableDeletedBy(i *int64) *TemporaryFileUpdate {
	if i != nil {
		tfu.SetDeletedBy(*i)
	}
	return tfu
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (tfu *TemporaryFileUpdate) ClearDeletedBy() *TemporaryFileUpdate {
	tfu.mutation.ClearDeletedBy()
	return tfu
}

// SetDeletedAt sets the "deleted_at" field.
func (tfu *TemporaryFileUpdate) SetDeletedAt(t time.Time) *TemporaryFileUpdate {
	tfu.mutation.SetDeletedAt(t)
	return tfu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableDeletedAt(t *time.Time) *TemporaryFileUpdate {
	if t != nil {
		tfu.SetDeletedAt(*t)
	}
	return tfu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (tfu *TemporaryFileUpdate) ClearDeletedAt() *TemporaryFileUpdate {
	tfu.mutation.ClearDeletedAt()
	return tfu
}

// SetSize sets the "size" field.
func (tfu *TemporaryFileUpdate) SetSize(i int64) *TemporaryFileUpdate {
	tfu.mutation.ResetSize()
	tfu.mutation.SetSize(i)
	return tfu
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableSize(i *int64) *TemporaryFileUpdate {
	if i != nil {
		tfu.SetSize(*i)
	}
	return tfu
}

// AddSize adds i to the "size" field.
func (tfu *TemporaryFileUpdate) AddSize(i int64) *TemporaryFileUpdate {
	tfu.mutation.AddSize(i)
	return tfu
}

// ClearSize clears the value of the "size" field.
func (tfu *TemporaryFileUpdate) ClearSize() *TemporaryFileUpdate {
	tfu.mutation.ClearSize()
	return tfu
}

// SetSizeInStorage sets the "size_in_storage" field.
func (tfu *TemporaryFileUpdate) SetSizeInStorage(i int64) *TemporaryFileUpdate {
	tfu.mutation.ResetSizeInStorage()
	tfu.mutation.SetSizeInStorage(i)
	return tfu
}

// SetNillableSizeInStorage sets the "size_in_storage" field if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableSizeInStorage(i *int64) *TemporaryFileUpdate {
	if i != nil {
		tfu.SetSizeInStorage(*i)
	}
	return tfu
}

// AddSizeInStorage adds i to the "size_in_storage" field.
func (tfu *TemporaryFileUpdate) AddSizeInStorage(i int64) *TemporaryFileUpdate {
	tfu.mutation.AddSizeInStorage(i)
	return tfu
}

// SetSha256 sets the "sha256" field.
func (tfu *TemporaryFileUpdate) SetSha256(s string) *TemporaryFileUpdate {
	tfu.mutation.SetSha256(s)
	return tfu
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableSha256(s *string) *TemporaryFileUpdate {
	if s != nil {
		tfu.SetSha256(*s)
	}
	return tfu
}

// ClearSha256 clears the value of the "sha256" field.
func (tfu *TemporaryFileUpdate) ClearSha256() *TemporaryFileUpdate {
	tfu.mutation.ClearSha256()
	return tfu
}

// SetMimeType sets the "mime_type" field.
func (tfu *TemporaryFileUpdate) SetMimeType(s string) *TemporaryFileUpdate {
	tfu.mutation.SetMimeType(s)
	return tfu
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableMimeType(s *string) *TemporaryFileUpdate {
	if s != nil {
		tfu.SetMimeType(*s)
	}
	return tfu
}

// ClearMimeType clears the value of the "mime_type" field.
func (tfu *TemporaryFileUpdate) ClearMimeType() *TemporaryFileUpdate {
	tfu.mutation.ClearMimeType()
	return tfu
}

// SetStorageType sets the "storage_type" field.
func (tfu *TemporaryFileUpdate) SetStorageType(st storagetype.StorageType) *TemporaryFileUpdate {
	tfu.mutation.SetStorageType(st)
	return tfu
}

// SetNillableStorageType sets the "storage_type" field if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableStorageType(st *storagetype.StorageType) *TemporaryFileUpdate {
	if st != nil {
		tfu.SetStorageType(*st)
	}
	return tfu
}

// SetBucketName sets the "bucket_name" field.
func (tfu *TemporaryFileUpdate) SetBucketName(s string) *TemporaryFileUpdate {
	tfu.mutation.SetBucketName(s)
	return tfu
}

// SetNillableBucketName sets the "bucket_name" field if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableBucketName(s *string) *TemporaryFileUpdate {
	if s != nil {
		tfu.SetBucketName(*s)
	}
	return tfu
}

// ClearBucketName clears the value of the "bucket_name" field.
func (tfu *TemporaryFileUpdate) ClearBucketName() *TemporaryFileUpdate {
	tfu.mutation.ClearBucketName()
	return tfu
}

// SetStoragePath sets the "storage_path" field.
func (tfu *TemporaryFileUpdate) SetStoragePath(s string) *TemporaryFileUpdate {
	tfu.mutation.SetStoragePath(s)
	return tfu
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableStoragePath(s *string) *TemporaryFileUpdate {
	if s != nil {
		tfu.SetStoragePath(*s)
	}
	return tfu
}

// SetStorageFilename sets the "storage_filename" field.
func (tfu *TemporaryFileUpdate) SetStorageFilename(s string) *TemporaryFileUpdate {
	tfu.mutation.SetStorageFilename(s)
	return tfu
}

// SetNillableStorageFilename sets the "storage_filename" field if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableStorageFilename(s *string) *TemporaryFileUpdate {
	if s != nil {
		tfu.SetStorageFilename(*s)
	}
	return tfu
}

// SetUploadToken sets the "upload_token" field.
func (tfu *TemporaryFileUpdate) SetUploadToken(s string) *TemporaryFileUpdate {
	tfu.mutation.SetUploadToken(s)
	return tfu
}

// SetNillableUploadToken sets the "upload_token" field if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableUploadToken(s *string) *TemporaryFileUpdate {
	if s != nil {
		tfu.SetUploadToken(*s)
	}
	return tfu
}

// SetConvertedToStoredFileAt sets the "converted_to_stored_file_at" field.
func (tfu *TemporaryFileUpdate) SetConvertedToStoredFileAt(t time.Time) *TemporaryFileUpdate {
	tfu.mutation.SetConvertedToStoredFileAt(t)
	return tfu
}

// SetNillableConvertedToStoredFileAt sets the "converted_to_stored_file_at" field if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableConvertedToStoredFileAt(t *time.Time) *TemporaryFileUpdate {
	if t != nil {
		tfu.SetConvertedToStoredFileAt(*t)
	}
	return tfu
}

// ClearConvertedToStoredFileAt clears the value of the "converted_to_stored_file_at" field.
func (tfu *TemporaryFileUpdate) ClearConvertedToStoredFileAt() *TemporaryFileUpdate {
	tfu.mutation.ClearConvertedToStoredFileAt()
	return tfu
}

// SetExpiresAt sets the "expires_at" field.
func (tfu *TemporaryFileUpdate) SetExpiresAt(t time.Time) *TemporaryFileUpdate {
	tfu.mutation.SetExpiresAt(t)
	return tfu
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableExpiresAt(t *time.Time) *TemporaryFileUpdate {
	if t != nil {
		tfu.SetExpiresAt(*t)
	}
	return tfu
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (tfu *TemporaryFileUpdate) ClearExpiresAt() *TemporaryFileUpdate {
	tfu.mutation.ClearExpiresAt()
	return tfu
}

// SetUpdaterID sets the "updater" edge to the Account entity by ID.
func (tfu *TemporaryFileUpdate) SetUpdaterID(id int64) *TemporaryFileUpdate {
	tfu.mutation.SetUpdaterID(id)
	return tfu
}

// SetNillableUpdaterID sets the "updater" edge to the Account entity by ID if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableUpdaterID(id *int64) *TemporaryFileUpdate {
	if id != nil {
		tfu = tfu.SetUpdaterID(*id)
	}
	return tfu
}

// SetUpdater sets the "updater" edge to the Account entity.
func (tfu *TemporaryFileUpdate) SetUpdater(a *Account) *TemporaryFileUpdate {
	return tfu.SetUpdaterID(a.ID)
}

// SetDeleterID sets the "deleter" edge to the Account entity by ID.
func (tfu *TemporaryFileUpdate) SetDeleterID(id int64) *TemporaryFileUpdate {
	tfu.mutation.SetDeleterID(id)
	return tfu
}

// SetNillableDeleterID sets the "deleter" edge to the Account entity by ID if the given value is not nil.
func (tfu *TemporaryFileUpdate) SetNillableDeleterID(id *int64) *TemporaryFileUpdate {
	if id != nil {
		tfu = tfu.SetDeleterID(*id)
	}
	return tfu
}

// SetDeleter sets the "deleter" edge to the Account entity.
func (tfu *TemporaryFileUpdate) SetDeleter(a *Account) *TemporaryFileUpdate {
	return tfu.SetDeleterID(a.ID)
}

// Mutation returns the TemporaryFileMutation object of the builder.
func (tfu *TemporaryFileUpdate) Mutation() *TemporaryFileMutation {
	return tfu.mutation
}

// ClearUpdater clears the "updater" edge to the Account entity.
func (tfu *TemporaryFileUpdate) ClearUpdater() *TemporaryFileUpdate {
	tfu.mutation.ClearUpdater()
	return tfu
}

// ClearDeleter clears the "deleter" edge to the Account entity.
func (tfu *TemporaryFileUpdate) ClearDeleter() *TemporaryFileUpdate {
	tfu.mutation.ClearDeleter()
	return tfu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tfu *TemporaryFileUpdate) Save(ctx context.Context) (int, error) {
	if err := tfu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, tfu.sqlSave, tfu.mutation, tfu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tfu *TemporaryFileUpdate) SaveX(ctx context.Context) int {
	affected, err := tfu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tfu *TemporaryFileUpdate) Exec(ctx context.Context) error {
	_, err := tfu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tfu *TemporaryFileUpdate) ExecX(ctx context.Context) {
	if err := tfu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tfu *TemporaryFileUpdate) defaults() error {
	if _, ok := tfu.mutation.UpdatedAt(); !ok {
		if temporaryfile.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("entmain: uninitialized temporaryfile.UpdateDefaultUpdatedAt (forgotten import entmain/runtime?)")
		}
		v := temporaryfile.UpdateDefaultUpdatedAt()
		tfu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (tfu *TemporaryFileUpdate) check() error {
	if v, ok := tfu.mutation.StorageType(); ok {
		if err := temporaryfile.StorageTypeValidator(v); err != nil {
			return &ValidationError{Name: "storage_type", err: fmt.Errorf(`entmain: validator failed for field "TemporaryFile.storage_type": %w`, err)}
		}
	}
	if tfu.mutation.OwnerCleared() && len(tfu.mutation.OwnerIDs()) > 0 {
		return errors.New(`entmain: clearing a required unique edge "TemporaryFile.owner"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tfu *TemporaryFileUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TemporaryFileUpdate {
	tfu.modifiers = append(tfu.modifiers, modifiers...)
	return tfu
}

func (tfu *TemporaryFileUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tfu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(temporaryfile.Table, temporaryfile.Columns, sqlgraph.NewFieldSpec(temporaryfile.FieldID, field.TypeInt64))
	if ps := tfu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tfu.mutation.UpdatedAt(); ok {
		_spec.SetField(temporaryfile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tfu.mutation.DeletedAt(); ok {
		_spec.SetField(temporaryfile.FieldDeletedAt, field.TypeTime, value)
	}
	if tfu.mutation.DeletedAtCleared() {
		_spec.ClearField(temporaryfile.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := tfu.mutation.Size(); ok {
		_spec.SetField(temporaryfile.FieldSize, field.TypeInt64, value)
	}
	if value, ok := tfu.mutation.AddedSize(); ok {
		_spec.AddField(temporaryfile.FieldSize, field.TypeInt64, value)
	}
	if tfu.mutation.SizeCleared() {
		_spec.ClearField(temporaryfile.FieldSize, field.TypeInt64)
	}
	if value, ok := tfu.mutation.SizeInStorage(); ok {
		_spec.SetField(temporaryfile.FieldSizeInStorage, field.TypeInt64, value)
	}
	if value, ok := tfu.mutation.AddedSizeInStorage(); ok {
		_spec.AddField(temporaryfile.FieldSizeInStorage, field.TypeInt64, value)
	}
	if value, ok := tfu.mutation.Sha256(); ok {
		_spec.SetField(temporaryfile.FieldSha256, field.TypeString, value)
	}
	if tfu.mutation.Sha256Cleared() {
		_spec.ClearField(temporaryfile.FieldSha256, field.TypeString)
	}
	if value, ok := tfu.mutation.MimeType(); ok {
		_spec.SetField(temporaryfile.FieldMimeType, field.TypeString, value)
	}
	if tfu.mutation.MimeTypeCleared() {
		_spec.ClearField(temporaryfile.FieldMimeType, field.TypeString)
	}
	if value, ok := tfu.mutation.StorageType(); ok {
		_spec.SetField(temporaryfile.FieldStorageType, field.TypeEnum, value)
	}
	if value, ok := tfu.mutation.BucketName(); ok {
		_spec.SetField(temporaryfile.FieldBucketName, field.TypeString, value)
	}
	if tfu.mutation.BucketNameCleared() {
		_spec.ClearField(temporaryfile.FieldBucketName, field.TypeString)
	}
	if value, ok := tfu.mutation.StoragePath(); ok {
		_spec.SetField(temporaryfile.FieldStoragePath, field.TypeString, value)
	}
	if value, ok := tfu.mutation.StorageFilename(); ok {
		_spec.SetField(temporaryfile.FieldStorageFilename, field.TypeString, value)
	}
	if value, ok := tfu.mutation.UploadToken(); ok {
		_spec.SetField(temporaryfile.FieldUploadToken, field.TypeString, value)
	}
	if value, ok := tfu.mutation.ConvertedToStoredFileAt(); ok {
		_spec.SetField(temporaryfile.FieldConvertedToStoredFileAt, field.TypeTime, value)
	}
	if tfu.mutation.ConvertedToStoredFileAtCleared() {
		_spec.ClearField(temporaryfile.FieldConvertedToStoredFileAt, field.TypeTime)
	}
	if value, ok := tfu.mutation.ExpiresAt(); ok {
		_spec.SetField(temporaryfile.FieldExpiresAt, field.TypeTime, value)
	}
	if tfu.mutation.ExpiresAtCleared() {
		_spec.ClearField(temporaryfile.FieldExpiresAt, field.TypeTime)
	}
	if tfu.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   temporaryfile.UpdaterTable,
			Columns: []string{temporaryfile.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tfu.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   temporaryfile.UpdaterTable,
			Columns: []string{temporaryfile.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tfu.mutation.DeleterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   temporaryfile.DeleterTable,
			Columns: []string{temporaryfile.DeleterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tfu.mutation.DeleterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   temporaryfile.DeleterTable,
			Columns: []string{temporaryfile.DeleterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(tfu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, tfu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{temporaryfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tfu.mutation.done = true
	return n, nil
}

// TemporaryFileUpdateOne is the builder for updating a single TemporaryFile entity.
type TemporaryFileUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TemporaryFileMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (tfuo *TemporaryFileUpdateOne) SetUpdatedAt(t time.Time) *TemporaryFileUpdateOne {
	tfuo.mutation.SetUpdatedAt(t)
	return tfuo
}

// SetUpdatedBy sets the "updated_by" field.
func (tfuo *TemporaryFileUpdateOne) SetUpdatedBy(i int64) *TemporaryFileUpdateOne {
	tfuo.mutation.SetUpdatedBy(i)
	return tfuo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableUpdatedBy(i *int64) *TemporaryFileUpdateOne {
	if i != nil {
		tfuo.SetUpdatedBy(*i)
	}
	return tfuo
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (tfuo *TemporaryFileUpdateOne) ClearUpdatedBy() *TemporaryFileUpdateOne {
	tfuo.mutation.ClearUpdatedBy()
	return tfuo
}

// SetDeletedBy sets the "deleted_by" field.
func (tfuo *TemporaryFileUpdateOne) SetDeletedBy(i int64) *TemporaryFileUpdateOne {
	tfuo.mutation.SetDeletedBy(i)
	return tfuo
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableDeletedBy(i *int64) *TemporaryFileUpdateOne {
	if i != nil {
		tfuo.SetDeletedBy(*i)
	}
	return tfuo
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (tfuo *TemporaryFileUpdateOne) ClearDeletedBy() *TemporaryFileUpdateOne {
	tfuo.mutation.ClearDeletedBy()
	return tfuo
}

// SetDeletedAt sets the "deleted_at" field.
func (tfuo *TemporaryFileUpdateOne) SetDeletedAt(t time.Time) *TemporaryFileUpdateOne {
	tfuo.mutation.SetDeletedAt(t)
	return tfuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableDeletedAt(t *time.Time) *TemporaryFileUpdateOne {
	if t != nil {
		tfuo.SetDeletedAt(*t)
	}
	return tfuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (tfuo *TemporaryFileUpdateOne) ClearDeletedAt() *TemporaryFileUpdateOne {
	tfuo.mutation.ClearDeletedAt()
	return tfuo
}

// SetSize sets the "size" field.
func (tfuo *TemporaryFileUpdateOne) SetSize(i int64) *TemporaryFileUpdateOne {
	tfuo.mutation.ResetSize()
	tfuo.mutation.SetSize(i)
	return tfuo
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableSize(i *int64) *TemporaryFileUpdateOne {
	if i != nil {
		tfuo.SetSize(*i)
	}
	return tfuo
}

// AddSize adds i to the "size" field.
func (tfuo *TemporaryFileUpdateOne) AddSize(i int64) *TemporaryFileUpdateOne {
	tfuo.mutation.AddSize(i)
	return tfuo
}

// ClearSize clears the value of the "size" field.
func (tfuo *TemporaryFileUpdateOne) ClearSize() *TemporaryFileUpdateOne {
	tfuo.mutation.ClearSize()
	return tfuo
}

// SetSizeInStorage sets the "size_in_storage" field.
func (tfuo *TemporaryFileUpdateOne) SetSizeInStorage(i int64) *TemporaryFileUpdateOne {
	tfuo.mutation.ResetSizeInStorage()
	tfuo.mutation.SetSizeInStorage(i)
	return tfuo
}

// SetNillableSizeInStorage sets the "size_in_storage" field if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableSizeInStorage(i *int64) *TemporaryFileUpdateOne {
	if i != nil {
		tfuo.SetSizeInStorage(*i)
	}
	return tfuo
}

// AddSizeInStorage adds i to the "size_in_storage" field.
func (tfuo *TemporaryFileUpdateOne) AddSizeInStorage(i int64) *TemporaryFileUpdateOne {
	tfuo.mutation.AddSizeInStorage(i)
	return tfuo
}

// SetSha256 sets the "sha256" field.
func (tfuo *TemporaryFileUpdateOne) SetSha256(s string) *TemporaryFileUpdateOne {
	tfuo.mutation.SetSha256(s)
	return tfuo
}

// SetNillableSha256 sets the "sha256" field if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableSha256(s *string) *TemporaryFileUpdateOne {
	if s != nil {
		tfuo.SetSha256(*s)
	}
	return tfuo
}

// ClearSha256 clears the value of the "sha256" field.
func (tfuo *TemporaryFileUpdateOne) ClearSha256() *TemporaryFileUpdateOne {
	tfuo.mutation.ClearSha256()
	return tfuo
}

// SetMimeType sets the "mime_type" field.
func (tfuo *TemporaryFileUpdateOne) SetMimeType(s string) *TemporaryFileUpdateOne {
	tfuo.mutation.SetMimeType(s)
	return tfuo
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableMimeType(s *string) *TemporaryFileUpdateOne {
	if s != nil {
		tfuo.SetMimeType(*s)
	}
	return tfuo
}

// ClearMimeType clears the value of the "mime_type" field.
func (tfuo *TemporaryFileUpdateOne) ClearMimeType() *TemporaryFileUpdateOne {
	tfuo.mutation.ClearMimeType()
	return tfuo
}

// SetStorageType sets the "storage_type" field.
func (tfuo *TemporaryFileUpdateOne) SetStorageType(st storagetype.StorageType) *TemporaryFileUpdateOne {
	tfuo.mutation.SetStorageType(st)
	return tfuo
}

// SetNillableStorageType sets the "storage_type" field if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableStorageType(st *storagetype.StorageType) *TemporaryFileUpdateOne {
	if st != nil {
		tfuo.SetStorageType(*st)
	}
	return tfuo
}

// SetBucketName sets the "bucket_name" field.
func (tfuo *TemporaryFileUpdateOne) SetBucketName(s string) *TemporaryFileUpdateOne {
	tfuo.mutation.SetBucketName(s)
	return tfuo
}

// SetNillableBucketName sets the "bucket_name" field if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableBucketName(s *string) *TemporaryFileUpdateOne {
	if s != nil {
		tfuo.SetBucketName(*s)
	}
	return tfuo
}

// ClearBucketName clears the value of the "bucket_name" field.
func (tfuo *TemporaryFileUpdateOne) ClearBucketName() *TemporaryFileUpdateOne {
	tfuo.mutation.ClearBucketName()
	return tfuo
}

// SetStoragePath sets the "storage_path" field.
func (tfuo *TemporaryFileUpdateOne) SetStoragePath(s string) *TemporaryFileUpdateOne {
	tfuo.mutation.SetStoragePath(s)
	return tfuo
}

// SetNillableStoragePath sets the "storage_path" field if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableStoragePath(s *string) *TemporaryFileUpdateOne {
	if s != nil {
		tfuo.SetStoragePath(*s)
	}
	return tfuo
}

// SetStorageFilename sets the "storage_filename" field.
func (tfuo *TemporaryFileUpdateOne) SetStorageFilename(s string) *TemporaryFileUpdateOne {
	tfuo.mutation.SetStorageFilename(s)
	return tfuo
}

// SetNillableStorageFilename sets the "storage_filename" field if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableStorageFilename(s *string) *TemporaryFileUpdateOne {
	if s != nil {
		tfuo.SetStorageFilename(*s)
	}
	return tfuo
}

// SetUploadToken sets the "upload_token" field.
func (tfuo *TemporaryFileUpdateOne) SetUploadToken(s string) *TemporaryFileUpdateOne {
	tfuo.mutation.SetUploadToken(s)
	return tfuo
}

// SetNillableUploadToken sets the "upload_token" field if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableUploadToken(s *string) *TemporaryFileUpdateOne {
	if s != nil {
		tfuo.SetUploadToken(*s)
	}
	return tfuo
}

// SetConvertedToStoredFileAt sets the "converted_to_stored_file_at" field.
func (tfuo *TemporaryFileUpdateOne) SetConvertedToStoredFileAt(t time.Time) *TemporaryFileUpdateOne {
	tfuo.mutation.SetConvertedToStoredFileAt(t)
	return tfuo
}

// SetNillableConvertedToStoredFileAt sets the "converted_to_stored_file_at" field if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableConvertedToStoredFileAt(t *time.Time) *TemporaryFileUpdateOne {
	if t != nil {
		tfuo.SetConvertedToStoredFileAt(*t)
	}
	return tfuo
}

// ClearConvertedToStoredFileAt clears the value of the "converted_to_stored_file_at" field.
func (tfuo *TemporaryFileUpdateOne) ClearConvertedToStoredFileAt() *TemporaryFileUpdateOne {
	tfuo.mutation.ClearConvertedToStoredFileAt()
	return tfuo
}

// SetExpiresAt sets the "expires_at" field.
func (tfuo *TemporaryFileUpdateOne) SetExpiresAt(t time.Time) *TemporaryFileUpdateOne {
	tfuo.mutation.SetExpiresAt(t)
	return tfuo
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableExpiresAt(t *time.Time) *TemporaryFileUpdateOne {
	if t != nil {
		tfuo.SetExpiresAt(*t)
	}
	return tfuo
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (tfuo *TemporaryFileUpdateOne) ClearExpiresAt() *TemporaryFileUpdateOne {
	tfuo.mutation.ClearExpiresAt()
	return tfuo
}

// SetUpdaterID sets the "updater" edge to the Account entity by ID.
func (tfuo *TemporaryFileUpdateOne) SetUpdaterID(id int64) *TemporaryFileUpdateOne {
	tfuo.mutation.SetUpdaterID(id)
	return tfuo
}

// SetNillableUpdaterID sets the "updater" edge to the Account entity by ID if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableUpdaterID(id *int64) *TemporaryFileUpdateOne {
	if id != nil {
		tfuo = tfuo.SetUpdaterID(*id)
	}
	return tfuo
}

// SetUpdater sets the "updater" edge to the Account entity.
func (tfuo *TemporaryFileUpdateOne) SetUpdater(a *Account) *TemporaryFileUpdateOne {
	return tfuo.SetUpdaterID(a.ID)
}

// SetDeleterID sets the "deleter" edge to the Account entity by ID.
func (tfuo *TemporaryFileUpdateOne) SetDeleterID(id int64) *TemporaryFileUpdateOne {
	tfuo.mutation.SetDeleterID(id)
	return tfuo
}

// SetNillableDeleterID sets the "deleter" edge to the Account entity by ID if the given value is not nil.
func (tfuo *TemporaryFileUpdateOne) SetNillableDeleterID(id *int64) *TemporaryFileUpdateOne {
	if id != nil {
		tfuo = tfuo.SetDeleterID(*id)
	}
	return tfuo
}

// SetDeleter sets the "deleter" edge to the Account entity.
func (tfuo *TemporaryFileUpdateOne) SetDeleter(a *Account) *TemporaryFileUpdateOne {
	return tfuo.SetDeleterID(a.ID)
}

// Mutation returns the TemporaryFileMutation object of the builder.
func (tfuo *TemporaryFileUpdateOne) Mutation() *TemporaryFileMutation {
	return tfuo.mutation
}

// ClearUpdater clears the "updater" edge to the Account entity.
func (tfuo *TemporaryFileUpdateOne) ClearUpdater() *TemporaryFileUpdateOne {
	tfuo.mutation.ClearUpdater()
	return tfuo
}

// ClearDeleter clears the "deleter" edge to the Account entity.
func (tfuo *TemporaryFileUpdateOne) ClearDeleter() *TemporaryFileUpdateOne {
	tfuo.mutation.ClearDeleter()
	return tfuo
}

// Where appends a list predicates to the TemporaryFileUpdate builder.
func (tfuo *TemporaryFileUpdateOne) Where(ps ...predicate.TemporaryFile) *TemporaryFileUpdateOne {
	tfuo.mutation.Where(ps...)
	return tfuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tfuo *TemporaryFileUpdateOne) Select(field string, fields ...string) *TemporaryFileUpdateOne {
	tfuo.fields = append([]string{field}, fields...)
	return tfuo
}

// Save executes the query and returns the updated TemporaryFile entity.
func (tfuo *TemporaryFileUpdateOne) Save(ctx context.Context) (*TemporaryFile, error) {
	if err := tfuo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, tfuo.sqlSave, tfuo.mutation, tfuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tfuo *TemporaryFileUpdateOne) SaveX(ctx context.Context) *TemporaryFile {
	node, err := tfuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tfuo *TemporaryFileUpdateOne) Exec(ctx context.Context) error {
	_, err := tfuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tfuo *TemporaryFileUpdateOne) ExecX(ctx context.Context) {
	if err := tfuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tfuo *TemporaryFileUpdateOne) defaults() error {
	if _, ok := tfuo.mutation.UpdatedAt(); !ok {
		if temporaryfile.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("entmain: uninitialized temporaryfile.UpdateDefaultUpdatedAt (forgotten import entmain/runtime?)")
		}
		v := temporaryfile.UpdateDefaultUpdatedAt()
		tfuo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (tfuo *TemporaryFileUpdateOne) check() error {
	if v, ok := tfuo.mutation.StorageType(); ok {
		if err := temporaryfile.StorageTypeValidator(v); err != nil {
			return &ValidationError{Name: "storage_type", err: fmt.Errorf(`entmain: validator failed for field "TemporaryFile.storage_type": %w`, err)}
		}
	}
	if tfuo.mutation.OwnerCleared() && len(tfuo.mutation.OwnerIDs()) > 0 {
		return errors.New(`entmain: clearing a required unique edge "TemporaryFile.owner"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tfuo *TemporaryFileUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TemporaryFileUpdateOne {
	tfuo.modifiers = append(tfuo.modifiers, modifiers...)
	return tfuo
}

func (tfuo *TemporaryFileUpdateOne) sqlSave(ctx context.Context) (_node *TemporaryFile, err error) {
	if err := tfuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(temporaryfile.Table, temporaryfile.Columns, sqlgraph.NewFieldSpec(temporaryfile.FieldID, field.TypeInt64))
	id, ok := tfuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`entmain: missing "TemporaryFile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tfuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, temporaryfile.FieldID)
		for _, f := range fields {
			if !temporaryfile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("entmain: invalid field %q for query", f)}
			}
			if f != temporaryfile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tfuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tfuo.mutation.UpdatedAt(); ok {
		_spec.SetField(temporaryfile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tfuo.mutation.DeletedAt(); ok {
		_spec.SetField(temporaryfile.FieldDeletedAt, field.TypeTime, value)
	}
	if tfuo.mutation.DeletedAtCleared() {
		_spec.ClearField(temporaryfile.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := tfuo.mutation.Size(); ok {
		_spec.SetField(temporaryfile.FieldSize, field.TypeInt64, value)
	}
	if value, ok := tfuo.mutation.AddedSize(); ok {
		_spec.AddField(temporaryfile.FieldSize, field.TypeInt64, value)
	}
	if tfuo.mutation.SizeCleared() {
		_spec.ClearField(temporaryfile.FieldSize, field.TypeInt64)
	}
	if value, ok := tfuo.mutation.SizeInStorage(); ok {
		_spec.SetField(temporaryfile.FieldSizeInStorage, field.TypeInt64, value)
	}
	if value, ok := tfuo.mutation.AddedSizeInStorage(); ok {
		_spec.AddField(temporaryfile.FieldSizeInStorage, field.TypeInt64, value)
	}
	if value, ok := tfuo.mutation.Sha256(); ok {
		_spec.SetField(temporaryfile.FieldSha256, field.TypeString, value)
	}
	if tfuo.mutation.Sha256Cleared() {
		_spec.ClearField(temporaryfile.FieldSha256, field.TypeString)
	}
	if value, ok := tfuo.mutation.MimeType(); ok {
		_spec.SetField(temporaryfile.FieldMimeType, field.TypeString, value)
	}
	if tfuo.mutation.MimeTypeCleared() {
		_spec.ClearField(temporaryfile.FieldMimeType, field.TypeString)
	}
	if value, ok := tfuo.mutation.StorageType(); ok {
		_spec.SetField(temporaryfile.FieldStorageType, field.TypeEnum, value)
	}
	if value, ok := tfuo.mutation.BucketName(); ok {
		_spec.SetField(temporaryfile.FieldBucketName, field.TypeString, value)
	}
	if tfuo.mutation.BucketNameCleared() {
		_spec.ClearField(temporaryfile.FieldBucketName, field.TypeString)
	}
	if value, ok := tfuo.mutation.StoragePath(); ok {
		_spec.SetField(temporaryfile.FieldStoragePath, field.TypeString, value)
	}
	if value, ok := tfuo.mutation.StorageFilename(); ok {
		_spec.SetField(temporaryfile.FieldStorageFilename, field.TypeString, value)
	}
	if value, ok := tfuo.mutation.UploadToken(); ok {
		_spec.SetField(temporaryfile.FieldUploadToken, field.TypeString, value)
	}
	if value, ok := tfuo.mutation.ConvertedToStoredFileAt(); ok {
		_spec.SetField(temporaryfile.FieldConvertedToStoredFileAt, field.TypeTime, value)
	}
	if tfuo.mutation.ConvertedToStoredFileAtCleared() {
		_spec.ClearField(temporaryfile.FieldConvertedToStoredFileAt, field.TypeTime)
	}
	if value, ok := tfuo.mutation.ExpiresAt(); ok {
		_spec.SetField(temporaryfile.FieldExpiresAt, field.TypeTime, value)
	}
	if tfuo.mutation.ExpiresAtCleared() {
		_spec.ClearField(temporaryfile.FieldExpiresAt, field.TypeTime)
	}
	if tfuo.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   temporaryfile.UpdaterTable,
			Columns: []string{temporaryfile.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tfuo.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   temporaryfile.UpdaterTable,
			Columns: []string{temporaryfile.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tfuo.mutation.DeleterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   temporaryfile.DeleterTable,
			Columns: []string{temporaryfile.DeleterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tfuo.mutation.DeleterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   temporaryfile.DeleterTable,
			Columns: []string{temporaryfile.DeleterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(tfuo.modifiers...)
	_node = &TemporaryFile{config: tfuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tfuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{temporaryfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tfuo.mutation.done = true
	return _node, nil
}
