// Code generated by ent, DO NOT EDIT.

package entmain

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/simpledms/simpledms/db/entmain/account"
	"github.com/simpledms/simpledms/db/entmain/webauthnchallenge"
)

// WebAuthnChallenge is the model entity for the WebAuthnChallenge schema.
type WebAuthnChallenge struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ChallengeID holds the value of the "challenge_id" field.
	ChallengeID string `json:"challenge_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int64 `json:"account_id,omitempty"`
	// ClientKey holds the value of the "client_key" field.
	ClientKey *string `json:"client_key,omitempty"`
	// Ceremony holds the value of the "ceremony" field.
	Ceremony string `json:"ceremony,omitempty"`
	// SessionDataJSON holds the value of the "session_data_json" field.
	SessionDataJSON []byte `json:"-"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// UsedAt holds the value of the "used_at" field.
	UsedAt *time.Time `json:"used_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WebAuthnChallengeQuery when eager-loading is set.
	Edges        WebAuthnChallengeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WebAuthnChallengeEdges holds the relations/edges for other nodes in the graph.
type WebAuthnChallengeEdges struct {
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e WebAuthnChallengeEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*WebAuthnChallenge) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case webauthnchallenge.FieldSessionDataJSON:
			values[i] = new([]byte)
		case webauthnchallenge.FieldID, webauthnchallenge.FieldAccountID:
			values[i] = new(sql.NullInt64)
		case webauthnchallenge.FieldChallengeID, webauthnchallenge.FieldClientKey, webauthnchallenge.FieldCeremony:
			values[i] = new(sql.NullString)
		case webauthnchallenge.FieldExpiresAt, webauthnchallenge.FieldUsedAt, webauthnchallenge.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the WebAuthnChallenge fields.
func (_m *WebAuthnChallenge) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case webauthnchallenge.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case webauthnchallenge.FieldChallengeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field challenge_id", values[i])
			} else if value.Valid {
				_m.ChallengeID = value.String
			}
		case webauthnchallenge.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case webauthnchallenge.FieldClientKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_key", values[i])
			} else if value.Valid {
				_m.ClientKey = new(string)
				*_m.ClientKey = value.String
			}
		case webauthnchallenge.FieldCeremony:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ceremony", values[i])
			} else if value.Valid {
				_m.Ceremony = value.String
			}
		case webauthnchallenge.FieldSessionDataJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field session_data_json", values[i])
			} else if value != nil {
				_m.SessionDataJSON = *value
			}
		case webauthnchallenge.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case webauthnchallenge.FieldUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field used_at", values[i])
			} else if value.Valid {
				_m.UsedAt = new(time.Time)
				*_m.UsedAt = value.Time
			}
		case webauthnchallenge.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the WebAuthnChallenge.
// This includes values selected through modifiers, order, etc.
func (_m *WebAuthnChallenge) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccount queries the "account" edge of the WebAuthnChallenge entity.
func (_m *WebAuthnChallenge) QueryAccount() *AccountQuery {
	return NewWebAuthnChallengeClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this WebAuthnChallenge.
// Note that you need to call WebAuthnChallenge.Unwrap() before calling this method if this WebAuthnChallenge
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *WebAuthnChallenge) Update() *WebAuthnChallengeUpdateOne {
	return NewWebAuthnChallengeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the WebAuthnChallenge entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *WebAuthnChallenge) Unwrap() *WebAuthnChallenge {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("entmain: WebAuthnChallenge is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *WebAuthnChallenge) String() string {
	var builder strings.Builder
	builder.WriteString("WebAuthnChallenge(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("challenge_id=")
	builder.WriteString(_m.ChallengeID)
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ClientKey; v != nil {
		builder.WriteString("client_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("ceremony=")
	builder.WriteString(_m.Ceremony)
	builder.WriteString(", ")
	builder.WriteString("session_data_json=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UsedAt; v != nil {
		builder.WriteString("used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// WebAuthnChallenges is a parsable slice of WebAuthnChallenge.
type WebAuthnChallenges []*WebAuthnChallenge
