// Code generated by "enumer -type=Status -sql -ent -json -empty_string -output=status.gen.go"; DO NOT EDIT

package status

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const _Status_name = "UnknownPendingAcceptedRejected"

var _Status_index = [...]uint8{0, 7, 14, 22, 30}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		if i == 0 {
			return ""
		}
		return fmt.Sprintf("Status(%d)", i)
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}

var _StatusNameToValue_map = map[string]Status{
	_Status_name[0:7]:   0,
	_Status_name[7:14]:  1,
	_Status_name[14:22]: 2,
	_Status_name[22:30]: 3,
}

func StatusString(s string) (Status, error) {
	if val, ok := _StatusNameToValue_map[s]; ok {
		return val, nil
	}
	if s == "" && _StatusHasNoNullValue() { // fix for case when db field is NOT NULL, then an empty string is returned from db for 0 values
		return 0, nil
	}
	return 0, fmt.Errorf("%s does not belong to Status values", s)
}

func _StatusHasNoNullValue() bool {
	for _, val := range _StatusNameToValue_map {
		if val == 0 {
			return false
		}
	}
	return true
}

func (i Status) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

func (i *Status) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Status should be a string, got %s", data)
	}

	var err error
	*i, err = StatusString(s)
	return err
}

func (i Status) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Status) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := StatusString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

func (i Status) Values() []string {
	return []string{
		Unknown.String(),
		Pending.String(),
		Accepted.String(),
		Rejected.String(),
	}
}
