// Code generated by ent, DO NOT EDIT.

package entmain

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/simpledms/simpledms/db/entmain/account"
	"github.com/simpledms/simpledms/db/entmain/mail"
	"github.com/simpledms/simpledms/db/entmain/temporaryfile"
	"github.com/simpledms/simpledms/db/entmain/tenant"
	"github.com/simpledms/simpledms/db/entmain/tenantaccountassignment"
	"github.com/simpledms/simpledms/db/entx"
	"github.com/simpledms/simpledms/model/common/language"
	"github.com/simpledms/simpledms/model/common/mainrole"
)

// AccountCreate is the builder for creating a Account entity.
type AccountCreate struct {
	config
	mutation *AccountMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (ac *AccountCreate) SetCreatedAt(t time.Time) *AccountCreate {
	ac.mutation.SetCreatedAt(t)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *AccountCreate) SetNillableCreatedAt(t *time.Time) *AccountCreate {
	if t != nil {
		ac.SetCreatedAt(*t)
	}
	return ac
}

// SetCreatedBy sets the "created_by" field.
func (ac *AccountCreate) SetCreatedBy(i int64) *AccountCreate {
	ac.mutation.SetCreatedBy(i)
	return ac
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (ac *AccountCreate) SetNillableCreatedBy(i *int64) *AccountCreate {
	if i != nil {
		ac.SetCreatedBy(*i)
	}
	return ac
}

// SetUpdatedAt sets the "updated_at" field.
func (ac *AccountCreate) SetUpdatedAt(t time.Time) *AccountCreate {
	ac.mutation.SetUpdatedAt(t)
	return ac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ac *AccountCreate) SetNillableUpdatedAt(t *time.Time) *AccountCreate {
	if t != nil {
		ac.SetUpdatedAt(*t)
	}
	return ac
}

// SetUpdatedBy sets the "updated_by" field.
func (ac *AccountCreate) SetUpdatedBy(i int64) *AccountCreate {
	ac.mutation.SetUpdatedBy(i)
	return ac
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (ac *AccountCreate) SetNillableUpdatedBy(i *int64) *AccountCreate {
	if i != nil {
		ac.SetUpdatedBy(*i)
	}
	return ac
}

// SetDeletedBy sets the "deleted_by" field.
func (ac *AccountCreate) SetDeletedBy(i int64) *AccountCreate {
	ac.mutation.SetDeletedBy(i)
	return ac
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (ac *AccountCreate) SetNillableDeletedBy(i *int64) *AccountCreate {
	if i != nil {
		ac.SetDeletedBy(*i)
	}
	return ac
}

// SetDeletedAt sets the "deleted_at" field.
func (ac *AccountCreate) SetDeletedAt(t time.Time) *AccountCreate {
	ac.mutation.SetDeletedAt(t)
	return ac
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ac *AccountCreate) SetNillableDeletedAt(t *time.Time) *AccountCreate {
	if t != nil {
		ac.SetDeletedAt(*t)
	}
	return ac
}

// SetPublicID sets the "public_id" field.
func (ac *AccountCreate) SetPublicID(et entx.CIText) *AccountCreate {
	ac.mutation.SetPublicID(et)
	return ac
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (ac *AccountCreate) SetNillablePublicID(et *entx.CIText) *AccountCreate {
	if et != nil {
		ac.SetPublicID(*et)
	}
	return ac
}

// SetEmail sets the "email" field.
func (ac *AccountCreate) SetEmail(et entx.CIText) *AccountCreate {
	ac.mutation.SetEmail(et)
	return ac
}

// SetFirstName sets the "first_name" field.
func (ac *AccountCreate) SetFirstName(s string) *AccountCreate {
	ac.mutation.SetFirstName(s)
	return ac
}

// SetLastName sets the "last_name" field.
func (ac *AccountCreate) SetLastName(s string) *AccountCreate {
	ac.mutation.SetLastName(s)
	return ac
}

// SetLanguage sets the "language" field.
func (ac *AccountCreate) SetLanguage(l language.Language) *AccountCreate {
	ac.mutation.SetLanguage(l)
	return ac
}

// SetSubscribedToNewsletterAt sets the "subscribed_to_newsletter_at" field.
func (ac *AccountCreate) SetSubscribedToNewsletterAt(t time.Time) *AccountCreate {
	ac.mutation.SetSubscribedToNewsletterAt(t)
	return ac
}

// SetNillableSubscribedToNewsletterAt sets the "subscribed_to_newsletter_at" field if the given value is not nil.
func (ac *AccountCreate) SetNillableSubscribedToNewsletterAt(t *time.Time) *AccountCreate {
	if t != nil {
		ac.SetSubscribedToNewsletterAt(*t)
	}
	return ac
}

// SetPasswordSalt sets the "password_salt" field.
func (ac *AccountCreate) SetPasswordSalt(s string) *AccountCreate {
	ac.mutation.SetPasswordSalt(s)
	return ac
}

// SetNillablePasswordSalt sets the "password_salt" field if the given value is not nil.
func (ac *AccountCreate) SetNillablePasswordSalt(s *string) *AccountCreate {
	if s != nil {
		ac.SetPasswordSalt(*s)
	}
	return ac
}

// SetPasswordHash sets the "password_hash" field.
func (ac *AccountCreate) SetPasswordHash(s string) *AccountCreate {
	ac.mutation.SetPasswordHash(s)
	return ac
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (ac *AccountCreate) SetNillablePasswordHash(s *string) *AccountCreate {
	if s != nil {
		ac.SetPasswordHash(*s)
	}
	return ac
}

// SetTemporaryPasswordSalt sets the "temporary_password_salt" field.
func (ac *AccountCreate) SetTemporaryPasswordSalt(s string) *AccountCreate {
	ac.mutation.SetTemporaryPasswordSalt(s)
	return ac
}

// SetNillableTemporaryPasswordSalt sets the "temporary_password_salt" field if the given value is not nil.
func (ac *AccountCreate) SetNillableTemporaryPasswordSalt(s *string) *AccountCreate {
	if s != nil {
		ac.SetTemporaryPasswordSalt(*s)
	}
	return ac
}

// SetTemporaryPasswordHash sets the "temporary_password_hash" field.
func (ac *AccountCreate) SetTemporaryPasswordHash(s string) *AccountCreate {
	ac.mutation.SetTemporaryPasswordHash(s)
	return ac
}

// SetNillableTemporaryPasswordHash sets the "temporary_password_hash" field if the given value is not nil.
func (ac *AccountCreate) SetNillableTemporaryPasswordHash(s *string) *AccountCreate {
	if s != nil {
		ac.SetTemporaryPasswordHash(*s)
	}
	return ac
}

// SetTemporaryPasswordExpiresAt sets the "temporary_password_expires_at" field.
func (ac *AccountCreate) SetTemporaryPasswordExpiresAt(t time.Time) *AccountCreate {
	ac.mutation.SetTemporaryPasswordExpiresAt(t)
	return ac
}

// SetNillableTemporaryPasswordExpiresAt sets the "temporary_password_expires_at" field if the given value is not nil.
func (ac *AccountCreate) SetNillableTemporaryPasswordExpiresAt(t *time.Time) *AccountCreate {
	if t != nil {
		ac.SetTemporaryPasswordExpiresAt(*t)
	}
	return ac
}

// SetTemporaryTwoFactorAuthKeyEncrypted sets the "temporary_two_factor_auth_key_encrypted" field.
func (ac *AccountCreate) SetTemporaryTwoFactorAuthKeyEncrypted(s string) *AccountCreate {
	ac.mutation.SetTemporaryTwoFactorAuthKeyEncrypted(s)
	return ac
}

// SetNillableTemporaryTwoFactorAuthKeyEncrypted sets the "temporary_two_factor_auth_key_encrypted" field if the given value is not nil.
func (ac *AccountCreate) SetNillableTemporaryTwoFactorAuthKeyEncrypted(s *string) *AccountCreate {
	if s != nil {
		ac.SetTemporaryTwoFactorAuthKeyEncrypted(*s)
	}
	return ac
}

// SetTwoFactoryAuthKeyEncrypted sets the "two_factory_auth_key_encrypted" field.
func (ac *AccountCreate) SetTwoFactoryAuthKeyEncrypted(s string) *AccountCreate {
	ac.mutation.SetTwoFactoryAuthKeyEncrypted(s)
	return ac
}

// SetNillableTwoFactoryAuthKeyEncrypted sets the "two_factory_auth_key_encrypted" field if the given value is not nil.
func (ac *AccountCreate) SetNillableTwoFactoryAuthKeyEncrypted(s *string) *AccountCreate {
	if s != nil {
		ac.SetTwoFactoryAuthKeyEncrypted(*s)
	}
	return ac
}

// SetTwoFactorAuthRecoveryCodeSalt sets the "two_factor_auth_recovery_code_salt" field.
func (ac *AccountCreate) SetTwoFactorAuthRecoveryCodeSalt(s string) *AccountCreate {
	ac.mutation.SetTwoFactorAuthRecoveryCodeSalt(s)
	return ac
}

// SetNillableTwoFactorAuthRecoveryCodeSalt sets the "two_factor_auth_recovery_code_salt" field if the given value is not nil.
func (ac *AccountCreate) SetNillableTwoFactorAuthRecoveryCodeSalt(s *string) *AccountCreate {
	if s != nil {
		ac.SetTwoFactorAuthRecoveryCodeSalt(*s)
	}
	return ac
}

// SetTwoFactorAuthRecoveryCodeHashes sets the "two_factor_auth_recovery_code_hashes" field.
func (ac *AccountCreate) SetTwoFactorAuthRecoveryCodeHashes(s []string) *AccountCreate {
	ac.mutation.SetTwoFactorAuthRecoveryCodeHashes(s)
	return ac
}

// SetLastLoginAttemptAt sets the "last_login_attempt_at" field.
func (ac *AccountCreate) SetLastLoginAttemptAt(t time.Time) *AccountCreate {
	ac.mutation.SetLastLoginAttemptAt(t)
	return ac
}

// SetNillableLastLoginAttemptAt sets the "last_login_attempt_at" field if the given value is not nil.
func (ac *AccountCreate) SetNillableLastLoginAttemptAt(t *time.Time) *AccountCreate {
	if t != nil {
		ac.SetLastLoginAttemptAt(*t)
	}
	return ac
}

// SetRole sets the "role" field.
func (ac *AccountCreate) SetRole(mr mainrole.MainRole) *AccountCreate {
	ac.mutation.SetRole(mr)
	return ac
}

// SetID sets the "id" field.
func (ac *AccountCreate) SetID(i int64) *AccountCreate {
	ac.mutation.SetID(i)
	return ac
}

// AddTenantIDs adds the "tenants" edge to the Tenant entity by IDs.
func (ac *AccountCreate) AddTenantIDs(ids ...int64) *AccountCreate {
	ac.mutation.AddTenantIDs(ids...)
	return ac
}

// AddTenants adds the "tenants" edges to the Tenant entity.
func (ac *AccountCreate) AddTenants(t ...*Tenant) *AccountCreate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ac.AddTenantIDs(ids...)
}

// AddReceivedMailIDs adds the "received_mails" edge to the Mail entity by IDs.
func (ac *AccountCreate) AddReceivedMailIDs(ids ...int64) *AccountCreate {
	ac.mutation.AddReceivedMailIDs(ids...)
	return ac
}

// AddReceivedMails adds the "received_mails" edges to the Mail entity.
func (ac *AccountCreate) AddReceivedMails(m ...*Mail) *AccountCreate {
	ids := make([]int64, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return ac.AddReceivedMailIDs(ids...)
}

// AddTemporaryFileIDs adds the "temporary_files" edge to the TemporaryFile entity by IDs.
func (ac *AccountCreate) AddTemporaryFileIDs(ids ...int64) *AccountCreate {
	ac.mutation.AddTemporaryFileIDs(ids...)
	return ac
}

// AddTemporaryFiles adds the "temporary_files" edges to the TemporaryFile entity.
func (ac *AccountCreate) AddTemporaryFiles(t ...*TemporaryFile) *AccountCreate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ac.AddTemporaryFileIDs(ids...)
}

// AddTenantAssignmentIDs adds the "tenant_assignment" edge to the TenantAccountAssignment entity by IDs.
func (ac *AccountCreate) AddTenantAssignmentIDs(ids ...int64) *AccountCreate {
	ac.mutation.AddTenantAssignmentIDs(ids...)
	return ac
}

// AddTenantAssignment adds the "tenant_assignment" edges to the TenantAccountAssignment entity.
func (ac *AccountCreate) AddTenantAssignment(t ...*TenantAccountAssignment) *AccountCreate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return ac.AddTenantAssignmentIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (ac *AccountCreate) Mutation() *AccountMutation {
	return ac.mutation
}

// Save creates the Account in the database.
func (ac *AccountCreate) Save(ctx context.Context) (*Account, error) {
	if err := ac.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AccountCreate) SaveX(ctx context.Context) *Account {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AccountCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AccountCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AccountCreate) defaults() error {
	if _, ok := ac.mutation.CreatedAt(); !ok {
		if account.DefaultCreatedAt == nil {
			return fmt.Errorf("entmain: uninitialized account.DefaultCreatedAt (forgotten import entmain/runtime?)")
		}
		v := account.DefaultCreatedAt()
		ac.mutation.SetCreatedAt(v)
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		if account.DefaultUpdatedAt == nil {
			return fmt.Errorf("entmain: uninitialized account.DefaultUpdatedAt (forgotten import entmain/runtime?)")
		}
		v := account.DefaultUpdatedAt()
		ac.mutation.SetUpdatedAt(v)
	}
	if _, ok := ac.mutation.PublicID(); !ok {
		if account.DefaultPublicID == nil {
			return fmt.Errorf("entmain: uninitialized account.DefaultPublicID (forgotten import entmain/runtime?)")
		}
		v := account.DefaultPublicID()
		ac.mutation.SetPublicID(v)
	}
	if _, ok := ac.mutation.PasswordSalt(); !ok {
		v := account.DefaultPasswordSalt
		ac.mutation.SetPasswordSalt(v)
	}
	if _, ok := ac.mutation.PasswordHash(); !ok {
		v := account.DefaultPasswordHash
		ac.mutation.SetPasswordHash(v)
	}
	if _, ok := ac.mutation.TemporaryPasswordSalt(); !ok {
		v := account.DefaultTemporaryPasswordSalt
		ac.mutation.SetTemporaryPasswordSalt(v)
	}
	if _, ok := ac.mutation.TemporaryPasswordHash(); !ok {
		v := account.DefaultTemporaryPasswordHash
		ac.mutation.SetTemporaryPasswordHash(v)
	}
	if _, ok := ac.mutation.TemporaryPasswordExpiresAt(); !ok {
		v := account.DefaultTemporaryPasswordExpiresAt
		ac.mutation.SetTemporaryPasswordExpiresAt(v)
	}
	if _, ok := ac.mutation.TemporaryTwoFactorAuthKeyEncrypted(); !ok {
		v := account.DefaultTemporaryTwoFactorAuthKeyEncrypted
		ac.mutation.SetTemporaryTwoFactorAuthKeyEncrypted(v)
	}
	if _, ok := ac.mutation.TwoFactoryAuthKeyEncrypted(); !ok {
		v := account.DefaultTwoFactoryAuthKeyEncrypted
		ac.mutation.SetTwoFactoryAuthKeyEncrypted(v)
	}
	if _, ok := ac.mutation.TwoFactorAuthRecoveryCodeSalt(); !ok {
		v := account.DefaultTwoFactorAuthRecoveryCodeSalt
		ac.mutation.SetTwoFactorAuthRecoveryCodeSalt(v)
	}
	if _, ok := ac.mutation.TwoFactorAuthRecoveryCodeHashes(); !ok {
		v := account.DefaultTwoFactorAuthRecoveryCodeHashes
		ac.mutation.SetTwoFactorAuthRecoveryCodeHashes(v)
	}
	if _, ok := ac.mutation.LastLoginAttemptAt(); !ok {
		v := account.DefaultLastLoginAttemptAt
		ac.mutation.SetLastLoginAttemptAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ac *AccountCreate) check() error {
	if _, ok := ac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`entmain: missing required field "Account.created_at"`)}
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`entmain: missing required field "Account.updated_at"`)}
	}
	if _, ok := ac.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`entmain: missing required field "Account.public_id"`)}
	}
	if _, ok := ac.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`entmain: missing required field "Account.email"`)}
	}
	if _, ok := ac.mutation.FirstName(); !ok {
		return &ValidationError{Name: "first_name", err: errors.New(`entmain: missing required field "Account.first_name"`)}
	}
	if _, ok := ac.mutation.LastName(); !ok {
		return &ValidationError{Name: "last_name", err: errors.New(`entmain: missing required field "Account.last_name"`)}
	}
	if _, ok := ac.mutation.Language(); !ok {
		return &ValidationError{Name: "language", err: errors.New(`entmain: missing required field "Account.language"`)}
	}
	if v, ok := ac.mutation.Language(); ok {
		if err := account.LanguageValidator(v); err != nil {
			return &ValidationError{Name: "language", err: fmt.Errorf(`entmain: validator failed for field "Account.language": %w`, err)}
		}
	}
	if _, ok := ac.mutation.PasswordSalt(); !ok {
		return &ValidationError{Name: "password_salt", err: errors.New(`entmain: missing required field "Account.password_salt"`)}
	}
	if _, ok := ac.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`entmain: missing required field "Account.password_hash"`)}
	}
	if _, ok := ac.mutation.TemporaryPasswordSalt(); !ok {
		return &ValidationError{Name: "temporary_password_salt", err: errors.New(`entmain: missing required field "Account.temporary_password_salt"`)}
	}
	if _, ok := ac.mutation.TemporaryPasswordHash(); !ok {
		return &ValidationError{Name: "temporary_password_hash", err: errors.New(`entmain: missing required field "Account.temporary_password_hash"`)}
	}
	if _, ok := ac.mutation.TemporaryTwoFactorAuthKeyEncrypted(); !ok {
		return &ValidationError{Name: "temporary_two_factor_auth_key_encrypted", err: errors.New(`entmain: missing required field "Account.temporary_two_factor_auth_key_encrypted"`)}
	}
	if _, ok := ac.mutation.TwoFactoryAuthKeyEncrypted(); !ok {
		return &ValidationError{Name: "two_factory_auth_key_encrypted", err: errors.New(`entmain: missing required field "Account.two_factory_auth_key_encrypted"`)}
	}
	if _, ok := ac.mutation.TwoFactorAuthRecoveryCodeSalt(); !ok {
		return &ValidationError{Name: "two_factor_auth_recovery_code_salt", err: errors.New(`entmain: missing required field "Account.two_factor_auth_recovery_code_salt"`)}
	}
	if _, ok := ac.mutation.TwoFactorAuthRecoveryCodeHashes(); !ok {
		return &ValidationError{Name: "two_factor_auth_recovery_code_hashes", err: errors.New(`entmain: missing required field "Account.two_factor_auth_recovery_code_hashes"`)}
	}
	if _, ok := ac.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`entmain: missing required field "Account.role"`)}
	}
	if v, ok := ac.mutation.Role(); ok {
		if err := account.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`entmain: validator failed for field "Account.role": %w`, err)}
		}
	}
	return nil
}

func (ac *AccountCreate) sqlSave(ctx context.Context) (*Account, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AccountCreate) createSpec() (*Account, *sqlgraph.CreateSpec) {
	var (
		_node = &Account{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(account.Table, sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.SetField(account.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ac.mutation.CreatedBy(); ok {
		_spec.SetField(account.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = value
	}
	if value, ok := ac.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ac.mutation.UpdatedBy(); ok {
		_spec.SetField(account.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = value
	}
	if value, ok := ac.mutation.DeletedBy(); ok {
		_spec.SetField(account.FieldDeletedBy, field.TypeInt64, value)
		_node.DeletedBy = value
	}
	if value, ok := ac.mutation.DeletedAt(); ok {
		_spec.SetField(account.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := ac.mutation.PublicID(); ok {
		_spec.SetField(account.FieldPublicID, field.TypeString, value)
		_node.PublicID = value
	}
	if value, ok := ac.mutation.Email(); ok {
		_spec.SetField(account.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := ac.mutation.FirstName(); ok {
		_spec.SetField(account.FieldFirstName, field.TypeString, value)
		_node.FirstName = value
	}
	if value, ok := ac.mutation.LastName(); ok {
		_spec.SetField(account.FieldLastName, field.TypeString, value)
		_node.LastName = value
	}
	if value, ok := ac.mutation.Language(); ok {
		_spec.SetField(account.FieldLanguage, field.TypeEnum, value)
		_node.Language = value
	}
	if value, ok := ac.mutation.SubscribedToNewsletterAt(); ok {
		_spec.SetField(account.FieldSubscribedToNewsletterAt, field.TypeTime, value)
		_node.SubscribedToNewsletterAt = &value
	}
	if value, ok := ac.mutation.PasswordSalt(); ok {
		_spec.SetField(account.FieldPasswordSalt, field.TypeString, value)
		_node.PasswordSalt = value
	}
	if value, ok := ac.mutation.PasswordHash(); ok {
		_spec.SetField(account.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := ac.mutation.TemporaryPasswordSalt(); ok {
		_spec.SetField(account.FieldTemporaryPasswordSalt, field.TypeString, value)
		_node.TemporaryPasswordSalt = value
	}
	if value, ok := ac.mutation.TemporaryPasswordHash(); ok {
		_spec.SetField(account.FieldTemporaryPasswordHash, field.TypeString, value)
		_node.TemporaryPasswordHash = value
	}
	if value, ok := ac.mutation.TemporaryPasswordExpiresAt(); ok {
		_spec.SetField(account.FieldTemporaryPasswordExpiresAt, field.TypeTime, value)
		_node.TemporaryPasswordExpiresAt = value
	}
	if value, ok := ac.mutation.TemporaryTwoFactorAuthKeyEncrypted(); ok {
		_spec.SetField(account.FieldTemporaryTwoFactorAuthKeyEncrypted, field.TypeString, value)
		_node.TemporaryTwoFactorAuthKeyEncrypted = value
	}
	if value, ok := ac.mutation.TwoFactoryAuthKeyEncrypted(); ok {
		_spec.SetField(account.FieldTwoFactoryAuthKeyEncrypted, field.TypeString, value)
		_node.TwoFactoryAuthKeyEncrypted = value
	}
	if value, ok := ac.mutation.TwoFactorAuthRecoveryCodeSalt(); ok {
		_spec.SetField(account.FieldTwoFactorAuthRecoveryCodeSalt, field.TypeString, value)
		_node.TwoFactorAuthRecoveryCodeSalt = value
	}
	if value, ok := ac.mutation.TwoFactorAuthRecoveryCodeHashes(); ok {
		_spec.SetField(account.FieldTwoFactorAuthRecoveryCodeHashes, field.TypeJSON, value)
		_node.TwoFactorAuthRecoveryCodeHashes = value
	}
	if value, ok := ac.mutation.LastLoginAttemptAt(); ok {
		_spec.SetField(account.FieldLastLoginAttemptAt, field.TypeTime, value)
		_node.LastLoginAttemptAt = value
	}
	if value, ok := ac.mutation.Role(); ok {
		_spec.SetField(account.FieldRole, field.TypeEnum, value)
		_node.Role = value
	}
	if nodes := ac.mutation.TenantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   account.TenantsTable,
			Columns: account.TenantsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &TenantAccountAssignmentCreate{config: ac.config, mutation: newTenantAccountAssignmentMutation(ac.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.ReceivedMailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   account.ReceivedMailsTable,
			Columns: []string{account.ReceivedMailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(mail.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.TemporaryFilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   account.TemporaryFilesTable,
			Columns: []string{account.TemporaryFilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(temporaryfile.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.TenantAssignmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   account.TenantAssignmentTable,
			Columns: []string{account.TenantAssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantaccountassignment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccountCreateBulk is the builder for creating many Account entities in bulk.
type AccountCreateBulk struct {
	config
	err      error
	builders []*AccountCreate
}

// Save creates the Account entities in the database.
func (acb *AccountCreateBulk) Save(ctx context.Context) ([]*Account, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Account, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AccountCreateBulk) SaveX(ctx context.Context) []*Account {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AccountCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AccountCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
