// Code generated by ent, DO NOT EDIT.

package entmain

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/simpledms/simpledms/db/entmain/predicate"
	"github.com/simpledms/simpledms/db/entmain/temporaryfile"
)

// TemporaryFileDelete is the builder for deleting a TemporaryFile entity.
type TemporaryFileDelete struct {
	config
	hooks    []Hook
	mutation *TemporaryFileMutation
}

// Where appends a list predicates to the TemporaryFileDelete builder.
func (tfd *TemporaryFileDelete) Where(ps ...predicate.TemporaryFile) *TemporaryFileDelete {
	tfd.mutation.Where(ps...)
	return tfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tfd *TemporaryFileDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tfd.sqlExec, tfd.mutation, tfd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tfd *TemporaryFileDelete) ExecX(ctx context.Context) int {
	n, err := tfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tfd *TemporaryFileDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(temporaryfile.Table, sqlgraph.NewFieldSpec(temporaryfile.FieldID, field.TypeInt64))
	if ps := tfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tfd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tfd.mutation.done = true
	return affected, err
}

// TemporaryFileDeleteOne is the builder for deleting a single TemporaryFile entity.
type TemporaryFileDeleteOne struct {
	tfd *TemporaryFileDelete
}

// Where appends a list predicates to the TemporaryFileDelete builder.
func (tfdo *TemporaryFileDeleteOne) Where(ps ...predicate.TemporaryFile) *TemporaryFileDeleteOne {
	tfdo.tfd.mutation.Where(ps...)
	return tfdo
}

// Exec executes the deletion query.
func (tfdo *TemporaryFileDeleteOne) Exec(ctx context.Context) error {
	n, err := tfdo.tfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{temporaryfile.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tfdo *TemporaryFileDeleteOne) ExecX(ctx context.Context) {
	if err := tfdo.Exec(ctx); err != nil {
		panic(err)
	}
}
