// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AttributesColumns holds the columns for the "attributes" table.
	AttributesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "is_name_giving", Type: field.TypeBool, Default: false},
		{Name: "is_protected", Type: field.TypeBool, Default: false},
		{Name: "is_disabled", Type: field.TypeBool, Default: false},
		{Name: "is_required", Type: field.TypeBool, Default: false},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"Tag", "Field"}},
		{Name: "space_id", Type: field.TypeInt64},
		{Name: "tag_id", Type: field.TypeInt64, Nullable: true},
		{Name: "property_id", Type: field.TypeInt64, Nullable: true},
		{Name: "document_type_id", Type: field.TypeInt64},
	}
	// AttributesTable holds the schema information for the "attributes" table.
	AttributesTable = &schema.Table{
		Name:       "attributes",
		Columns:    AttributesColumns,
		PrimaryKey: []*schema.Column{AttributesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "attributes_spaces_space",
				Columns:    []*schema.Column{AttributesColumns[7]},
				RefColumns: []*schema.Column{SpacesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "attributes_tags_tag",
				Columns:    []*schema.Column{AttributesColumns[8]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "attributes_properties_property",
				Columns:    []*schema.Column{AttributesColumns[9]},
				RefColumns: []*schema.Column{PropertiesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "attributes_document_types_attributes",
				Columns:    []*schema.Column{AttributesColumns[10]},
				RefColumns: []*schema.Column{DocumentTypesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "attribute_space_id",
				Unique:  false,
				Columns: []*schema.Column{AttributesColumns[7]},
			},
			{
				Name:    "attribute_space_id_document_type_id_name",
				Unique:  true,
				Columns: []*schema.Column{AttributesColumns[7], AttributesColumns[10], AttributesColumns[1]},
				Annotation: &entsql.IndexAnnotation{
					Where: "`name` != ''",
				},
			},
			{
				Name:    "attribute_space_id_document_type_id_tag_id",
				Unique:  true,
				Columns: []*schema.Column{AttributesColumns[7], AttributesColumns[10], AttributesColumns[8]},
			},
			{
				Name:    "attribute_space_id_document_type_id_property_id",
				Unique:  true,
				Columns: []*schema.Column{AttributesColumns[7], AttributesColumns[10], AttributesColumns[9]},
			},
		},
	}
	// DocumentTypesColumns holds the columns for the "document_types" table.
	DocumentTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString, Nullable: true},
		{Name: "is_protected", Type: field.TypeBool, Default: false},
		{Name: "is_disabled", Type: field.TypeBool, Default: false},
		{Name: "space_id", Type: field.TypeInt64},
	}
	// DocumentTypesTable holds the schema information for the "document_types" table.
	DocumentTypesTable = &schema.Table{
		Name:       "document_types",
		Columns:    DocumentTypesColumns,
		PrimaryKey: []*schema.Column{DocumentTypesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "document_types_spaces_space",
				Columns:    []*schema.Column{DocumentTypesColumns[5]},
				RefColumns: []*schema.Column{SpacesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "documenttype_space_id",
				Unique:  false,
				Columns: []*schema.Column{DocumentTypesColumns[5]},
			},
		},
	}
	// FilesColumns holds the columns for the "files" table.
	FilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "public_id", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "source", Type: field.TypeEnum, Enums: []string{"UnknownLegacy", "WebInterface", "PWAOSOpen", "URLImport", "WebDAV", "SystemExtraction"}, Default: "UnknownLegacy"},
		{Name: "is_directory", Type: field.TypeBool},
		{Name: "notes", Type: field.TypeString, Nullable: true},
		{Name: "modified_at", Type: field.TypeTime, Nullable: true},
		{Name: "indexed_at", Type: field.TypeTime},
		{Name: "indexing_completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "is_in_inbox", Type: field.TypeBool, Default: false},
		{Name: "is_root_dir", Type: field.TypeBool, Default: false},
		{Name: "ocr_content", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "ocr_success_at", Type: field.TypeTime, Nullable: true},
		{Name: "ocr_retry_count", Type: field.TypeInt, Default: 0},
		{Name: "ocr_last_tried_at", Type: field.TypeTime},
		{Name: "deleted_by", Type: field.TypeInt64, Nullable: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "space_id", Type: field.TypeInt64},
		{Name: "parent_id", Type: field.TypeInt64, Nullable: true},
		{Name: "document_type_id", Type: field.TypeInt64, Nullable: true},
	}
	// FilesTable holds the schema information for the "files" table.
	FilesTable = &schema.Table{
		Name:       "files",
		Columns:    FilesColumns,
		PrimaryKey: []*schema.Column{FilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "files_users_deleter",
				Columns:    []*schema.Column{FilesColumns[18]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "files_users_creator",
				Columns:    []*schema.Column{FilesColumns[19]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "files_users_updater",
				Columns:    []*schema.Column{FilesColumns[20]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "files_spaces_space",
				Columns:    []*schema.Column{FilesColumns[21]},
				RefColumns: []*schema.Column{SpacesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "files_files_parent",
				Columns:    []*schema.Column{FilesColumns[22]},
				RefColumns: []*schema.Column{FilesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "files_document_types_document_type",
				Columns:    []*schema.Column{FilesColumns[23]},
				RefColumns: []*schema.Column{DocumentTypesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "file_space_id",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[21]},
			},
			{
				Name:    "file_space_id_name_parent_id",
				Unique:  true,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[5], FilesColumns[22]},
				Annotation: &entsql.IndexAnnotation{
					Where: "`deleted_at` is null and `is_in_inbox` = false",
				},
			},
			{
				Name:    "file_space_id_is_root_dir",
				Unique:  true,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[13]},
				Annotation: &entsql.IndexAnnotation{
					Where: "`is_root_dir` = true",
				},
			},
			{
				Name:    "file_parent_id",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[22]},
			},
			{
				Name:    "file_is_directory",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[7]},
			},
			{
				Name:    "file_is_in_inbox",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[12]},
			},
			{
				Name:    "file_space_id_parent_id",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[22]},
			},
			{
				Name:    "file_browse_name",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[22], FilesColumns[7], FilesColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						FilesColumns[7].Name: true,
					},
					Where: "`deleted_at` is null and `is_in_inbox` = false",
				},
			},
			{
				Name:    "file_browse_created",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[22], FilesColumns[7], FilesColumns[3], FilesColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						FilesColumns[3].Name: true,

						FilesColumns[7].Name: true,
					},
					Where: "`deleted_at` is null and `is_in_inbox` = false",
				},
			},
			{
				Name:    "file_browse_created_oldest",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[22], FilesColumns[7], FilesColumns[3], FilesColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						FilesColumns[7].Name: true,
					},
					Where: "`deleted_at` is null and `is_in_inbox` = false",
				},
			},
			{
				Name:    "file_inbox_created",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[7], FilesColumns[3]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						FilesColumns[3].Name: true,
					},
					Where: "`deleted_at` is null and `is_in_inbox` = true",
				},
			},
			{
				Name:    "file_inbox_name",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[7], FilesColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					Where: "`deleted_at` is null and `is_in_inbox` = true",
				},
			},
			{
				Name:    "file_browse_name_fast",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[22], FilesColumns[12], FilesColumns[1], FilesColumns[7], FilesColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						FilesColumns[7].Name: true,
					},
				},
			},
			{
				Name:    "file_browse_created_fast",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[22], FilesColumns[12], FilesColumns[1], FilesColumns[7], FilesColumns[3], FilesColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						FilesColumns[3].Name: true,

						FilesColumns[7].Name: true,
					},
				},
			},
			{
				Name:    "file_browse_created_oldest_fast",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[22], FilesColumns[12], FilesColumns[1], FilesColumns[7], FilesColumns[3], FilesColumns[5]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						FilesColumns[7].Name: true,
					},
				},
			},
			{
				Name:    "file_inbox_created_fast",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[12], FilesColumns[7], FilesColumns[1], FilesColumns[3]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						FilesColumns[3].Name: true,
					},
				},
			},
			{
				Name:    "file_inbox_name_fast",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[12], FilesColumns[7], FilesColumns[1], FilesColumns[5]},
			},
			{
				Name:    "file_inbox_source_created_fast",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[12], FilesColumns[1], FilesColumns[7], FilesColumns[6], FilesColumns[3]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						FilesColumns[3].Name: true,
					},
				},
			},
			{
				Name:    "file_inbox_source_created_oldest_fast",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[12], FilesColumns[1], FilesColumns[7], FilesColumns[6], FilesColumns[3]},
			},
			{
				Name:    "file_inbox_source_name_fast",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[21], FilesColumns[12], FilesColumns[1], FilesColumns[7], FilesColumns[6], FilesColumns[5]},
			},
			{
				Name:    "file_ocr_pending",
				Unique:  false,
				Columns: []*schema.Column{FilesColumns[17], FilesColumns[0]},
				Annotation: &entsql.IndexAnnotation{
					Where: "`ocr_success_at` is null and `ocr_retry_count` < 3 and `is_directory` = false",
				},
			},
		},
	}
	// FilePropertyAssignmentsColumns holds the columns for the "file_property_assignments" table.
	FilePropertyAssignmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "text_value", Type: field.TypeString, Nullable: true},
		{Name: "number_value", Type: field.TypeInt, Nullable: true},
		{Name: "date_value", Type: field.TypeTime, Nullable: true},
		{Name: "bool_value", Type: field.TypeBool, Nullable: true},
		{Name: "space_id", Type: field.TypeInt64},
		{Name: "file_id", Type: field.TypeInt64},
		{Name: "property_id", Type: field.TypeInt64},
	}
	// FilePropertyAssignmentsTable holds the schema information for the "file_property_assignments" table.
	FilePropertyAssignmentsTable = &schema.Table{
		Name:       "file_property_assignments",
		Columns:    FilePropertyAssignmentsColumns,
		PrimaryKey: []*schema.Column{FilePropertyAssignmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "file_property_assignments_spaces_space",
				Columns:    []*schema.Column{FilePropertyAssignmentsColumns[5]},
				RefColumns: []*schema.Column{SpacesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "file_property_assignments_files_file",
				Columns:    []*schema.Column{FilePropertyAssignmentsColumns[6]},
				RefColumns: []*schema.Column{FilesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "file_property_assignments_properties_property",
				Columns:    []*schema.Column{FilePropertyAssignmentsColumns[7]},
				RefColumns: []*schema.Column{PropertiesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "filepropertyassignment_space_id",
				Unique:  false,
				Columns: []*schema.Column{FilePropertyAssignmentsColumns[5]},
			},
			{
				Name:    "filepropertyassignment_file_id_property_id",
				Unique:  true,
				Columns: []*schema.Column{FilePropertyAssignmentsColumns[6], FilePropertyAssignmentsColumns[7]},
			},
		},
	}
	// FileVersionsColumns holds the columns for the "file_versions" table.
	FileVersionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "version_number", Type: field.TypeInt, Default: 1},
		{Name: "note", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "file_id", Type: field.TypeInt64},
		{Name: "stored_file_id", Type: field.TypeInt64},
	}
	// FileVersionsTable holds the schema information for the "file_versions" table.
	FileVersionsTable = &schema.Table{
		Name:       "file_versions",
		Columns:    FileVersionsColumns,
		PrimaryKey: []*schema.Column{FileVersionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "file_versions_files_file",
				Columns:    []*schema.Column{FileVersionsColumns[3]},
				RefColumns: []*schema.Column{FilesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "file_versions_stored_files_stored_file",
				Columns:    []*schema.Column{FileVersionsColumns[4]},
				RefColumns: []*schema.Column{StoredFilesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "fileversion_file_id_stored_file_id",
				Unique:  true,
				Columns: []*schema.Column{FileVersionsColumns[3], FileVersionsColumns[4]},
			},
			{
				Name:    "fileversion_file_id_version_number",
				Unique:  true,
				Columns: []*schema.Column{FileVersionsColumns[3], FileVersionsColumns[1]},
			},
			{
				Name:    "fileversion_stored_file_id",
				Unique:  false,
				Columns: []*schema.Column{FileVersionsColumns[4]},
			},
		},
	}
	// PreviewConversionsColumns holds the columns for the "preview_conversions" table.
	PreviewConversionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"Pending", "Processing", "Ready", "Failed"}},
		{Name: "retry_count", Type: field.TypeInt, Default: 0},
		{Name: "last_attempted_at", Type: field.TypeTime, Nullable: true},
		{Name: "next_attempt_at", Type: field.TypeTime, Nullable: true},
		{Name: "processing_started_at", Type: field.TypeTime, Nullable: true},
		{Name: "failure_category", Type: field.TypeString, Nullable: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "source_stored_file_id", Type: field.TypeInt64},
		{Name: "preview_stored_file_id", Type: field.TypeInt64, Nullable: true},
	}
	// PreviewConversionsTable holds the schema information for the "preview_conversions" table.
	PreviewConversionsTable = &schema.Table{
		Name:       "preview_conversions",
		Columns:    PreviewConversionsColumns,
		PrimaryKey: []*schema.Column{PreviewConversionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "preview_conversions_users_creator",
				Columns:    []*schema.Column{PreviewConversionsColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "preview_conversions_users_updater",
				Columns:    []*schema.Column{PreviewConversionsColumns[10]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "preview_conversions_stored_files_source",
				Columns:    []*schema.Column{PreviewConversionsColumns[11]},
				RefColumns: []*schema.Column{StoredFilesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "preview_conversions_stored_files_preview",
				Columns:    []*schema.Column{PreviewConversionsColumns[12]},
				RefColumns: []*schema.Column{StoredFilesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "previewconversion_source_stored_file_id",
				Unique:  true,
				Columns: []*schema.Column{PreviewConversionsColumns[11]},
			},
			{
				Name:    "previewconversion_status_next_attempt_at_id",
				Unique:  false,
				Columns: []*schema.Column{PreviewConversionsColumns[3], PreviewConversionsColumns[6], PreviewConversionsColumns[0]},
			},
		},
	}
	// PropertiesColumns holds the columns for the "properties" table.
	PropertiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"Unknown", "Text", "Number", "Money", "Date", "Checkbox"}},
		{Name: "unit", Type: field.TypeString, Default: ""},
		{Name: "space_id", Type: field.TypeInt64},
	}
	// PropertiesTable holds the schema information for the "properties" table.
	PropertiesTable = &schema.Table{
		Name:       "properties",
		Columns:    PropertiesColumns,
		PrimaryKey: []*schema.Column{PropertiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "properties_spaces_space",
				Columns:    []*schema.Column{PropertiesColumns[4]},
				RefColumns: []*schema.Column{SpacesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "property_space_id",
				Unique:  false,
				Columns: []*schema.Column{PropertiesColumns[4]},
			},
			{
				Name:    "property_space_id_name",
				Unique:  true,
				Columns: []*schema.Column{PropertiesColumns[4], PropertiesColumns[1]},
			},
		},
	}
	// SpacesColumns holds the columns for the "spaces" table.
	SpacesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "public_id", Type: field.TypeString, Unique: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "icon", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "is_folder_mode", Type: field.TypeBool, Default: false},
		{Name: "deleted_by", Type: field.TypeInt64, Nullable: true},
	}
	// SpacesTable holds the schema information for the "spaces" table.
	SpacesTable = &schema.Table{
		Name:       "spaces",
		Columns:    SpacesColumns,
		PrimaryKey: []*schema.Column{SpacesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "spaces_users_deleter",
				Columns:    []*schema.Column{SpacesColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "space_name",
				Unique:  true,
				Columns: []*schema.Column{SpacesColumns[3]},
				Annotation: &entsql.IndexAnnotation{
					Where: "`deleted_at` is null",
				},
			},
		},
	}
	// SpaceUserAssignmentsColumns holds the columns for the "space_user_assignments" table.
	SpaceUserAssignmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"User", "Owner"}},
		{Name: "is_default", Type: field.TypeBool, Default: false},
		{Name: "space_id", Type: field.TypeInt64},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "user_id", Type: field.TypeInt64},
	}
	// SpaceUserAssignmentsTable holds the schema information for the "space_user_assignments" table.
	SpaceUserAssignmentsTable = &schema.Table{
		Name:       "space_user_assignments",
		Columns:    SpaceUserAssignmentsColumns,
		PrimaryKey: []*schema.Column{SpaceUserAssignmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "space_user_assignments_spaces_space",
				Columns:    []*schema.Column{SpaceUserAssignmentsColumns[5]},
				RefColumns: []*schema.Column{SpacesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "space_user_assignments_users_creator",
				Columns:    []*schema.Column{SpaceUserAssignmentsColumns[6]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "space_user_assignments_users_updater",
				Columns:    []*schema.Column{SpaceUserAssignmentsColumns[7]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "space_user_assignments_users_user",
				Columns:    []*schema.Column{SpaceUserAssignmentsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "spaceuserassignment_space_id",
				Unique:  false,
				Columns: []*schema.Column{SpaceUserAssignmentsColumns[5]},
			},
			{
				Name:    "spaceuserassignment_space_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{SpaceUserAssignmentsColumns[5], SpaceUserAssignmentsColumns[8]},
			},
			{
				Name:    "spaceuserassignment_user_id_is_default",
				Unique:  true,
				Columns: []*schema.Column{SpaceUserAssignmentsColumns[8], SpaceUserAssignmentsColumns[4]},
				Annotation: &entsql.IndexAnnotation{
					Where: "`is_default` = true",
				},
			},
		},
	}
	// StoredFilesColumns holds the columns for the "stored_files" table.
	StoredFilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "upload_started_at", Type: field.TypeTime, Nullable: true},
		{Name: "upload_last_progress_at", Type: field.TypeTime, Nullable: true},
		{Name: "upload_failed_at", Type: field.TypeTime, Nullable: true},
		{Name: "upload_succeeded_at", Type: field.TypeTime, Nullable: true},
		{Name: "filename", Type: field.TypeString},
		{Name: "size", Type: field.TypeInt64, Nullable: true},
		{Name: "size_in_storage", Type: field.TypeInt64},
		{Name: "sha256", Type: field.TypeString, Nullable: true},
		{Name: "content_sha256", Type: field.TypeString, Nullable: true},
		{Name: "storage_crc32c", Type: field.TypeString, Nullable: true},
		{Name: "mime_type", Type: field.TypeString, Nullable: true},
		{Name: "storage_type", Type: field.TypeEnum, Enums: []string{"Unknown", "Local", "S3"}},
		{Name: "bucket_name", Type: field.TypeString, Nullable: true},
		{Name: "storage_path", Type: field.TypeString},
		{Name: "storage_filename", Type: field.TypeString},
		{Name: "temporary_storage_path", Type: field.TypeString},
		{Name: "temporary_storage_filename", Type: field.TypeString},
		{Name: "source_temporary_file_public_id", Type: field.TypeString, Nullable: true},
		{Name: "source_conversion_claim_token", Type: field.TypeString, Nullable: true},
		{Name: "copied_to_final_destination_at", Type: field.TypeTime, Nullable: true},
		{Name: "deleted_temporary_file_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
	}
	// StoredFilesTable holds the schema information for the "stored_files" table.
	StoredFilesTable = &schema.Table{
		Name:       "stored_files",
		Columns:    StoredFilesColumns,
		PrimaryKey: []*schema.Column{StoredFilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "stored_files_users_creator",
				Columns:    []*schema.Column{StoredFilesColumns[24]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "stored_files_users_updater",
				Columns:    []*schema.Column{StoredFilesColumns[25]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "storedfile_content_sha256",
				Unique:  false,
				Columns: []*schema.Column{StoredFilesColumns[11]},
			},
			{
				Name:    "storedfile_content_hash_pending",
				Unique:  false,
				Columns: []*schema.Column{StoredFilesColumns[0]},
				Annotation: &entsql.IndexAnnotation{
					Where: "`content_sha256` is null and `upload_succeeded_at` is not null and `copied_to_final_destination_at` is not null",
				},
			},
			{
				Name:    "storedfile_copy_pending",
				Unique:  false,
				Columns: []*schema.Column{StoredFilesColumns[22], StoredFilesColumns[0]},
				Annotation: &entsql.IndexAnnotation{
					Where: "`copied_to_final_destination_at` is null and `deleted_temporary_file_at` is null",
				},
			},
			{
				Name:    "storedfile_temp_delete_pending",
				Unique:  false,
				Columns: []*schema.Column{StoredFilesColumns[22], StoredFilesColumns[0]},
				Annotation: &entsql.IndexAnnotation{
					Where: "`copied_to_final_destination_at` is not null and `deleted_temporary_file_at` is null",
				},
			},
			{
				Name:    "storedfile_source_temporary_file",
				Unique:  true,
				Columns: []*schema.Column{StoredFilesColumns[20]},
				Annotation: &entsql.IndexAnnotation{
					Where: "`source_temporary_file_public_id` is not null",
				},
			},
		},
	}
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "color", Type: field.TypeString, Nullable: true},
		{Name: "icon", Type: field.TypeString, Nullable: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"Simple", "Super", "Group"}},
		{Name: "space_id", Type: field.TypeInt64},
		{Name: "group_id", Type: field.TypeInt64, Nullable: true},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tags_spaces_space",
				Columns:    []*schema.Column{TagsColumns[5]},
				RefColumns: []*schema.Column{SpacesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "tags_tags_group",
				Columns:    []*schema.Column{TagsColumns[6]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tag_space_id",
				Unique:  false,
				Columns: []*schema.Column{TagsColumns[5]},
			},
			{
				Name:    "tag_space_id_name",
				Unique:  true,
				Columns: []*schema.Column{TagsColumns[5], TagsColumns[1]},
				Annotation: &entsql.IndexAnnotation{
					Where: "`group_id` is null",
				},
			},
			{
				Name:    "tag_space_id_name_group_id",
				Unique:  true,
				Columns: []*schema.Column{TagsColumns[5], TagsColumns[1], TagsColumns[6]},
			},
		},
	}
	// TagAssignmentsColumns holds the columns for the "tag_assignments" table.
	TagAssignmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "space_id", Type: field.TypeInt64},
		{Name: "tag_id", Type: field.TypeInt64},
		{Name: "file_id", Type: field.TypeInt64},
	}
	// TagAssignmentsTable holds the schema information for the "tag_assignments" table.
	TagAssignmentsTable = &schema.Table{
		Name:       "tag_assignments",
		Columns:    TagAssignmentsColumns,
		PrimaryKey: []*schema.Column{TagAssignmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tag_assignments_spaces_space",
				Columns:    []*schema.Column{TagAssignmentsColumns[1]},
				RefColumns: []*schema.Column{SpacesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "tag_assignments_tags_tag",
				Columns:    []*schema.Column{TagAssignmentsColumns[2]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "tag_assignments_files_file",
				Columns:    []*schema.Column{TagAssignmentsColumns[3]},
				RefColumns: []*schema.Column{FilesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "tagassignment_space_id",
				Unique:  false,
				Columns: []*schema.Column{TagAssignmentsColumns[1]},
			},
			{
				Name:    "tagassignment_tag_id",
				Unique:  false,
				Columns: []*schema.Column{TagAssignmentsColumns[2]},
			},
			{
				Name:    "tagassignment_file_id_tag_id",
				Unique:  true,
				Columns: []*schema.Column{TagAssignmentsColumns[3], TagAssignmentsColumns[2]},
			},
		},
	}
	// TenantDataMigrationsColumns holds the columns for the "tenant_data_migrations" table.
	TenantDataMigrationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString},
		{Name: "cursor", Type: field.TypeInt64, Default: 0},
		{Name: "first_started_at", Type: field.TypeTime},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_attempted_at", Type: field.TypeTime, Nullable: true},
		{Name: "failed_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_error", Type: field.TypeString, Nullable: true},
		{Name: "retry_count", Type: field.TypeInt, Default: 0},
		{Name: "lease_token", Type: field.TypeString, Nullable: true},
		{Name: "lease_expires_at", Type: field.TypeTime, Nullable: true},
	}
	// TenantDataMigrationsTable holds the schema information for the "tenant_data_migrations" table.
	TenantDataMigrationsTable = &schema.Table{
		Name:       "tenant_data_migrations",
		Columns:    TenantDataMigrationsColumns,
		PrimaryKey: []*schema.Column{TenantDataMigrationsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "tenantdatamigration_key",
				Unique:  true,
				Columns: []*schema.Column{TenantDataMigrationsColumns[1]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "deleted_by", Type: field.TypeInt64, Nullable: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "public_id", Type: field.TypeString, Unique: true},
		{Name: "account_id", Type: field.TypeInt64, Unique: true},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"User", "Owner"}},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "first_name", Type: field.TypeString},
		{Name: "last_name", Type: field.TypeString, Nullable: true},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// WebDavResourcesColumns holds the columns for the "web_dav_resources" table.
	WebDavResourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "credential_public_id", Type: field.TypeString},
		{Name: "dav_path", Type: field.TypeString},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"Uploading", "Active", "CleanupPending"}, Default: "Uploading"},
		{Name: "last_progress_at", Type: field.TypeTime},
		{Name: "finalized_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_by", Type: field.TypeInt64, Nullable: true},
		{Name: "updated_by", Type: field.TypeInt64, Nullable: true},
		{Name: "space_id", Type: field.TypeInt64},
		{Name: "file_id", Type: field.TypeInt64, Nullable: true},
		{Name: "stored_file_id", Type: field.TypeInt64, Nullable: true},
	}
	// WebDavResourcesTable holds the schema information for the "web_dav_resources" table.
	WebDavResourcesTable = &schema.Table{
		Name:       "web_dav_resources",
		Columns:    WebDavResourcesColumns,
		PrimaryKey: []*schema.Column{WebDavResourcesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "web_dav_resources_users_creator",
				Columns:    []*schema.Column{WebDavResourcesColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "web_dav_resources_users_updater",
				Columns:    []*schema.Column{WebDavResourcesColumns[9]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "web_dav_resources_spaces_space",
				Columns:    []*schema.Column{WebDavResourcesColumns[10]},
				RefColumns: []*schema.Column{SpacesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "web_dav_resources_files_file",
				Columns:    []*schema.Column{WebDavResourcesColumns[11]},
				RefColumns: []*schema.Column{FilesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "web_dav_resources_stored_files_stored_file",
				Columns:    []*schema.Column{WebDavResourcesColumns[12]},
				RefColumns: []*schema.Column{StoredFilesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "webdavresource_space_id",
				Unique:  false,
				Columns: []*schema.Column{WebDavResourcesColumns[10]},
			},
			{
				Name:    "webdavresource_active_path",
				Unique:  true,
				Columns: []*schema.Column{WebDavResourcesColumns[3], WebDavResourcesColumns[10], WebDavResourcesColumns[4]},
				Annotation: &entsql.IndexAnnotation{
					Where: "`state` in ('Uploading', 'Active')",
				},
			},
			{
				Name:    "webdavresource_state_last_progress_at_id",
				Unique:  false,
				Columns: []*schema.Column{WebDavResourcesColumns[5], WebDavResourcesColumns[6], WebDavResourcesColumns[0]},
			},
			{
				Name:    "webdavresource_file_id",
				Unique:  false,
				Columns: []*schema.Column{WebDavResourcesColumns[11]},
			},
			{
				Name:    "webdavresource_stored_file_id",
				Unique:  false,
				Columns: []*schema.Column{WebDavResourcesColumns[12]},
			},
		},
	}
	// TagSubTagsColumns holds the columns for the "tag_sub_tags" table.
	TagSubTagsColumns = []*schema.Column{
		{Name: "tag_id", Type: field.TypeInt64},
		{Name: "super_tag_id", Type: field.TypeInt64},
	}
	// TagSubTagsTable holds the schema information for the "tag_sub_tags" table.
	TagSubTagsTable = &schema.Table{
		Name:       "tag_sub_tags",
		Columns:    TagSubTagsColumns,
		PrimaryKey: []*schema.Column{TagSubTagsColumns[0], TagSubTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "tag_sub_tags_tag_id",
				Columns:    []*schema.Column{TagSubTagsColumns[0]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "tag_sub_tags_super_tag_id",
				Columns:    []*schema.Column{TagSubTagsColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AttributesTable,
		DocumentTypesTable,
		FilesTable,
		FilePropertyAssignmentsTable,
		FileVersionsTable,
		PreviewConversionsTable,
		PropertiesTable,
		SpacesTable,
		SpaceUserAssignmentsTable,
		StoredFilesTable,
		TagsTable,
		TagAssignmentsTable,
		TenantDataMigrationsTable,
		UsersTable,
		WebDavResourcesTable,
		TagSubTagsTable,
	}
)

func init() {
	AttributesTable.ForeignKeys[0].RefTable = SpacesTable
	AttributesTable.ForeignKeys[1].RefTable = TagsTable
	AttributesTable.ForeignKeys[2].RefTable = PropertiesTable
	AttributesTable.ForeignKeys[3].RefTable = DocumentTypesTable
	DocumentTypesTable.ForeignKeys[0].RefTable = SpacesTable
	FilesTable.ForeignKeys[0].RefTable = UsersTable
	FilesTable.ForeignKeys[1].RefTable = UsersTable
	FilesTable.ForeignKeys[2].RefTable = UsersTable
	FilesTable.ForeignKeys[3].RefTable = SpacesTable
	FilesTable.ForeignKeys[4].RefTable = FilesTable
	FilesTable.ForeignKeys[5].RefTable = DocumentTypesTable
	FilePropertyAssignmentsTable.ForeignKeys[0].RefTable = SpacesTable
	FilePropertyAssignmentsTable.ForeignKeys[1].RefTable = FilesTable
	FilePropertyAssignmentsTable.ForeignKeys[2].RefTable = PropertiesTable
	FileVersionsTable.ForeignKeys[0].RefTable = FilesTable
	FileVersionsTable.ForeignKeys[1].RefTable = StoredFilesTable
	PreviewConversionsTable.ForeignKeys[0].RefTable = UsersTable
	PreviewConversionsTable.ForeignKeys[1].RefTable = UsersTable
	PreviewConversionsTable.ForeignKeys[2].RefTable = StoredFilesTable
	PreviewConversionsTable.ForeignKeys[3].RefTable = StoredFilesTable
	PropertiesTable.ForeignKeys[0].RefTable = SpacesTable
	SpacesTable.ForeignKeys[0].RefTable = UsersTable
	SpaceUserAssignmentsTable.ForeignKeys[0].RefTable = SpacesTable
	SpaceUserAssignmentsTable.ForeignKeys[1].RefTable = UsersTable
	SpaceUserAssignmentsTable.ForeignKeys[2].RefTable = UsersTable
	SpaceUserAssignmentsTable.ForeignKeys[3].RefTable = UsersTable
	StoredFilesTable.ForeignKeys[0].RefTable = UsersTable
	StoredFilesTable.ForeignKeys[1].RefTable = UsersTable
	TagsTable.ForeignKeys[0].RefTable = SpacesTable
	TagsTable.ForeignKeys[1].RefTable = TagsTable
	TagAssignmentsTable.ForeignKeys[0].RefTable = SpacesTable
	TagAssignmentsTable.ForeignKeys[1].RefTable = TagsTable
	TagAssignmentsTable.ForeignKeys[2].RefTable = FilesTable
	WebDavResourcesTable.ForeignKeys[0].RefTable = UsersTable
	WebDavResourcesTable.ForeignKeys[1].RefTable = UsersTable
	WebDavResourcesTable.ForeignKeys[2].RefTable = SpacesTable
	WebDavResourcesTable.ForeignKeys[3].RefTable = FilesTable
	WebDavResourcesTable.ForeignKeys[4].RefTable = StoredFilesTable
	TagSubTagsTable.ForeignKeys[0].RefTable = TagsTable
	TagSubTagsTable.ForeignKeys[1].RefTable = TagsTable
}
