// Code generated by ent, DO NOT EDIT.

package mcpcredential

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/simpledms/simpledms/db/entmain/predicate"
	"github.com/simpledms/simpledms/db/entx"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldLTE(FieldID, id))
}

// PublicID applies equality check predicate on the "public_id" field. It's identical to PublicIDEQ.
func PublicID(v entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldPublicID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldAccountID, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldTenantID, v))
}

// SpacePublicID applies equality check predicate on the "space_public_id" field. It's identical to SpacePublicIDEQ.
func SpacePublicID(v entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldSpacePublicID, v))
}

// IsReadOnly applies equality check predicate on the "is_read_only" field. It's identical to IsReadOnlyEQ.
func IsReadOnly(v bool) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldIsReadOnly, v))
}

// SecretHash applies equality check predicate on the "secret_hash" field. It's identical to SecretHashEQ.
func SecretHash(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldSecretHash, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldRevokedAt, v))
}

// PublicIDEQ applies the EQ predicate on the "public_id" field.
func PublicIDEQ(v entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldPublicID, v))
}

// PublicIDNEQ applies the NEQ predicate on the "public_id" field.
func PublicIDNEQ(v entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNEQ(FieldPublicID, v))
}

// PublicIDIn applies the In predicate on the "public_id" field.
func PublicIDIn(vs ...entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldIn(FieldPublicID, vs...))
}

// PublicIDNotIn applies the NotIn predicate on the "public_id" field.
func PublicIDNotIn(vs ...entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNotIn(FieldPublicID, vs...))
}

// PublicIDGT applies the GT predicate on the "public_id" field.
func PublicIDGT(v entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldGT(FieldPublicID, v))
}

// PublicIDGTE applies the GTE predicate on the "public_id" field.
func PublicIDGTE(v entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldGTE(FieldPublicID, v))
}

// PublicIDLT applies the LT predicate on the "public_id" field.
func PublicIDLT(v entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldLT(FieldPublicID, v))
}

// PublicIDLTE applies the LTE predicate on the "public_id" field.
func PublicIDLTE(v entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldLTE(FieldPublicID, v))
}

// PublicIDContains applies the Contains predicate on the "public_id" field.
func PublicIDContains(v entx.CIText) predicate.MCPCredential {
	vc := string(v)
	return predicate.MCPCredential(sql.FieldContains(FieldPublicID, vc))
}

// PublicIDHasPrefix applies the HasPrefix predicate on the "public_id" field.
func PublicIDHasPrefix(v entx.CIText) predicate.MCPCredential {
	vc := string(v)
	return predicate.MCPCredential(sql.FieldHasPrefix(FieldPublicID, vc))
}

// PublicIDHasSuffix applies the HasSuffix predicate on the "public_id" field.
func PublicIDHasSuffix(v entx.CIText) predicate.MCPCredential {
	vc := string(v)
	return predicate.MCPCredential(sql.FieldHasSuffix(FieldPublicID, vc))
}

// PublicIDEqualFold applies the EqualFold predicate on the "public_id" field.
func PublicIDEqualFold(v entx.CIText) predicate.MCPCredential {
	vc := string(v)
	return predicate.MCPCredential(sql.FieldEqualFold(FieldPublicID, vc))
}

// PublicIDContainsFold applies the ContainsFold predicate on the "public_id" field.
func PublicIDContainsFold(v entx.CIText) predicate.MCPCredential {
	vc := string(v)
	return predicate.MCPCredential(sql.FieldContainsFold(FieldPublicID, vc))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNotIn(FieldAccountID, vs...))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNotIn(FieldTenantID, vs...))
}

// SpacePublicIDEQ applies the EQ predicate on the "space_public_id" field.
func SpacePublicIDEQ(v entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldSpacePublicID, v))
}

// SpacePublicIDNEQ applies the NEQ predicate on the "space_public_id" field.
func SpacePublicIDNEQ(v entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNEQ(FieldSpacePublicID, v))
}

// SpacePublicIDIn applies the In predicate on the "space_public_id" field.
func SpacePublicIDIn(vs ...entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldIn(FieldSpacePublicID, vs...))
}

// SpacePublicIDNotIn applies the NotIn predicate on the "space_public_id" field.
func SpacePublicIDNotIn(vs ...entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNotIn(FieldSpacePublicID, vs...))
}

// SpacePublicIDGT applies the GT predicate on the "space_public_id" field.
func SpacePublicIDGT(v entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldGT(FieldSpacePublicID, v))
}

// SpacePublicIDGTE applies the GTE predicate on the "space_public_id" field.
func SpacePublicIDGTE(v entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldGTE(FieldSpacePublicID, v))
}

// SpacePublicIDLT applies the LT predicate on the "space_public_id" field.
func SpacePublicIDLT(v entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldLT(FieldSpacePublicID, v))
}

// SpacePublicIDLTE applies the LTE predicate on the "space_public_id" field.
func SpacePublicIDLTE(v entx.CIText) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldLTE(FieldSpacePublicID, v))
}

// SpacePublicIDContains applies the Contains predicate on the "space_public_id" field.
func SpacePublicIDContains(v entx.CIText) predicate.MCPCredential {
	vc := string(v)
	return predicate.MCPCredential(sql.FieldContains(FieldSpacePublicID, vc))
}

// SpacePublicIDHasPrefix applies the HasPrefix predicate on the "space_public_id" field.
func SpacePublicIDHasPrefix(v entx.CIText) predicate.MCPCredential {
	vc := string(v)
	return predicate.MCPCredential(sql.FieldHasPrefix(FieldSpacePublicID, vc))
}

// SpacePublicIDHasSuffix applies the HasSuffix predicate on the "space_public_id" field.
func SpacePublicIDHasSuffix(v entx.CIText) predicate.MCPCredential {
	vc := string(v)
	return predicate.MCPCredential(sql.FieldHasSuffix(FieldSpacePublicID, vc))
}

// SpacePublicIDEqualFold applies the EqualFold predicate on the "space_public_id" field.
func SpacePublicIDEqualFold(v entx.CIText) predicate.MCPCredential {
	vc := string(v)
	return predicate.MCPCredential(sql.FieldEqualFold(FieldSpacePublicID, vc))
}

// SpacePublicIDContainsFold applies the ContainsFold predicate on the "space_public_id" field.
func SpacePublicIDContainsFold(v entx.CIText) predicate.MCPCredential {
	vc := string(v)
	return predicate.MCPCredential(sql.FieldContainsFold(FieldSpacePublicID, vc))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldContainsFold(FieldLabel, v))
}

// IsReadOnlyEQ applies the EQ predicate on the "is_read_only" field.
func IsReadOnlyEQ(v bool) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldIsReadOnly, v))
}

// IsReadOnlyNEQ applies the NEQ predicate on the "is_read_only" field.
func IsReadOnlyNEQ(v bool) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNEQ(FieldIsReadOnly, v))
}

// SecretHashEQ applies the EQ predicate on the "secret_hash" field.
func SecretHashEQ(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldSecretHash, v))
}

// SecretHashNEQ applies the NEQ predicate on the "secret_hash" field.
func SecretHashNEQ(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNEQ(FieldSecretHash, v))
}

// SecretHashIn applies the In predicate on the "secret_hash" field.
func SecretHashIn(vs ...string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldIn(FieldSecretHash, vs...))
}

// SecretHashNotIn applies the NotIn predicate on the "secret_hash" field.
func SecretHashNotIn(vs ...string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNotIn(FieldSecretHash, vs...))
}

// SecretHashGT applies the GT predicate on the "secret_hash" field.
func SecretHashGT(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldGT(FieldSecretHash, v))
}

// SecretHashGTE applies the GTE predicate on the "secret_hash" field.
func SecretHashGTE(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldGTE(FieldSecretHash, v))
}

// SecretHashLT applies the LT predicate on the "secret_hash" field.
func SecretHashLT(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldLT(FieldSecretHash, v))
}

// SecretHashLTE applies the LTE predicate on the "secret_hash" field.
func SecretHashLTE(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldLTE(FieldSecretHash, v))
}

// SecretHashContains applies the Contains predicate on the "secret_hash" field.
func SecretHashContains(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldContains(FieldSecretHash, v))
}

// SecretHashHasPrefix applies the HasPrefix predicate on the "secret_hash" field.
func SecretHashHasPrefix(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldHasPrefix(FieldSecretHash, v))
}

// SecretHashHasSuffix applies the HasSuffix predicate on the "secret_hash" field.
func SecretHashHasSuffix(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldHasSuffix(FieldSecretHash, v))
}

// SecretHashEqualFold applies the EqualFold predicate on the "secret_hash" field.
func SecretHashEqualFold(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEqualFold(FieldSecretHash, v))
}

// SecretHashContainsFold applies the ContainsFold predicate on the "secret_hash" field.
func SecretHashContainsFold(v string) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldContainsFold(FieldSecretHash, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldLTE(FieldCreatedAt, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.MCPCredential {
	return predicate.MCPCredential(sql.FieldNotNull(FieldRevokedAt))
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.MCPCredential {
	return predicate.MCPCredential(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.MCPCredential {
	return predicate.MCPCredential(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTenant applies the HasEdge predicate on the "tenant" edge.
func HasTenant() predicate.MCPCredential {
	return predicate.MCPCredential(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TenantTable, TenantColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTenantWith applies the HasEdge predicate on the "tenant" edge with a given conditions (other predicates).
func HasTenantWith(preds ...predicate.Tenant) predicate.MCPCredential {
	return predicate.MCPCredential(func(s *sql.Selector) {
		step := newTenantStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MCPCredential) predicate.MCPCredential {
	return predicate.MCPCredential(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MCPCredential) predicate.MCPCredential {
	return predicate.MCPCredential(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MCPCredential) predicate.MCPCredential {
	return predicate.MCPCredential(sql.NotPredicates(p))
}
