// Code generated by ent, DO NOT EDIT.

package enttenant

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/simpledms/simpledms/app/simpledms/enttenant/documenttype"
	"github.com/simpledms/simpledms/app/simpledms/enttenant/space"
)

// DocumentType is the model entity for the DocumentType schema.
type DocumentType struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// SpaceID holds the value of the "space_id" field.
	SpaceID int64 `json:"space_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Icon holds the value of the "icon" field.
	Icon string `json:"icon,omitempty"`
	// IsProtected holds the value of the "is_protected" field.
	IsProtected bool `json:"is_protected,omitempty"`
	// IsDisabled holds the value of the "is_disabled" field.
	IsDisabled bool `json:"is_disabled,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DocumentTypeQuery when eager-loading is set.
	Edges        DocumentTypeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DocumentTypeEdges holds the relations/edges for other nodes in the graph.
type DocumentTypeEdges struct {
	// Space holds the value of the space edge.
	Space *Space `json:"space,omitempty"`
	// Attributes holds the value of the attributes edge.
	Attributes []*Attribute `json:"attributes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SpaceOrErr returns the Space value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DocumentTypeEdges) SpaceOrErr() (*Space, error) {
	if e.Space != nil {
		return e.Space, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: space.Label}
	}
	return nil, &NotLoadedError{edge: "space"}
}

// AttributesOrErr returns the Attributes value or an error if the edge
// was not loaded in eager-loading.
func (e DocumentTypeEdges) AttributesOrErr() ([]*Attribute, error) {
	if e.loadedTypes[1] {
		return e.Attributes, nil
	}
	return nil, &NotLoadedError{edge: "attributes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DocumentType) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case documenttype.FieldIsProtected, documenttype.FieldIsDisabled:
			values[i] = new(sql.NullBool)
		case documenttype.FieldID, documenttype.FieldSpaceID:
			values[i] = new(sql.NullInt64)
		case documenttype.FieldName, documenttype.FieldIcon:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DocumentType fields.
func (dt *DocumentType) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case documenttype.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			dt.ID = int64(value.Int64)
		case documenttype.FieldSpaceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field space_id", values[i])
			} else if value.Valid {
				dt.SpaceID = value.Int64
			}
		case documenttype.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				dt.Name = value.String
			}
		case documenttype.FieldIcon:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field icon", values[i])
			} else if value.Valid {
				dt.Icon = value.String
			}
		case documenttype.FieldIsProtected:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_protected", values[i])
			} else if value.Valid {
				dt.IsProtected = value.Bool
			}
		case documenttype.FieldIsDisabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_disabled", values[i])
			} else if value.Valid {
				dt.IsDisabled = value.Bool
			}
		default:
			dt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DocumentType.
// This includes values selected through modifiers, order, etc.
func (dt *DocumentType) Value(name string) (ent.Value, error) {
	return dt.selectValues.Get(name)
}

// QuerySpace queries the "space" edge of the DocumentType entity.
func (dt *DocumentType) QuerySpace() *SpaceQuery {
	return NewDocumentTypeClient(dt.config).QuerySpace(dt)
}

// QueryAttributes queries the "attributes" edge of the DocumentType entity.
func (dt *DocumentType) QueryAttributes() *AttributeQuery {
	return NewDocumentTypeClient(dt.config).QueryAttributes(dt)
}

// Update returns a builder for updating this DocumentType.
// Note that you need to call DocumentType.Unwrap() before calling this method if this DocumentType
// was returned from a transaction, and the transaction was committed or rolled back.
func (dt *DocumentType) Update() *DocumentTypeUpdateOne {
	return NewDocumentTypeClient(dt.config).UpdateOne(dt)
}

// Unwrap unwraps the DocumentType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (dt *DocumentType) Unwrap() *DocumentType {
	_tx, ok := dt.config.driver.(*txDriver)
	if !ok {
		panic("enttenant: DocumentType is not a transactional entity")
	}
	dt.config.driver = _tx.drv
	return dt
}

// String implements the fmt.Stringer.
func (dt *DocumentType) String() string {
	var builder strings.Builder
	builder.WriteString("DocumentType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", dt.ID))
	builder.WriteString("space_id=")
	builder.WriteString(fmt.Sprintf("%v", dt.SpaceID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(dt.Name)
	builder.WriteString(", ")
	builder.WriteString("icon=")
	builder.WriteString(dt.Icon)
	builder.WriteString(", ")
	builder.WriteString("is_protected=")
	builder.WriteString(fmt.Sprintf("%v", dt.IsProtected))
	builder.WriteString(", ")
	builder.WriteString("is_disabled=")
	builder.WriteString(fmt.Sprintf("%v", dt.IsDisabled))
	builder.WriteByte(')')
	return builder.String()
}

// DocumentTypes is a parsable slice of DocumentType.
type DocumentTypes []*DocumentType
