// Code generated by ent, DO NOT EDIT.

package filesearch

import (
	"entgo.io/ent/dialect/sql"
	"github.com/simpledms/simpledms/db/enttenant/predicate"
)

// SpaceID applies equality check predicate on the "space_id" field. It's identical to SpaceIDEQ.
func SpaceID(v int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldEQ(FieldSpaceID, v))
}

// FileSearches applies equality check predicate on the "file_searches" field. It's identical to FileSearchesEQ.
func FileSearches(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldEQ(FieldFileSearches, v))
}

// Rank applies equality check predicate on the "rank" field. It's identical to RankEQ.
func Rank(v float64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldEQ(FieldRank, v))
}

// Rowid applies equality check predicate on the "rowid" field. It's identical to RowidEQ.
func Rowid(v int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldEQ(FieldRowid, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldEQ(FieldName, v))
}

// OcrContent applies equality check predicate on the "ocr_content" field. It's identical to OcrContentEQ.
func OcrContent(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldEQ(FieldOcrContent, v))
}

// SpaceIDEQ applies the EQ predicate on the "space_id" field.
func SpaceIDEQ(v int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldEQ(FieldSpaceID, v))
}

// SpaceIDNEQ applies the NEQ predicate on the "space_id" field.
func SpaceIDNEQ(v int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldNEQ(FieldSpaceID, v))
}

// SpaceIDIn applies the In predicate on the "space_id" field.
func SpaceIDIn(vs ...int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldIn(FieldSpaceID, vs...))
}

// SpaceIDNotIn applies the NotIn predicate on the "space_id" field.
func SpaceIDNotIn(vs ...int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldNotIn(FieldSpaceID, vs...))
}

// SpaceIDGT applies the GT predicate on the "space_id" field.
func SpaceIDGT(v int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldGT(FieldSpaceID, v))
}

// SpaceIDGTE applies the GTE predicate on the "space_id" field.
func SpaceIDGTE(v int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldGTE(FieldSpaceID, v))
}

// SpaceIDLT applies the LT predicate on the "space_id" field.
func SpaceIDLT(v int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldLT(FieldSpaceID, v))
}

// SpaceIDLTE applies the LTE predicate on the "space_id" field.
func SpaceIDLTE(v int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldLTE(FieldSpaceID, v))
}

// FileSearchesEQ applies the EQ predicate on the "file_searches" field.
func FileSearchesEQ(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldEQ(FieldFileSearches, v))
}

// FileSearchesNEQ applies the NEQ predicate on the "file_searches" field.
func FileSearchesNEQ(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldNEQ(FieldFileSearches, v))
}

// FileSearchesIn applies the In predicate on the "file_searches" field.
func FileSearchesIn(vs ...string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldIn(FieldFileSearches, vs...))
}

// FileSearchesNotIn applies the NotIn predicate on the "file_searches" field.
func FileSearchesNotIn(vs ...string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldNotIn(FieldFileSearches, vs...))
}

// FileSearchesGT applies the GT predicate on the "file_searches" field.
func FileSearchesGT(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldGT(FieldFileSearches, v))
}

// FileSearchesGTE applies the GTE predicate on the "file_searches" field.
func FileSearchesGTE(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldGTE(FieldFileSearches, v))
}

// FileSearchesLT applies the LT predicate on the "file_searches" field.
func FileSearchesLT(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldLT(FieldFileSearches, v))
}

// FileSearchesLTE applies the LTE predicate on the "file_searches" field.
func FileSearchesLTE(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldLTE(FieldFileSearches, v))
}

// FileSearchesContains applies the Contains predicate on the "file_searches" field.
func FileSearchesContains(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldContains(FieldFileSearches, v))
}

// FileSearchesHasPrefix applies the HasPrefix predicate on the "file_searches" field.
func FileSearchesHasPrefix(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldHasPrefix(FieldFileSearches, v))
}

// FileSearchesHasSuffix applies the HasSuffix predicate on the "file_searches" field.
func FileSearchesHasSuffix(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldHasSuffix(FieldFileSearches, v))
}

// FileSearchesEqualFold applies the EqualFold predicate on the "file_searches" field.
func FileSearchesEqualFold(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldEqualFold(FieldFileSearches, v))
}

// FileSearchesContainsFold applies the ContainsFold predicate on the "file_searches" field.
func FileSearchesContainsFold(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldContainsFold(FieldFileSearches, v))
}

// RankEQ applies the EQ predicate on the "rank" field.
func RankEQ(v float64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldEQ(FieldRank, v))
}

// RankNEQ applies the NEQ predicate on the "rank" field.
func RankNEQ(v float64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldNEQ(FieldRank, v))
}

// RankIn applies the In predicate on the "rank" field.
func RankIn(vs ...float64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldIn(FieldRank, vs...))
}

// RankNotIn applies the NotIn predicate on the "rank" field.
func RankNotIn(vs ...float64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldNotIn(FieldRank, vs...))
}

// RankGT applies the GT predicate on the "rank" field.
func RankGT(v float64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldGT(FieldRank, v))
}

// RankGTE applies the GTE predicate on the "rank" field.
func RankGTE(v float64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldGTE(FieldRank, v))
}

// RankLT applies the LT predicate on the "rank" field.
func RankLT(v float64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldLT(FieldRank, v))
}

// RankLTE applies the LTE predicate on the "rank" field.
func RankLTE(v float64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldLTE(FieldRank, v))
}

// RowidEQ applies the EQ predicate on the "rowid" field.
func RowidEQ(v int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldEQ(FieldRowid, v))
}

// RowidNEQ applies the NEQ predicate on the "rowid" field.
func RowidNEQ(v int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldNEQ(FieldRowid, v))
}

// RowidIn applies the In predicate on the "rowid" field.
func RowidIn(vs ...int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldIn(FieldRowid, vs...))
}

// RowidNotIn applies the NotIn predicate on the "rowid" field.
func RowidNotIn(vs ...int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldNotIn(FieldRowid, vs...))
}

// RowidGT applies the GT predicate on the "rowid" field.
func RowidGT(v int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldGT(FieldRowid, v))
}

// RowidGTE applies the GTE predicate on the "rowid" field.
func RowidGTE(v int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldGTE(FieldRowid, v))
}

// RowidLT applies the LT predicate on the "rowid" field.
func RowidLT(v int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldLT(FieldRowid, v))
}

// RowidLTE applies the LTE predicate on the "rowid" field.
func RowidLTE(v int64) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldLTE(FieldRowid, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldContainsFold(FieldName, v))
}

// OcrContentEQ applies the EQ predicate on the "ocr_content" field.
func OcrContentEQ(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldEQ(FieldOcrContent, v))
}

// OcrContentNEQ applies the NEQ predicate on the "ocr_content" field.
func OcrContentNEQ(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldNEQ(FieldOcrContent, v))
}

// OcrContentIn applies the In predicate on the "ocr_content" field.
func OcrContentIn(vs ...string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldIn(FieldOcrContent, vs...))
}

// OcrContentNotIn applies the NotIn predicate on the "ocr_content" field.
func OcrContentNotIn(vs ...string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldNotIn(FieldOcrContent, vs...))
}

// OcrContentGT applies the GT predicate on the "ocr_content" field.
func OcrContentGT(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldGT(FieldOcrContent, v))
}

// OcrContentGTE applies the GTE predicate on the "ocr_content" field.
func OcrContentGTE(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldGTE(FieldOcrContent, v))
}

// OcrContentLT applies the LT predicate on the "ocr_content" field.
func OcrContentLT(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldLT(FieldOcrContent, v))
}

// OcrContentLTE applies the LTE predicate on the "ocr_content" field.
func OcrContentLTE(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldLTE(FieldOcrContent, v))
}

// OcrContentContains applies the Contains predicate on the "ocr_content" field.
func OcrContentContains(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldContains(FieldOcrContent, v))
}

// OcrContentHasPrefix applies the HasPrefix predicate on the "ocr_content" field.
func OcrContentHasPrefix(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldHasPrefix(FieldOcrContent, v))
}

// OcrContentHasSuffix applies the HasSuffix predicate on the "ocr_content" field.
func OcrContentHasSuffix(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldHasSuffix(FieldOcrContent, v))
}

// OcrContentEqualFold applies the EqualFold predicate on the "ocr_content" field.
func OcrContentEqualFold(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldEqualFold(FieldOcrContent, v))
}

// OcrContentContainsFold applies the ContainsFold predicate on the "ocr_content" field.
func OcrContentContainsFold(v string) predicate.FileSearch {
	return predicate.FileSearch(sql.FieldContainsFold(FieldOcrContent, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FileSearch) predicate.FileSearch {
	return predicate.FileSearch(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FileSearch) predicate.FileSearch {
	return predicate.FileSearch(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FileSearch) predicate.FileSearch {
	return predicate.FileSearch(sql.NotPredicates(p))
}
