// Code generated by ent, DO NOT EDIT.

package enttenant

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/simpledms/simpledms/db/enttenant/file"
	"github.com/simpledms/simpledms/db/enttenant/filepropertyassignment"
	"github.com/simpledms/simpledms/db/enttenant/property"
	"github.com/simpledms/simpledms/db/enttenant/space"
	"github.com/simpledms/simpledms/util/timex"
)

// FilePropertyAssignmentCreate is the builder for creating a FilePropertyAssignment entity.
type FilePropertyAssignmentCreate struct {
	config
	mutation *FilePropertyAssignmentMutation
	hooks    []Hook
}

// SetSpaceID sets the "space_id" field.
func (_c *FilePropertyAssignmentCreate) SetSpaceID(v int64) *FilePropertyAssignmentCreate {
	_c.mutation.SetSpaceID(v)
	return _c
}

// SetFileID sets the "file_id" field.
func (_c *FilePropertyAssignmentCreate) SetFileID(v int64) *FilePropertyAssignmentCreate {
	_c.mutation.SetFileID(v)
	return _c
}

// SetPropertyID sets the "property_id" field.
func (_c *FilePropertyAssignmentCreate) SetPropertyID(v int64) *FilePropertyAssignmentCreate {
	_c.mutation.SetPropertyID(v)
	return _c
}

// SetTextValue sets the "text_value" field.
func (_c *FilePropertyAssignmentCreate) SetTextValue(v string) *FilePropertyAssignmentCreate {
	_c.mutation.SetTextValue(v)
	return _c
}

// SetNillableTextValue sets the "text_value" field if the given value is not nil.
func (_c *FilePropertyAssignmentCreate) SetNillableTextValue(v *string) *FilePropertyAssignmentCreate {
	if v != nil {
		_c.SetTextValue(*v)
	}
	return _c
}

// SetNumberValue sets the "number_value" field.
func (_c *FilePropertyAssignmentCreate) SetNumberValue(v int) *FilePropertyAssignmentCreate {
	_c.mutation.SetNumberValue(v)
	return _c
}

// SetNillableNumberValue sets the "number_value" field if the given value is not nil.
func (_c *FilePropertyAssignmentCreate) SetNillableNumberValue(v *int) *FilePropertyAssignmentCreate {
	if v != nil {
		_c.SetNumberValue(*v)
	}
	return _c
}

// SetDateValue sets the "date_value" field.
func (_c *FilePropertyAssignmentCreate) SetDateValue(v timex.Date) *FilePropertyAssignmentCreate {
	_c.mutation.SetDateValue(v)
	return _c
}

// SetNillableDateValue sets the "date_value" field if the given value is not nil.
func (_c *FilePropertyAssignmentCreate) SetNillableDateValue(v *timex.Date) *FilePropertyAssignmentCreate {
	if v != nil {
		_c.SetDateValue(*v)
	}
	return _c
}

// SetBoolValue sets the "bool_value" field.
func (_c *FilePropertyAssignmentCreate) SetBoolValue(v bool) *FilePropertyAssignmentCreate {
	_c.mutation.SetBoolValue(v)
	return _c
}

// SetNillableBoolValue sets the "bool_value" field if the given value is not nil.
func (_c *FilePropertyAssignmentCreate) SetNillableBoolValue(v *bool) *FilePropertyAssignmentCreate {
	if v != nil {
		_c.SetBoolValue(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FilePropertyAssignmentCreate) SetID(v int64) *FilePropertyAssignmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSpace sets the "space" edge to the Space entity.
func (_c *FilePropertyAssignmentCreate) SetSpace(v *Space) *FilePropertyAssignmentCreate {
	return _c.SetSpaceID(v.ID)
}

// SetFile sets the "file" edge to the File entity.
func (_c *FilePropertyAssignmentCreate) SetFile(v *File) *FilePropertyAssignmentCreate {
	return _c.SetFileID(v.ID)
}

// SetProperty sets the "property" edge to the Property entity.
func (_c *FilePropertyAssignmentCreate) SetProperty(v *Property) *FilePropertyAssignmentCreate {
	return _c.SetPropertyID(v.ID)
}

// Mutation returns the FilePropertyAssignmentMutation object of the builder.
func (_c *FilePropertyAssignmentCreate) Mutation() *FilePropertyAssignmentMutation {
	return _c.mutation
}

// Save creates the FilePropertyAssignment in the database.
func (_c *FilePropertyAssignmentCreate) Save(ctx context.Context) (*FilePropertyAssignment, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FilePropertyAssignmentCreate) SaveX(ctx context.Context) *FilePropertyAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FilePropertyAssignmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FilePropertyAssignmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FilePropertyAssignmentCreate) check() error {
	if _, ok := _c.mutation.SpaceID(); !ok {
		return &ValidationError{Name: "space_id", err: errors.New(`enttenant: missing required field "FilePropertyAssignment.space_id"`)}
	}
	if _, ok := _c.mutation.FileID(); !ok {
		return &ValidationError{Name: "file_id", err: errors.New(`enttenant: missing required field "FilePropertyAssignment.file_id"`)}
	}
	if _, ok := _c.mutation.PropertyID(); !ok {
		return &ValidationError{Name: "property_id", err: errors.New(`enttenant: missing required field "FilePropertyAssignment.property_id"`)}
	}
	if len(_c.mutation.SpaceIDs()) == 0 {
		return &ValidationError{Name: "space", err: errors.New(`enttenant: missing required edge "FilePropertyAssignment.space"`)}
	}
	if len(_c.mutation.FileIDs()) == 0 {
		return &ValidationError{Name: "file", err: errors.New(`enttenant: missing required edge "FilePropertyAssignment.file"`)}
	}
	if len(_c.mutation.PropertyIDs()) == 0 {
		return &ValidationError{Name: "property", err: errors.New(`enttenant: missing required edge "FilePropertyAssignment.property"`)}
	}
	return nil
}

func (_c *FilePropertyAssignmentCreate) sqlSave(ctx context.Context) (*FilePropertyAssignment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FilePropertyAssignmentCreate) createSpec() (*FilePropertyAssignment, *sqlgraph.CreateSpec) {
	var (
		_node = &FilePropertyAssignment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(filepropertyassignment.Table, sqlgraph.NewFieldSpec(filepropertyassignment.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.TextValue(); ok {
		_spec.SetField(filepropertyassignment.FieldTextValue, field.TypeString, value)
		_node.TextValue = value
	}
	if value, ok := _c.mutation.NumberValue(); ok {
		_spec.SetField(filepropertyassignment.FieldNumberValue, field.TypeInt, value)
		_node.NumberValue = value
	}
	if value, ok := _c.mutation.DateValue(); ok {
		_spec.SetField(filepropertyassignment.FieldDateValue, field.TypeTime, value)
		_node.DateValue = value
	}
	if value, ok := _c.mutation.BoolValue(); ok {
		_spec.SetField(filepropertyassignment.FieldBoolValue, field.TypeBool, value)
		_node.BoolValue = value
	}
	if nodes := _c.mutation.SpaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   filepropertyassignment.SpaceTable,
			Columns: []string{filepropertyassignment.SpaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(space.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SpaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   filepropertyassignment.FileTable,
			Columns: []string{filepropertyassignment.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FileID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PropertyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   filepropertyassignment.PropertyTable,
			Columns: []string{filepropertyassignment.PropertyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PropertyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FilePropertyAssignmentCreateBulk is the builder for creating many FilePropertyAssignment entities in bulk.
type FilePropertyAssignmentCreateBulk struct {
	config
	err      error
	builders []*FilePropertyAssignmentCreate
}

// Save creates the FilePropertyAssignment entities in the database.
func (_c *FilePropertyAssignmentCreateBulk) Save(ctx context.Context) ([]*FilePropertyAssignment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FilePropertyAssignment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FilePropertyAssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FilePropertyAssignmentCreateBulk) SaveX(ctx context.Context) []*FilePropertyAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FilePropertyAssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FilePropertyAssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
