// Code generated by ent, DO NOT EDIT.

package enttenant

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/simpledms/simpledms/db/enttenant/file"
	"github.com/simpledms/simpledms/db/enttenant/fileversion"
	"github.com/simpledms/simpledms/db/enttenant/storedfile"
)

// FileVersionCreate is the builder for creating a FileVersion entity.
type FileVersionCreate struct {
	config
	mutation *FileVersionMutation
	hooks    []Hook
}

// SetFileID sets the "file_id" field.
func (_c *FileVersionCreate) SetFileID(v int64) *FileVersionCreate {
	_c.mutation.SetFileID(v)
	return _c
}

// SetStoredFileID sets the "stored_file_id" field.
func (_c *FileVersionCreate) SetStoredFileID(v int64) *FileVersionCreate {
	_c.mutation.SetStoredFileID(v)
	return _c
}

// SetVersionNumber sets the "version_number" field.
func (_c *FileVersionCreate) SetVersionNumber(v int) *FileVersionCreate {
	_c.mutation.SetVersionNumber(v)
	return _c
}

// SetNillableVersionNumber sets the "version_number" field if the given value is not nil.
func (_c *FileVersionCreate) SetNillableVersionNumber(v *int) *FileVersionCreate {
	if v != nil {
		_c.SetVersionNumber(*v)
	}
	return _c
}

// SetNote sets the "note" field.
func (_c *FileVersionCreate) SetNote(v string) *FileVersionCreate {
	_c.mutation.SetNote(v)
	return _c
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (_c *FileVersionCreate) SetNillableNote(v *string) *FileVersionCreate {
	if v != nil {
		_c.SetNote(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FileVersionCreate) SetID(v int64) *FileVersionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetFile sets the "file" edge to the File entity.
func (_c *FileVersionCreate) SetFile(v *File) *FileVersionCreate {
	return _c.SetFileID(v.ID)
}

// SetStoredFile sets the "stored_file" edge to the StoredFile entity.
func (_c *FileVersionCreate) SetStoredFile(v *StoredFile) *FileVersionCreate {
	return _c.SetStoredFileID(v.ID)
}

// Mutation returns the FileVersionMutation object of the builder.
func (_c *FileVersionCreate) Mutation() *FileVersionMutation {
	return _c.mutation
}

// Save creates the FileVersion in the database.
func (_c *FileVersionCreate) Save(ctx context.Context) (*FileVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FileVersionCreate) SaveX(ctx context.Context) *FileVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FileVersionCreate) defaults() {
	if _, ok := _c.mutation.VersionNumber(); !ok {
		v := fileversion.DefaultVersionNumber
		_c.mutation.SetVersionNumber(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FileVersionCreate) check() error {
	if _, ok := _c.mutation.FileID(); !ok {
		return &ValidationError{Name: "file_id", err: errors.New(`enttenant: missing required field "FileVersion.file_id"`)}
	}
	if _, ok := _c.mutation.StoredFileID(); !ok {
		return &ValidationError{Name: "stored_file_id", err: errors.New(`enttenant: missing required field "FileVersion.stored_file_id"`)}
	}
	if _, ok := _c.mutation.VersionNumber(); !ok {
		return &ValidationError{Name: "version_number", err: errors.New(`enttenant: missing required field "FileVersion.version_number"`)}
	}
	if len(_c.mutation.FileIDs()) == 0 {
		return &ValidationError{Name: "file", err: errors.New(`enttenant: missing required edge "FileVersion.file"`)}
	}
	if len(_c.mutation.StoredFileIDs()) == 0 {
		return &ValidationError{Name: "stored_file", err: errors.New(`enttenant: missing required edge "FileVersion.stored_file"`)}
	}
	return nil
}

func (_c *FileVersionCreate) sqlSave(ctx context.Context) (*FileVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FileVersionCreate) createSpec() (*FileVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &FileVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(fileversion.Table, sqlgraph.NewFieldSpec(fileversion.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.VersionNumber(); ok {
		_spec.SetField(fileversion.FieldVersionNumber, field.TypeInt, value)
		_node.VersionNumber = value
	}
	if value, ok := _c.mutation.Note(); ok {
		_spec.SetField(fileversion.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if nodes := _c.mutation.FileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   fileversion.FileTable,
			Columns: []string{fileversion.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FileID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StoredFileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   fileversion.StoredFileTable,
			Columns: []string{fileversion.StoredFileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storedfile.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StoredFileID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FileVersionCreateBulk is the builder for creating many FileVersion entities in bulk.
type FileVersionCreateBulk struct {
	config
	err      error
	builders []*FileVersionCreate
}

// Save creates the FileVersion entities in the database.
func (_c *FileVersionCreateBulk) Save(ctx context.Context) ([]*FileVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FileVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FileVersionCreateBulk) SaveX(ctx context.Context) []*FileVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
