// Code generated by ent, DO NOT EDIT.

package enttenant

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/simpledms/simpledms/db/enttenant/predicate"
	enttenantpreviewconversion "github.com/simpledms/simpledms/db/enttenant/previewconversion"
	"github.com/simpledms/simpledms/db/enttenant/storedfile"
	"github.com/simpledms/simpledms/db/enttenant/user"
	"github.com/simpledms/simpledms/model/tenant/previewconversion"
)

// PreviewConversionUpdate is the builder for updating PreviewConversion entities.
type PreviewConversionUpdate struct {
	config
	hooks     []Hook
	mutation  *PreviewConversionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PreviewConversionUpdate builder.
func (_u *PreviewConversionUpdate) Where(ps ...predicate.PreviewConversion) *PreviewConversionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PreviewConversionUpdate) SetUpdatedAt(v time.Time) *PreviewConversionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PreviewConversionUpdate) SetUpdatedBy(v int64) *PreviewConversionUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PreviewConversionUpdate) SetNillableUpdatedBy(v *int64) *PreviewConversionUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *PreviewConversionUpdate) ClearUpdatedBy() *PreviewConversionUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetSourceStoredFileID sets the "source_stored_file_id" field.
func (_u *PreviewConversionUpdate) SetSourceStoredFileID(v int64) *PreviewConversionUpdate {
	_u.mutation.SetSourceStoredFileID(v)
	return _u
}

// SetNillableSourceStoredFileID sets the "source_stored_file_id" field if the given value is not nil.
func (_u *PreviewConversionUpdate) SetNillableSourceStoredFileID(v *int64) *PreviewConversionUpdate {
	if v != nil {
		_u.SetSourceStoredFileID(*v)
	}
	return _u
}

// SetPreviewStoredFileID sets the "preview_stored_file_id" field.
func (_u *PreviewConversionUpdate) SetPreviewStoredFileID(v int64) *PreviewConversionUpdate {
	_u.mutation.SetPreviewStoredFileID(v)
	return _u
}

// SetNillablePreviewStoredFileID sets the "preview_stored_file_id" field if the given value is not nil.
func (_u *PreviewConversionUpdate) SetNillablePreviewStoredFileID(v *int64) *PreviewConversionUpdate {
	if v != nil {
		_u.SetPreviewStoredFileID(*v)
	}
	return _u
}

// ClearPreviewStoredFileID clears the value of the "preview_stored_file_id" field.
func (_u *PreviewConversionUpdate) ClearPreviewStoredFileID() *PreviewConversionUpdate {
	_u.mutation.ClearPreviewStoredFileID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PreviewConversionUpdate) SetStatus(v previewconversion.Status) *PreviewConversionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PreviewConversionUpdate) SetNillableStatus(v *previewconversion.Status) *PreviewConversionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *PreviewConversionUpdate) SetRetryCount(v int) *PreviewConversionUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *PreviewConversionUpdate) SetNillableRetryCount(v *int) *PreviewConversionUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *PreviewConversionUpdate) AddRetryCount(v int) *PreviewConversionUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetLastAttemptedAt sets the "last_attempted_at" field.
func (_u *PreviewConversionUpdate) SetLastAttemptedAt(v time.Time) *PreviewConversionUpdate {
	_u.mutation.SetLastAttemptedAt(v)
	return _u
}

// SetNillableLastAttemptedAt sets the "last_attempted_at" field if the given value is not nil.
func (_u *PreviewConversionUpdate) SetNillableLastAttemptedAt(v *time.Time) *PreviewConversionUpdate {
	if v != nil {
		_u.SetLastAttemptedAt(*v)
	}
	return _u
}

// ClearLastAttemptedAt clears the value of the "last_attempted_at" field.
func (_u *PreviewConversionUpdate) ClearLastAttemptedAt() *PreviewConversionUpdate {
	_u.mutation.ClearLastAttemptedAt()
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *PreviewConversionUpdate) SetNextAttemptAt(v time.Time) *PreviewConversionUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *PreviewConversionUpdate) SetNillableNextAttemptAt(v *time.Time) *PreviewConversionUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *PreviewConversionUpdate) ClearNextAttemptAt() *PreviewConversionUpdate {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetProcessingStartedAt sets the "processing_started_at" field.
func (_u *PreviewConversionUpdate) SetProcessingStartedAt(v time.Time) *PreviewConversionUpdate {
	_u.mutation.SetProcessingStartedAt(v)
	return _u
}

// SetNillableProcessingStartedAt sets the "processing_started_at" field if the given value is not nil.
func (_u *PreviewConversionUpdate) SetNillableProcessingStartedAt(v *time.Time) *PreviewConversionUpdate {
	if v != nil {
		_u.SetProcessingStartedAt(*v)
	}
	return _u
}

// ClearProcessingStartedAt clears the value of the "processing_started_at" field.
func (_u *PreviewConversionUpdate) ClearProcessingStartedAt() *PreviewConversionUpdate {
	_u.mutation.ClearProcessingStartedAt()
	return _u
}

// SetFailureCategory sets the "failure_category" field.
func (_u *PreviewConversionUpdate) SetFailureCategory(v string) *PreviewConversionUpdate {
	_u.mutation.SetFailureCategory(v)
	return _u
}

// SetNillableFailureCategory sets the "failure_category" field if the given value is not nil.
func (_u *PreviewConversionUpdate) SetNillableFailureCategory(v *string) *PreviewConversionUpdate {
	if v != nil {
		_u.SetFailureCategory(*v)
	}
	return _u
}

// ClearFailureCategory clears the value of the "failure_category" field.
func (_u *PreviewConversionUpdate) ClearFailureCategory() *PreviewConversionUpdate {
	_u.mutation.ClearFailureCategory()
	return _u
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_u *PreviewConversionUpdate) SetUpdaterID(id int64) *PreviewConversionUpdate {
	_u.mutation.SetUpdaterID(id)
	return _u
}

// SetNillableUpdaterID sets the "updater" edge to the User entity by ID if the given value is not nil.
func (_u *PreviewConversionUpdate) SetNillableUpdaterID(id *int64) *PreviewConversionUpdate {
	if id != nil {
		_u = _u.SetUpdaterID(*id)
	}
	return _u
}

// SetUpdater sets the "updater" edge to the User entity.
func (_u *PreviewConversionUpdate) SetUpdater(v *User) *PreviewConversionUpdate {
	return _u.SetUpdaterID(v.ID)
}

// SetSourceID sets the "source" edge to the StoredFile entity by ID.
func (_u *PreviewConversionUpdate) SetSourceID(id int64) *PreviewConversionUpdate {
	_u.mutation.SetSourceID(id)
	return _u
}

// SetSource sets the "source" edge to the StoredFile entity.
func (_u *PreviewConversionUpdate) SetSource(v *StoredFile) *PreviewConversionUpdate {
	return _u.SetSourceID(v.ID)
}

// SetPreviewID sets the "preview" edge to the StoredFile entity by ID.
func (_u *PreviewConversionUpdate) SetPreviewID(id int64) *PreviewConversionUpdate {
	_u.mutation.SetPreviewID(id)
	return _u
}

// SetNillablePreviewID sets the "preview" edge to the StoredFile entity by ID if the given value is not nil.
func (_u *PreviewConversionUpdate) SetNillablePreviewID(id *int64) *PreviewConversionUpdate {
	if id != nil {
		_u = _u.SetPreviewID(*id)
	}
	return _u
}

// SetPreview sets the "preview" edge to the StoredFile entity.
func (_u *PreviewConversionUpdate) SetPreview(v *StoredFile) *PreviewConversionUpdate {
	return _u.SetPreviewID(v.ID)
}

// Mutation returns the PreviewConversionMutation object of the builder.
func (_u *PreviewConversionUpdate) Mutation() *PreviewConversionMutation {
	return _u.mutation
}

// ClearUpdater clears the "updater" edge to the User entity.
func (_u *PreviewConversionUpdate) ClearUpdater() *PreviewConversionUpdate {
	_u.mutation.ClearUpdater()
	return _u
}

// ClearSource clears the "source" edge to the StoredFile entity.
func (_u *PreviewConversionUpdate) ClearSource() *PreviewConversionUpdate {
	_u.mutation.ClearSource()
	return _u
}

// ClearPreview clears the "preview" edge to the StoredFile entity.
func (_u *PreviewConversionUpdate) ClearPreview() *PreviewConversionUpdate {
	_u.mutation.ClearPreview()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PreviewConversionUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PreviewConversionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PreviewConversionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PreviewConversionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PreviewConversionUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if enttenantpreviewconversion.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("enttenant: uninitialized enttenantpreviewconversion.UpdateDefaultUpdatedAt (forgotten import enttenant/runtime?)")
		}
		v := enttenantpreviewconversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PreviewConversionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := enttenantpreviewconversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`enttenant: validator failed for field "PreviewConversion.status": %w`, err)}
		}
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`enttenant: clearing a required unique edge "PreviewConversion.source"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PreviewConversionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PreviewConversionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PreviewConversionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enttenantpreviewconversion.Table, enttenantpreviewconversion.Columns, sqlgraph.NewFieldSpec(enttenantpreviewconversion.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enttenantpreviewconversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enttenantpreviewconversion.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(enttenantpreviewconversion.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(enttenantpreviewconversion.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastAttemptedAt(); ok {
		_spec.SetField(enttenantpreviewconversion.FieldLastAttemptedAt, field.TypeTime, value)
	}
	if _u.mutation.LastAttemptedAtCleared() {
		_spec.ClearField(enttenantpreviewconversion.FieldLastAttemptedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(enttenantpreviewconversion.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(enttenantpreviewconversion.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ProcessingStartedAt(); ok {
		_spec.SetField(enttenantpreviewconversion.FieldProcessingStartedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessingStartedAtCleared() {
		_spec.ClearField(enttenantpreviewconversion.FieldProcessingStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailureCategory(); ok {
		_spec.SetField(enttenantpreviewconversion.FieldFailureCategory, field.TypeString, value)
	}
	if _u.mutation.FailureCategoryCleared() {
		_spec.ClearField(enttenantpreviewconversion.FieldFailureCategory, field.TypeString)
	}
	if _u.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enttenantpreviewconversion.UpdaterTable,
			Columns: []string{enttenantpreviewconversion.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enttenantpreviewconversion.UpdaterTable,
			Columns: []string{enttenantpreviewconversion.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enttenantpreviewconversion.SourceTable,
			Columns: []string{enttenantpreviewconversion.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storedfile.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enttenantpreviewconversion.SourceTable,
			Columns: []string{enttenantpreviewconversion.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storedfile.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PreviewCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enttenantpreviewconversion.PreviewTable,
			Columns: []string{enttenantpreviewconversion.PreviewColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storedfile.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PreviewIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enttenantpreviewconversion.PreviewTable,
			Columns: []string{enttenantpreviewconversion.PreviewColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storedfile.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enttenantpreviewconversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PreviewConversionUpdateOne is the builder for updating a single PreviewConversion entity.
type PreviewConversionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PreviewConversionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PreviewConversionUpdateOne) SetUpdatedAt(v time.Time) *PreviewConversionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PreviewConversionUpdateOne) SetUpdatedBy(v int64) *PreviewConversionUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PreviewConversionUpdateOne) SetNillableUpdatedBy(v *int64) *PreviewConversionUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *PreviewConversionUpdateOne) ClearUpdatedBy() *PreviewConversionUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetSourceStoredFileID sets the "source_stored_file_id" field.
func (_u *PreviewConversionUpdateOne) SetSourceStoredFileID(v int64) *PreviewConversionUpdateOne {
	_u.mutation.SetSourceStoredFileID(v)
	return _u
}

// SetNillableSourceStoredFileID sets the "source_stored_file_id" field if the given value is not nil.
func (_u *PreviewConversionUpdateOne) SetNillableSourceStoredFileID(v *int64) *PreviewConversionUpdateOne {
	if v != nil {
		_u.SetSourceStoredFileID(*v)
	}
	return _u
}

// SetPreviewStoredFileID sets the "preview_stored_file_id" field.
func (_u *PreviewConversionUpdateOne) SetPreviewStoredFileID(v int64) *PreviewConversionUpdateOne {
	_u.mutation.SetPreviewStoredFileID(v)
	return _u
}

// SetNillablePreviewStoredFileID sets the "preview_stored_file_id" field if the given value is not nil.
func (_u *PreviewConversionUpdateOne) SetNillablePreviewStoredFileID(v *int64) *PreviewConversionUpdateOne {
	if v != nil {
		_u.SetPreviewStoredFileID(*v)
	}
	return _u
}

// ClearPreviewStoredFileID clears the value of the "preview_stored_file_id" field.
func (_u *PreviewConversionUpdateOne) ClearPreviewStoredFileID() *PreviewConversionUpdateOne {
	_u.mutation.ClearPreviewStoredFileID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PreviewConversionUpdateOne) SetStatus(v previewconversion.Status) *PreviewConversionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PreviewConversionUpdateOne) SetNillableStatus(v *previewconversion.Status) *PreviewConversionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *PreviewConversionUpdateOne) SetRetryCount(v int) *PreviewConversionUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *PreviewConversionUpdateOne) SetNillableRetryCount(v *int) *PreviewConversionUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *PreviewConversionUpdateOne) AddRetryCount(v int) *PreviewConversionUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetLastAttemptedAt sets the "last_attempted_at" field.
func (_u *PreviewConversionUpdateOne) SetLastAttemptedAt(v time.Time) *PreviewConversionUpdateOne {
	_u.mutation.SetLastAttemptedAt(v)
	return _u
}

// SetNillableLastAttemptedAt sets the "last_attempted_at" field if the given value is not nil.
func (_u *PreviewConversionUpdateOne) SetNillableLastAttemptedAt(v *time.Time) *PreviewConversionUpdateOne {
	if v != nil {
		_u.SetLastAttemptedAt(*v)
	}
	return _u
}

// ClearLastAttemptedAt clears the value of the "last_attempted_at" field.
func (_u *PreviewConversionUpdateOne) ClearLastAttemptedAt() *PreviewConversionUpdateOne {
	_u.mutation.ClearLastAttemptedAt()
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *PreviewConversionUpdateOne) SetNextAttemptAt(v time.Time) *PreviewConversionUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *PreviewConversionUpdateOne) SetNillableNextAttemptAt(v *time.Time) *PreviewConversionUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// ClearNextAttemptAt clears the value of the "next_attempt_at" field.
func (_u *PreviewConversionUpdateOne) ClearNextAttemptAt() *PreviewConversionUpdateOne {
	_u.mutation.ClearNextAttemptAt()
	return _u
}

// SetProcessingStartedAt sets the "processing_started_at" field.
func (_u *PreviewConversionUpdateOne) SetProcessingStartedAt(v time.Time) *PreviewConversionUpdateOne {
	_u.mutation.SetProcessingStartedAt(v)
	return _u
}

// SetNillableProcessingStartedAt sets the "processing_started_at" field if the given value is not nil.
func (_u *PreviewConversionUpdateOne) SetNillableProcessingStartedAt(v *time.Time) *PreviewConversionUpdateOne {
	if v != nil {
		_u.SetProcessingStartedAt(*v)
	}
	return _u
}

// ClearProcessingStartedAt clears the value of the "processing_started_at" field.
func (_u *PreviewConversionUpdateOne) ClearProcessingStartedAt() *PreviewConversionUpdateOne {
	_u.mutation.ClearProcessingStartedAt()
	return _u
}

// SetFailureCategory sets the "failure_category" field.
func (_u *PreviewConversionUpdateOne) SetFailureCategory(v string) *PreviewConversionUpdateOne {
	_u.mutation.SetFailureCategory(v)
	return _u
}

// SetNillableFailureCategory sets the "failure_category" field if the given value is not nil.
func (_u *PreviewConversionUpdateOne) SetNillableFailureCategory(v *string) *PreviewConversionUpdateOne {
	if v != nil {
		_u.SetFailureCategory(*v)
	}
	return _u
}

// ClearFailureCategory clears the value of the "failure_category" field.
func (_u *PreviewConversionUpdateOne) ClearFailureCategory() *PreviewConversionUpdateOne {
	_u.mutation.ClearFailureCategory()
	return _u
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_u *PreviewConversionUpdateOne) SetUpdaterID(id int64) *PreviewConversionUpdateOne {
	_u.mutation.SetUpdaterID(id)
	return _u
}

// SetNillableUpdaterID sets the "updater" edge to the User entity by ID if the given value is not nil.
func (_u *PreviewConversionUpdateOne) SetNillableUpdaterID(id *int64) *PreviewConversionUpdateOne {
	if id != nil {
		_u = _u.SetUpdaterID(*id)
	}
	return _u
}

// SetUpdater sets the "updater" edge to the User entity.
func (_u *PreviewConversionUpdateOne) SetUpdater(v *User) *PreviewConversionUpdateOne {
	return _u.SetUpdaterID(v.ID)
}

// SetSourceID sets the "source" edge to the StoredFile entity by ID.
func (_u *PreviewConversionUpdateOne) SetSourceID(id int64) *PreviewConversionUpdateOne {
	_u.mutation.SetSourceID(id)
	return _u
}

// SetSource sets the "source" edge to the StoredFile entity.
func (_u *PreviewConversionUpdateOne) SetSource(v *StoredFile) *PreviewConversionUpdateOne {
	return _u.SetSourceID(v.ID)
}

// SetPreviewID sets the "preview" edge to the StoredFile entity by ID.
func (_u *PreviewConversionUpdateOne) SetPreviewID(id int64) *PreviewConversionUpdateOne {
	_u.mutation.SetPreviewID(id)
	return _u
}

// SetNillablePreviewID sets the "preview" edge to the StoredFile entity by ID if the given value is not nil.
func (_u *PreviewConversionUpdateOne) SetNillablePreviewID(id *int64) *PreviewConversionUpdateOne {
	if id != nil {
		_u = _u.SetPreviewID(*id)
	}
	return _u
}

// SetPreview sets the "preview" edge to the StoredFile entity.
func (_u *PreviewConversionUpdateOne) SetPreview(v *StoredFile) *PreviewConversionUpdateOne {
	return _u.SetPreviewID(v.ID)
}

// Mutation returns the PreviewConversionMutation object of the builder.
func (_u *PreviewConversionUpdateOne) Mutation() *PreviewConversionMutation {
	return _u.mutation
}

// ClearUpdater clears the "updater" edge to the User entity.
func (_u *PreviewConversionUpdateOne) ClearUpdater() *PreviewConversionUpdateOne {
	_u.mutation.ClearUpdater()
	return _u
}

// ClearSource clears the "source" edge to the StoredFile entity.
func (_u *PreviewConversionUpdateOne) ClearSource() *PreviewConversionUpdateOne {
	_u.mutation.ClearSource()
	return _u
}

// ClearPreview clears the "preview" edge to the StoredFile entity.
func (_u *PreviewConversionUpdateOne) ClearPreview() *PreviewConversionUpdateOne {
	_u.mutation.ClearPreview()
	return _u
}

// Where appends a list predicates to the PreviewConversionUpdate builder.
func (_u *PreviewConversionUpdateOne) Where(ps ...predicate.PreviewConversion) *PreviewConversionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PreviewConversionUpdateOne) Select(field string, fields ...string) *PreviewConversionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PreviewConversion entity.
func (_u *PreviewConversionUpdateOne) Save(ctx context.Context) (*PreviewConversion, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PreviewConversionUpdateOne) SaveX(ctx context.Context) *PreviewConversion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PreviewConversionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PreviewConversionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PreviewConversionUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if enttenantpreviewconversion.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("enttenant: uninitialized enttenantpreviewconversion.UpdateDefaultUpdatedAt (forgotten import enttenant/runtime?)")
		}
		v := enttenantpreviewconversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PreviewConversionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := enttenantpreviewconversion.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`enttenant: validator failed for field "PreviewConversion.status": %w`, err)}
		}
	}
	if _u.mutation.SourceCleared() && len(_u.mutation.SourceIDs()) > 0 {
		return errors.New(`enttenant: clearing a required unique edge "PreviewConversion.source"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *PreviewConversionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PreviewConversionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *PreviewConversionUpdateOne) sqlSave(ctx context.Context) (_node *PreviewConversion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(enttenantpreviewconversion.Table, enttenantpreviewconversion.Columns, sqlgraph.NewFieldSpec(enttenantpreviewconversion.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`enttenant: missing "PreviewConversion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enttenantpreviewconversion.FieldID)
		for _, f := range fields {
			if !enttenantpreviewconversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("enttenant: invalid field %q for query", f)}
			}
			if f != enttenantpreviewconversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(enttenantpreviewconversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(enttenantpreviewconversion.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(enttenantpreviewconversion.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(enttenantpreviewconversion.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastAttemptedAt(); ok {
		_spec.SetField(enttenantpreviewconversion.FieldLastAttemptedAt, field.TypeTime, value)
	}
	if _u.mutation.LastAttemptedAtCleared() {
		_spec.ClearField(enttenantpreviewconversion.FieldLastAttemptedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(enttenantpreviewconversion.FieldNextAttemptAt, field.TypeTime, value)
	}
	if _u.mutation.NextAttemptAtCleared() {
		_spec.ClearField(enttenantpreviewconversion.FieldNextAttemptAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ProcessingStartedAt(); ok {
		_spec.SetField(enttenantpreviewconversion.FieldProcessingStartedAt, field.TypeTime, value)
	}
	if _u.mutation.ProcessingStartedAtCleared() {
		_spec.ClearField(enttenantpreviewconversion.FieldProcessingStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FailureCategory(); ok {
		_spec.SetField(enttenantpreviewconversion.FieldFailureCategory, field.TypeString, value)
	}
	if _u.mutation.FailureCategoryCleared() {
		_spec.ClearField(enttenantpreviewconversion.FieldFailureCategory, field.TypeString)
	}
	if _u.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enttenantpreviewconversion.UpdaterTable,
			Columns: []string{enttenantpreviewconversion.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enttenantpreviewconversion.UpdaterTable,
			Columns: []string{enttenantpreviewconversion.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enttenantpreviewconversion.SourceTable,
			Columns: []string{enttenantpreviewconversion.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storedfile.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enttenantpreviewconversion.SourceTable,
			Columns: []string{enttenantpreviewconversion.SourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storedfile.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PreviewCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enttenantpreviewconversion.PreviewTable,
			Columns: []string{enttenantpreviewconversion.PreviewColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storedfile.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PreviewIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   enttenantpreviewconversion.PreviewTable,
			Columns: []string{enttenantpreviewconversion.PreviewColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storedfile.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &PreviewConversion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{enttenantpreviewconversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
