// Code generated by ent, DO NOT EDIT.

package enttenant

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/simpledms/simpledms/db/enttenant/documenttype"
	"github.com/simpledms/simpledms/db/enttenant/file"
	"github.com/simpledms/simpledms/db/enttenant/predicate"
	"github.com/simpledms/simpledms/db/enttenant/property"
	"github.com/simpledms/simpledms/db/enttenant/space"
	"github.com/simpledms/simpledms/db/enttenant/spaceuserassignment"
	"github.com/simpledms/simpledms/db/enttenant/tag"
	"github.com/simpledms/simpledms/db/enttenant/user"
	"github.com/simpledms/simpledms/db/entx"
)

// SpaceUpdate is the builder for updating Space entities.
type SpaceUpdate struct {
	config
	hooks     []Hook
	mutation  *SpaceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SpaceUpdate builder.
func (su *SpaceUpdate) Where(ps ...predicate.Space) *SpaceUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetPublicID sets the "public_id" field.
func (su *SpaceUpdate) SetPublicID(et entx.CIText) *SpaceUpdate {
	su.mutation.SetPublicID(et)
	return su
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (su *SpaceUpdate) SetNillablePublicID(et *entx.CIText) *SpaceUpdate {
	if et != nil {
		su.SetPublicID(*et)
	}
	return su
}

// SetDeletedBy sets the "deleted_by" field.
func (su *SpaceUpdate) SetDeletedBy(i int64) *SpaceUpdate {
	su.mutation.SetDeletedBy(i)
	return su
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (su *SpaceUpdate) SetNillableDeletedBy(i *int64) *SpaceUpdate {
	if i != nil {
		su.SetDeletedBy(*i)
	}
	return su
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (su *SpaceUpdate) ClearDeletedBy() *SpaceUpdate {
	su.mutation.ClearDeletedBy()
	return su
}

// SetDeletedAt sets the "deleted_at" field.
func (su *SpaceUpdate) SetDeletedAt(t time.Time) *SpaceUpdate {
	su.mutation.SetDeletedAt(t)
	return su
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (su *SpaceUpdate) SetNillableDeletedAt(t *time.Time) *SpaceUpdate {
	if t != nil {
		su.SetDeletedAt(*t)
	}
	return su
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (su *SpaceUpdate) ClearDeletedAt() *SpaceUpdate {
	su.mutation.ClearDeletedAt()
	return su
}

// SetName sets the "name" field.
func (su *SpaceUpdate) SetName(s string) *SpaceUpdate {
	su.mutation.SetName(s)
	return su
}

// SetNillableName sets the "name" field if the given value is not nil.
func (su *SpaceUpdate) SetNillableName(s *string) *SpaceUpdate {
	if s != nil {
		su.SetName(*s)
	}
	return su
}

// SetIcon sets the "icon" field.
func (su *SpaceUpdate) SetIcon(s string) *SpaceUpdate {
	su.mutation.SetIcon(s)
	return su
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (su *SpaceUpdate) SetNillableIcon(s *string) *SpaceUpdate {
	if s != nil {
		su.SetIcon(*s)
	}
	return su
}

// ClearIcon clears the value of the "icon" field.
func (su *SpaceUpdate) ClearIcon() *SpaceUpdate {
	su.mutation.ClearIcon()
	return su
}

// SetDescription sets the "description" field.
func (su *SpaceUpdate) SetDescription(s string) *SpaceUpdate {
	su.mutation.SetDescription(s)
	return su
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (su *SpaceUpdate) SetNillableDescription(s *string) *SpaceUpdate {
	if s != nil {
		su.SetDescription(*s)
	}
	return su
}

// ClearDescription clears the value of the "description" field.
func (su *SpaceUpdate) ClearDescription() *SpaceUpdate {
	su.mutation.ClearDescription()
	return su
}

// SetIsFolderMode sets the "is_folder_mode" field.
func (su *SpaceUpdate) SetIsFolderMode(b bool) *SpaceUpdate {
	su.mutation.SetIsFolderMode(b)
	return su
}

// SetNillableIsFolderMode sets the "is_folder_mode" field if the given value is not nil.
func (su *SpaceUpdate) SetNillableIsFolderMode(b *bool) *SpaceUpdate {
	if b != nil {
		su.SetIsFolderMode(*b)
	}
	return su
}

// SetDeleterID sets the "deleter" edge to the User entity by ID.
func (su *SpaceUpdate) SetDeleterID(id int64) *SpaceUpdate {
	su.mutation.SetDeleterID(id)
	return su
}

// SetNillableDeleterID sets the "deleter" edge to the User entity by ID if the given value is not nil.
func (su *SpaceUpdate) SetNillableDeleterID(id *int64) *SpaceUpdate {
	if id != nil {
		su = su.SetDeleterID(*id)
	}
	return su
}

// SetDeleter sets the "deleter" edge to the User entity.
func (su *SpaceUpdate) SetDeleter(u *User) *SpaceUpdate {
	return su.SetDeleterID(u.ID)
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (su *SpaceUpdate) AddFileIDs(ids ...int64) *SpaceUpdate {
	su.mutation.AddFileIDs(ids...)
	return su
}

// AddFiles adds the "files" edges to the File entity.
func (su *SpaceUpdate) AddFiles(f ...*File) *SpaceUpdate {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return su.AddFileIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (su *SpaceUpdate) AddUserIDs(ids ...int64) *SpaceUpdate {
	su.mutation.AddUserIDs(ids...)
	return su
}

// AddUsers adds the "users" edges to the User entity.
func (su *SpaceUpdate) AddUsers(u ...*User) *SpaceUpdate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return su.AddUserIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (su *SpaceUpdate) AddTagIDs(ids ...int64) *SpaceUpdate {
	su.mutation.AddTagIDs(ids...)
	return su
}

// AddTags adds the "tags" edges to the Tag entity.
func (su *SpaceUpdate) AddTags(t ...*Tag) *SpaceUpdate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return su.AddTagIDs(ids...)
}

// AddDocumentTypeIDs adds the "document_types" edge to the DocumentType entity by IDs.
func (su *SpaceUpdate) AddDocumentTypeIDs(ids ...int64) *SpaceUpdate {
	su.mutation.AddDocumentTypeIDs(ids...)
	return su
}

// AddDocumentTypes adds the "document_types" edges to the DocumentType entity.
func (su *SpaceUpdate) AddDocumentTypes(d ...*DocumentType) *SpaceUpdate {
	ids := make([]int64, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return su.AddDocumentTypeIDs(ids...)
}

// AddPropertyIDs adds the "properties" edge to the Property entity by IDs.
func (su *SpaceUpdate) AddPropertyIDs(ids ...int64) *SpaceUpdate {
	su.mutation.AddPropertyIDs(ids...)
	return su
}

// AddProperties adds the "properties" edges to the Property entity.
func (su *SpaceUpdate) AddProperties(p ...*Property) *SpaceUpdate {
	ids := make([]int64, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return su.AddPropertyIDs(ids...)
}

// AddUserAssignmentIDs adds the "user_assignment" edge to the SpaceUserAssignment entity by IDs.
func (su *SpaceUpdate) AddUserAssignmentIDs(ids ...int64) *SpaceUpdate {
	su.mutation.AddUserAssignmentIDs(ids...)
	return su
}

// AddUserAssignment adds the "user_assignment" edges to the SpaceUserAssignment entity.
func (su *SpaceUpdate) AddUserAssignment(s ...*SpaceUserAssignment) *SpaceUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.AddUserAssignmentIDs(ids...)
}

// Mutation returns the SpaceMutation object of the builder.
func (su *SpaceUpdate) Mutation() *SpaceMutation {
	return su.mutation
}

// ClearDeleter clears the "deleter" edge to the User entity.
func (su *SpaceUpdate) ClearDeleter() *SpaceUpdate {
	su.mutation.ClearDeleter()
	return su
}

// ClearFiles clears all "files" edges to the File entity.
func (su *SpaceUpdate) ClearFiles() *SpaceUpdate {
	su.mutation.ClearFiles()
	return su
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (su *SpaceUpdate) RemoveFileIDs(ids ...int64) *SpaceUpdate {
	su.mutation.RemoveFileIDs(ids...)
	return su
}

// RemoveFiles removes "files" edges to File entities.
func (su *SpaceUpdate) RemoveFiles(f ...*File) *SpaceUpdate {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return su.RemoveFileIDs(ids...)
}

// ClearUsers clears all "users" edges to the User entity.
func (su *SpaceUpdate) ClearUsers() *SpaceUpdate {
	su.mutation.ClearUsers()
	return su
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (su *SpaceUpdate) RemoveUserIDs(ids ...int64) *SpaceUpdate {
	su.mutation.RemoveUserIDs(ids...)
	return su
}

// RemoveUsers removes "users" edges to User entities.
func (su *SpaceUpdate) RemoveUsers(u ...*User) *SpaceUpdate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return su.RemoveUserIDs(ids...)
}

// ClearTags clears all "tags" edges to the Tag entity.
func (su *SpaceUpdate) ClearTags() *SpaceUpdate {
	su.mutation.ClearTags()
	return su
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (su *SpaceUpdate) RemoveTagIDs(ids ...int64) *SpaceUpdate {
	su.mutation.RemoveTagIDs(ids...)
	return su
}

// RemoveTags removes "tags" edges to Tag entities.
func (su *SpaceUpdate) RemoveTags(t ...*Tag) *SpaceUpdate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return su.RemoveTagIDs(ids...)
}

// ClearDocumentTypes clears all "document_types" edges to the DocumentType entity.
func (su *SpaceUpdate) ClearDocumentTypes() *SpaceUpdate {
	su.mutation.ClearDocumentTypes()
	return su
}

// RemoveDocumentTypeIDs removes the "document_types" edge to DocumentType entities by IDs.
func (su *SpaceUpdate) RemoveDocumentTypeIDs(ids ...int64) *SpaceUpdate {
	su.mutation.RemoveDocumentTypeIDs(ids...)
	return su
}

// RemoveDocumentTypes removes "document_types" edges to DocumentType entities.
func (su *SpaceUpdate) RemoveDocumentTypes(d ...*DocumentType) *SpaceUpdate {
	ids := make([]int64, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return su.RemoveDocumentTypeIDs(ids...)
}

// ClearProperties clears all "properties" edges to the Property entity.
func (su *SpaceUpdate) ClearProperties() *SpaceUpdate {
	su.mutation.ClearProperties()
	return su
}

// RemovePropertyIDs removes the "properties" edge to Property entities by IDs.
func (su *SpaceUpdate) RemovePropertyIDs(ids ...int64) *SpaceUpdate {
	su.mutation.RemovePropertyIDs(ids...)
	return su
}

// RemoveProperties removes "properties" edges to Property entities.
func (su *SpaceUpdate) RemoveProperties(p ...*Property) *SpaceUpdate {
	ids := make([]int64, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return su.RemovePropertyIDs(ids...)
}

// ClearUserAssignment clears all "user_assignment" edges to the SpaceUserAssignment entity.
func (su *SpaceUpdate) ClearUserAssignment() *SpaceUpdate {
	su.mutation.ClearUserAssignment()
	return su
}

// RemoveUserAssignmentIDs removes the "user_assignment" edge to SpaceUserAssignment entities by IDs.
func (su *SpaceUpdate) RemoveUserAssignmentIDs(ids ...int64) *SpaceUpdate {
	su.mutation.RemoveUserAssignmentIDs(ids...)
	return su
}

// RemoveUserAssignment removes "user_assignment" edges to SpaceUserAssignment entities.
func (su *SpaceUpdate) RemoveUserAssignment(s ...*SpaceUserAssignment) *SpaceUpdate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return su.RemoveUserAssignmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SpaceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SpaceUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SpaceUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SpaceUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (su *SpaceUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SpaceUpdate {
	su.modifiers = append(su.modifiers, modifiers...)
	return su
}

func (su *SpaceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(space.Table, space.Columns, sqlgraph.NewFieldSpec(space.FieldID, field.TypeInt64))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.PublicID(); ok {
		_spec.SetField(space.FieldPublicID, field.TypeString, value)
	}
	if value, ok := su.mutation.DeletedAt(); ok {
		_spec.SetField(space.FieldDeletedAt, field.TypeTime, value)
	}
	if su.mutation.DeletedAtCleared() {
		_spec.ClearField(space.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := su.mutation.Name(); ok {
		_spec.SetField(space.FieldName, field.TypeString, value)
	}
	if value, ok := su.mutation.Icon(); ok {
		_spec.SetField(space.FieldIcon, field.TypeString, value)
	}
	if su.mutation.IconCleared() {
		_spec.ClearField(space.FieldIcon, field.TypeString)
	}
	if value, ok := su.mutation.Description(); ok {
		_spec.SetField(space.FieldDescription, field.TypeString, value)
	}
	if su.mutation.DescriptionCleared() {
		_spec.ClearField(space.FieldDescription, field.TypeString)
	}
	if value, ok := su.mutation.IsFolderMode(); ok {
		_spec.SetField(space.FieldIsFolderMode, field.TypeBool, value)
	}
	if su.mutation.DeleterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   space.DeleterTable,
			Columns: []string{space.DeleterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.DeleterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   space.DeleterTable,
			Columns: []string{space.DeleterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.FilesTable,
			Columns: []string{space.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedFilesIDs(); len(nodes) > 0 && !su.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.FilesTable,
			Columns: []string{space.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.FilesTable,
			Columns: []string{space.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   space.UsersTable,
			Columns: space.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		createE := &SpaceUserAssignmentCreate{config: su.config, mutation: newSpaceUserAssignmentMutation(su.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedUsersIDs(); len(nodes) > 0 && !su.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   space.UsersTable,
			Columns: space.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &SpaceUserAssignmentCreate{config: su.config, mutation: newSpaceUserAssignmentMutation(su.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   space.UsersTable,
			Columns: space.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &SpaceUserAssignmentCreate{config: su.config, mutation: newSpaceUserAssignmentMutation(su.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.TagsTable,
			Columns: []string{space.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedTagsIDs(); len(nodes) > 0 && !su.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.TagsTable,
			Columns: []string{space.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.TagsTable,
			Columns: []string{space.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.DocumentTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.DocumentTypesTable,
			Columns: []string{space.DocumentTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documenttype.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedDocumentTypesIDs(); len(nodes) > 0 && !su.mutation.DocumentTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.DocumentTypesTable,
			Columns: []string{space.DocumentTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documenttype.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.DocumentTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.DocumentTypesTable,
			Columns: []string{space.DocumentTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documenttype.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.PropertiesTable,
			Columns: []string{space.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedPropertiesIDs(); len(nodes) > 0 && !su.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.PropertiesTable,
			Columns: []string{space.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.PropertiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.PropertiesTable,
			Columns: []string{space.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if su.mutation.UserAssignmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.UserAssignmentTable,
			Columns: []string{space.UserAssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spaceuserassignment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.RemovedUserAssignmentIDs(); len(nodes) > 0 && !su.mutation.UserAssignmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.UserAssignmentTable,
			Columns: []string{space.UserAssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spaceuserassignment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := su.mutation.UserAssignmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.UserAssignmentTable,
			Columns: []string{space.UserAssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spaceuserassignment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(su.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{space.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SpaceUpdateOne is the builder for updating a single Space entity.
type SpaceUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SpaceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetPublicID sets the "public_id" field.
func (suo *SpaceUpdateOne) SetPublicID(et entx.CIText) *SpaceUpdateOne {
	suo.mutation.SetPublicID(et)
	return suo
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (suo *SpaceUpdateOne) SetNillablePublicID(et *entx.CIText) *SpaceUpdateOne {
	if et != nil {
		suo.SetPublicID(*et)
	}
	return suo
}

// SetDeletedBy sets the "deleted_by" field.
func (suo *SpaceUpdateOne) SetDeletedBy(i int64) *SpaceUpdateOne {
	suo.mutation.SetDeletedBy(i)
	return suo
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (suo *SpaceUpdateOne) SetNillableDeletedBy(i *int64) *SpaceUpdateOne {
	if i != nil {
		suo.SetDeletedBy(*i)
	}
	return suo
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (suo *SpaceUpdateOne) ClearDeletedBy() *SpaceUpdateOne {
	suo.mutation.ClearDeletedBy()
	return suo
}

// SetDeletedAt sets the "deleted_at" field.
func (suo *SpaceUpdateOne) SetDeletedAt(t time.Time) *SpaceUpdateOne {
	suo.mutation.SetDeletedAt(t)
	return suo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (suo *SpaceUpdateOne) SetNillableDeletedAt(t *time.Time) *SpaceUpdateOne {
	if t != nil {
		suo.SetDeletedAt(*t)
	}
	return suo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (suo *SpaceUpdateOne) ClearDeletedAt() *SpaceUpdateOne {
	suo.mutation.ClearDeletedAt()
	return suo
}

// SetName sets the "name" field.
func (suo *SpaceUpdateOne) SetName(s string) *SpaceUpdateOne {
	suo.mutation.SetName(s)
	return suo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (suo *SpaceUpdateOne) SetNillableName(s *string) *SpaceUpdateOne {
	if s != nil {
		suo.SetName(*s)
	}
	return suo
}

// SetIcon sets the "icon" field.
func (suo *SpaceUpdateOne) SetIcon(s string) *SpaceUpdateOne {
	suo.mutation.SetIcon(s)
	return suo
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (suo *SpaceUpdateOne) SetNillableIcon(s *string) *SpaceUpdateOne {
	if s != nil {
		suo.SetIcon(*s)
	}
	return suo
}

// ClearIcon clears the value of the "icon" field.
func (suo *SpaceUpdateOne) ClearIcon() *SpaceUpdateOne {
	suo.mutation.ClearIcon()
	return suo
}

// SetDescription sets the "description" field.
func (suo *SpaceUpdateOne) SetDescription(s string) *SpaceUpdateOne {
	suo.mutation.SetDescription(s)
	return suo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (suo *SpaceUpdateOne) SetNillableDescription(s *string) *SpaceUpdateOne {
	if s != nil {
		suo.SetDescription(*s)
	}
	return suo
}

// ClearDescription clears the value of the "description" field.
func (suo *SpaceUpdateOne) ClearDescription() *SpaceUpdateOne {
	suo.mutation.ClearDescription()
	return suo
}

// SetIsFolderMode sets the "is_folder_mode" field.
func (suo *SpaceUpdateOne) SetIsFolderMode(b bool) *SpaceUpdateOne {
	suo.mutation.SetIsFolderMode(b)
	return suo
}

// SetNillableIsFolderMode sets the "is_folder_mode" field if the given value is not nil.
func (suo *SpaceUpdateOne) SetNillableIsFolderMode(b *bool) *SpaceUpdateOne {
	if b != nil {
		suo.SetIsFolderMode(*b)
	}
	return suo
}

// SetDeleterID sets the "deleter" edge to the User entity by ID.
func (suo *SpaceUpdateOne) SetDeleterID(id int64) *SpaceUpdateOne {
	suo.mutation.SetDeleterID(id)
	return suo
}

// SetNillableDeleterID sets the "deleter" edge to the User entity by ID if the given value is not nil.
func (suo *SpaceUpdateOne) SetNillableDeleterID(id *int64) *SpaceUpdateOne {
	if id != nil {
		suo = suo.SetDeleterID(*id)
	}
	return suo
}

// SetDeleter sets the "deleter" edge to the User entity.
func (suo *SpaceUpdateOne) SetDeleter(u *User) *SpaceUpdateOne {
	return suo.SetDeleterID(u.ID)
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (suo *SpaceUpdateOne) AddFileIDs(ids ...int64) *SpaceUpdateOne {
	suo.mutation.AddFileIDs(ids...)
	return suo
}

// AddFiles adds the "files" edges to the File entity.
func (suo *SpaceUpdateOne) AddFiles(f ...*File) *SpaceUpdateOne {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return suo.AddFileIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (suo *SpaceUpdateOne) AddUserIDs(ids ...int64) *SpaceUpdateOne {
	suo.mutation.AddUserIDs(ids...)
	return suo
}

// AddUsers adds the "users" edges to the User entity.
func (suo *SpaceUpdateOne) AddUsers(u ...*User) *SpaceUpdateOne {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return suo.AddUserIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (suo *SpaceUpdateOne) AddTagIDs(ids ...int64) *SpaceUpdateOne {
	suo.mutation.AddTagIDs(ids...)
	return suo
}

// AddTags adds the "tags" edges to the Tag entity.
func (suo *SpaceUpdateOne) AddTags(t ...*Tag) *SpaceUpdateOne {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return suo.AddTagIDs(ids...)
}

// AddDocumentTypeIDs adds the "document_types" edge to the DocumentType entity by IDs.
func (suo *SpaceUpdateOne) AddDocumentTypeIDs(ids ...int64) *SpaceUpdateOne {
	suo.mutation.AddDocumentTypeIDs(ids...)
	return suo
}

// AddDocumentTypes adds the "document_types" edges to the DocumentType entity.
func (suo *SpaceUpdateOne) AddDocumentTypes(d ...*DocumentType) *SpaceUpdateOne {
	ids := make([]int64, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return suo.AddDocumentTypeIDs(ids...)
}

// AddPropertyIDs adds the "properties" edge to the Property entity by IDs.
func (suo *SpaceUpdateOne) AddPropertyIDs(ids ...int64) *SpaceUpdateOne {
	suo.mutation.AddPropertyIDs(ids...)
	return suo
}

// AddProperties adds the "properties" edges to the Property entity.
func (suo *SpaceUpdateOne) AddProperties(p ...*Property) *SpaceUpdateOne {
	ids := make([]int64, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return suo.AddPropertyIDs(ids...)
}

// AddUserAssignmentIDs adds the "user_assignment" edge to the SpaceUserAssignment entity by IDs.
func (suo *SpaceUpdateOne) AddUserAssignmentIDs(ids ...int64) *SpaceUpdateOne {
	suo.mutation.AddUserAssignmentIDs(ids...)
	return suo
}

// AddUserAssignment adds the "user_assignment" edges to the SpaceUserAssignment entity.
func (suo *SpaceUpdateOne) AddUserAssignment(s ...*SpaceUserAssignment) *SpaceUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.AddUserAssignmentIDs(ids...)
}

// Mutation returns the SpaceMutation object of the builder.
func (suo *SpaceUpdateOne) Mutation() *SpaceMutation {
	return suo.mutation
}

// ClearDeleter clears the "deleter" edge to the User entity.
func (suo *SpaceUpdateOne) ClearDeleter() *SpaceUpdateOne {
	suo.mutation.ClearDeleter()
	return suo
}

// ClearFiles clears all "files" edges to the File entity.
func (suo *SpaceUpdateOne) ClearFiles() *SpaceUpdateOne {
	suo.mutation.ClearFiles()
	return suo
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (suo *SpaceUpdateOne) RemoveFileIDs(ids ...int64) *SpaceUpdateOne {
	suo.mutation.RemoveFileIDs(ids...)
	return suo
}

// RemoveFiles removes "files" edges to File entities.
func (suo *SpaceUpdateOne) RemoveFiles(f ...*File) *SpaceUpdateOne {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return suo.RemoveFileIDs(ids...)
}

// ClearUsers clears all "users" edges to the User entity.
func (suo *SpaceUpdateOne) ClearUsers() *SpaceUpdateOne {
	suo.mutation.ClearUsers()
	return suo
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (suo *SpaceUpdateOne) RemoveUserIDs(ids ...int64) *SpaceUpdateOne {
	suo.mutation.RemoveUserIDs(ids...)
	return suo
}

// RemoveUsers removes "users" edges to User entities.
func (suo *SpaceUpdateOne) RemoveUsers(u ...*User) *SpaceUpdateOne {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return suo.RemoveUserIDs(ids...)
}

// ClearTags clears all "tags" edges to the Tag entity.
func (suo *SpaceUpdateOne) ClearTags() *SpaceUpdateOne {
	suo.mutation.ClearTags()
	return suo
}

// RemoveTagIDs removes the "tags" edge to Tag entities by IDs.
func (suo *SpaceUpdateOne) RemoveTagIDs(ids ...int64) *SpaceUpdateOne {
	suo.mutation.RemoveTagIDs(ids...)
	return suo
}

// RemoveTags removes "tags" edges to Tag entities.
func (suo *SpaceUpdateOne) RemoveTags(t ...*Tag) *SpaceUpdateOne {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return suo.RemoveTagIDs(ids...)
}

// ClearDocumentTypes clears all "document_types" edges to the DocumentType entity.
func (suo *SpaceUpdateOne) ClearDocumentTypes() *SpaceUpdateOne {
	suo.mutation.ClearDocumentTypes()
	return suo
}

// RemoveDocumentTypeIDs removes the "document_types" edge to DocumentType entities by IDs.
func (suo *SpaceUpdateOne) RemoveDocumentTypeIDs(ids ...int64) *SpaceUpdateOne {
	suo.mutation.RemoveDocumentTypeIDs(ids...)
	return suo
}

// RemoveDocumentTypes removes "document_types" edges to DocumentType entities.
func (suo *SpaceUpdateOne) RemoveDocumentTypes(d ...*DocumentType) *SpaceUpdateOne {
	ids := make([]int64, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return suo.RemoveDocumentTypeIDs(ids...)
}

// ClearProperties clears all "properties" edges to the Property entity.
func (suo *SpaceUpdateOne) ClearProperties() *SpaceUpdateOne {
	suo.mutation.ClearProperties()
	return suo
}

// RemovePropertyIDs removes the "properties" edge to Property entities by IDs.
func (suo *SpaceUpdateOne) RemovePropertyIDs(ids ...int64) *SpaceUpdateOne {
	suo.mutation.RemovePropertyIDs(ids...)
	return suo
}

// RemoveProperties removes "properties" edges to Property entities.
func (suo *SpaceUpdateOne) RemoveProperties(p ...*Property) *SpaceUpdateOne {
	ids := make([]int64, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return suo.RemovePropertyIDs(ids...)
}

// ClearUserAssignment clears all "user_assignment" edges to the SpaceUserAssignment entity.
func (suo *SpaceUpdateOne) ClearUserAssignment() *SpaceUpdateOne {
	suo.mutation.ClearUserAssignment()
	return suo
}

// RemoveUserAssignmentIDs removes the "user_assignment" edge to SpaceUserAssignment entities by IDs.
func (suo *SpaceUpdateOne) RemoveUserAssignmentIDs(ids ...int64) *SpaceUpdateOne {
	suo.mutation.RemoveUserAssignmentIDs(ids...)
	return suo
}

// RemoveUserAssignment removes "user_assignment" edges to SpaceUserAssignment entities.
func (suo *SpaceUpdateOne) RemoveUserAssignment(s ...*SpaceUserAssignment) *SpaceUpdateOne {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return suo.RemoveUserAssignmentIDs(ids...)
}

// Where appends a list predicates to the SpaceUpdate builder.
func (suo *SpaceUpdateOne) Where(ps ...predicate.Space) *SpaceUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SpaceUpdateOne) Select(field string, fields ...string) *SpaceUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Space entity.
func (suo *SpaceUpdateOne) Save(ctx context.Context) (*Space, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SpaceUpdateOne) SaveX(ctx context.Context) *Space {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SpaceUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SpaceUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (suo *SpaceUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SpaceUpdateOne {
	suo.modifiers = append(suo.modifiers, modifiers...)
	return suo
}

func (suo *SpaceUpdateOne) sqlSave(ctx context.Context) (_node *Space, err error) {
	_spec := sqlgraph.NewUpdateSpec(space.Table, space.Columns, sqlgraph.NewFieldSpec(space.FieldID, field.TypeInt64))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`enttenant: missing "Space.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, space.FieldID)
		for _, f := range fields {
			if !space.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("enttenant: invalid field %q for query", f)}
			}
			if f != space.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.PublicID(); ok {
		_spec.SetField(space.FieldPublicID, field.TypeString, value)
	}
	if value, ok := suo.mutation.DeletedAt(); ok {
		_spec.SetField(space.FieldDeletedAt, field.TypeTime, value)
	}
	if suo.mutation.DeletedAtCleared() {
		_spec.ClearField(space.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := suo.mutation.Name(); ok {
		_spec.SetField(space.FieldName, field.TypeString, value)
	}
	if value, ok := suo.mutation.Icon(); ok {
		_spec.SetField(space.FieldIcon, field.TypeString, value)
	}
	if suo.mutation.IconCleared() {
		_spec.ClearField(space.FieldIcon, field.TypeString)
	}
	if value, ok := suo.mutation.Description(); ok {
		_spec.SetField(space.FieldDescription, field.TypeString, value)
	}
	if suo.mutation.DescriptionCleared() {
		_spec.ClearField(space.FieldDescription, field.TypeString)
	}
	if value, ok := suo.mutation.IsFolderMode(); ok {
		_spec.SetField(space.FieldIsFolderMode, field.TypeBool, value)
	}
	if suo.mutation.DeleterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   space.DeleterTable,
			Columns: []string{space.DeleterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.DeleterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   space.DeleterTable,
			Columns: []string{space.DeleterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.FilesTable,
			Columns: []string{space.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedFilesIDs(); len(nodes) > 0 && !suo.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.FilesTable,
			Columns: []string{space.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.FilesTable,
			Columns: []string{space.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   space.UsersTable,
			Columns: space.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		createE := &SpaceUserAssignmentCreate{config: suo.config, mutation: newSpaceUserAssignmentMutation(suo.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedUsersIDs(); len(nodes) > 0 && !suo.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   space.UsersTable,
			Columns: space.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &SpaceUserAssignmentCreate{config: suo.config, mutation: newSpaceUserAssignmentMutation(suo.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   space.UsersTable,
			Columns: space.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &SpaceUserAssignmentCreate{config: suo.config, mutation: newSpaceUserAssignmentMutation(suo.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.TagsTable,
			Columns: []string{space.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedTagsIDs(); len(nodes) > 0 && !suo.mutation.TagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.TagsTable,
			Columns: []string{space.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.TagsTable,
			Columns: []string{space.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.DocumentTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.DocumentTypesTable,
			Columns: []string{space.DocumentTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documenttype.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedDocumentTypesIDs(); len(nodes) > 0 && !suo.mutation.DocumentTypesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.DocumentTypesTable,
			Columns: []string{space.DocumentTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documenttype.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.DocumentTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.DocumentTypesTable,
			Columns: []string{space.DocumentTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documenttype.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.PropertiesTable,
			Columns: []string{space.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedPropertiesIDs(); len(nodes) > 0 && !suo.mutation.PropertiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.PropertiesTable,
			Columns: []string{space.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.PropertiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.PropertiesTable,
			Columns: []string{space.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if suo.mutation.UserAssignmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.UserAssignmentTable,
			Columns: []string{space.UserAssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spaceuserassignment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.RemovedUserAssignmentIDs(); len(nodes) > 0 && !suo.mutation.UserAssignmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.UserAssignmentTable,
			Columns: []string{space.UserAssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spaceuserassignment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := suo.mutation.UserAssignmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.UserAssignmentTable,
			Columns: []string{space.UserAssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spaceuserassignment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(suo.modifiers...)
	_node = &Space{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{space.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
