-- create "accounts" table
CREATE TABLE `accounts` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `created_at` datetime NOT NULL, `created_by` integer NULL, `updated_at` datetime NOT NULL, `updated_by` integer NULL, `deleted_by` integer NULL, `deleted_at` datetime NULL, `public_id` text NOT NULL, `email` text NOT NULL, `first_name` text NOT NULL, `last_name` text NOT NULL, `language` text NOT NULL, `subscribed_to_newsletter_at` datetime NULL, `password_salt` text NOT NULL DEFAULT (''), `password_hash` text NOT NULL DEFAULT (''), `temporary_password_salt` text NOT NULL DEFAULT (''), `temporary_password_hash` text NOT NULL DEFAULT (''), `temporary_password_expires_at` datetime NULL, `temporary_two_factor_auth_key_encrypted` text NOT NULL DEFAULT (''), `two_factory_auth_key_encrypted` text NOT NULL DEFAULT (''), `two_factor_auth_recovery_code_salt` text NOT NULL DEFAULT (''), `two_factor_auth_recovery_code_hashes` json NOT NULL, `last_login_attempt_at` datetime NULL, `role` text NOT NULL);
-- create index "accounts_public_id_key" to table: "accounts"
CREATE UNIQUE INDEX `accounts_public_id_key` ON `accounts` (`public_id`);
-- create index "account_email" to table: "accounts"
CREATE UNIQUE INDEX `account_email` ON `accounts` (`email`) WHERE `deleted_at` is null;
-- create "mails" table
CREATE TABLE `mails` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `subject` text NOT NULL, `body` text NOT NULL, `html_body` text NULL, `sent_at` datetime NULL, `last_tried_at` datetime NOT NULL, `retry_count` integer NOT NULL DEFAULT (0), `created_by` integer NULL, `updated_by` integer NULL, `receiver_id` integer NOT NULL, CONSTRAINT `mails_accounts_creator` FOREIGN KEY (`created_by`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION, CONSTRAINT `mails_accounts_updater` FOREIGN KEY (`updated_by`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION, CONSTRAINT `mails_accounts_receiver` FOREIGN KEY (`receiver_id`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION);
-- create "sessions" table
CREATE TABLE `sessions` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `value` text NOT NULL, `is_temporary_session` bool NOT NULL, `expires_at` datetime NOT NULL, `deletable_at` datetime NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `account_id` integer NOT NULL, CONSTRAINT `sessions_accounts_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION);
-- create index "sessions_value_key" to table: "sessions"
CREATE UNIQUE INDEX `sessions_value_key` ON `sessions` (`value`);
-- create "system_configs" table
CREATE TABLE `system_configs` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `x25519_identity` blob NOT NULL, `is_identity_encrypted_with_passphrase` bool NOT NULL, `s3_endpoint` text NOT NULL, `s3_access_key_id` text NOT NULL, `s3_secret_access_key` blob NOT NULL, `s3_bucket_name` text NOT NULL, `s3_use_ssl` bool NOT NULL DEFAULT (true), `tls_enable_autocert` bool NOT NULL, `tls_cert_filepath` text NOT NULL, `tls_private_key_filepath` text NOT NULL, `tls_autocert_email` text NOT NULL, `tls_autocert_hosts` json NOT NULL, `mailer_host` text NOT NULL DEFAULT (''), `mailer_port` integer NOT NULL DEFAULT (25), `mailer_username` text NOT NULL DEFAULT (''), `mailer_password` blob NULL, `mailer_from` text NOT NULL DEFAULT (''), `mailer_insecure_skip_verify` bool NOT NULL DEFAULT (false), `initialized_at` datetime NULL, `created_by` integer NULL, `updated_by` integer NULL, CONSTRAINT `system_configs_accounts_creator` FOREIGN KEY (`created_by`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION, CONSTRAINT `system_configs_accounts_updater` FOREIGN KEY (`updated_by`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION);
-- create "temporary_files" table
CREATE TABLE `temporary_files` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `public_id` text NOT NULL, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `deleted_at` datetime NULL, `filename` text NOT NULL, `size` integer NULL, `size_in_storage` integer NOT NULL, `sha256` text NULL, `mime_type` text NULL, `storage_type` text NOT NULL, `bucket_name` text NULL, `storage_path` text NOT NULL, `storage_filename` text NOT NULL, `upload_token` text NOT NULL, `converted_to_stored_file_at` datetime NULL, `expires_at` datetime NULL, `created_by` integer NULL, `updated_by` integer NULL, `deleted_by` integer NULL, `owner_id` integer NOT NULL, CONSTRAINT `temporary_files_accounts_creator` FOREIGN KEY (`created_by`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION, CONSTRAINT `temporary_files_accounts_updater` FOREIGN KEY (`updated_by`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION, CONSTRAINT `temporary_files_accounts_deleter` FOREIGN KEY (`deleted_by`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION, CONSTRAINT `temporary_files_accounts_owner` FOREIGN KEY (`owner_id`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION);
-- create index "temporary_files_public_id_key" to table: "temporary_files"
CREATE UNIQUE INDEX `temporary_files_public_id_key` ON `temporary_files` (`public_id`);
-- create index "temporaryfile_upload_token" to table: "temporary_files"
CREATE INDEX `temporaryfile_upload_token` ON `temporary_files` (`upload_token`);
-- create "tenants" table
CREATE TABLE `tenants` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `deleted_at` datetime NULL, `public_id` text NOT NULL, `name` text NOT NULL, `first_name` text NOT NULL DEFAULT (''), `last_name` text NOT NULL DEFAULT (''), `street` text NOT NULL DEFAULT (''), `house_number` text NOT NULL DEFAULT (''), `additional_address_info` text NOT NULL DEFAULT (''), `postal_code` text NOT NULL DEFAULT (''), `city` text NOT NULL DEFAULT (''), `country` text NOT NULL, `vat_id` text NOT NULL DEFAULT (''), `terms_of_service_accepted` datetime NOT NULL, `privacy_policy_accepted` datetime NOT NULL, `two_factor_auth_enforced` bool NOT NULL DEFAULT (false), `x25519_identity_encrypted` blob NULL, `maintenance_mode_enabled_at` datetime NULL, `initialized_at` datetime NULL, `created_by` integer NULL, `updated_by` integer NULL, `deleted_by` integer NULL, CONSTRAINT `tenants_accounts_creator` FOREIGN KEY (`created_by`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION, CONSTRAINT `tenants_accounts_updater` FOREIGN KEY (`updated_by`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION, CONSTRAINT `tenants_accounts_deleter` FOREIGN KEY (`deleted_by`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION);
-- create index "tenants_public_id_key" to table: "tenants"
CREATE UNIQUE INDEX `tenants_public_id_key` ON `tenants` (`public_id`);
-- create "tenant_account_assignments" table
CREATE TABLE `tenant_account_assignments` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `is_contact_person` bool NOT NULL DEFAULT (false), `is_default` bool NOT NULL DEFAULT (false), `role` text NOT NULL, `expires_at` datetime NULL, `created_by` integer NULL, `updated_by` integer NULL, `tenant_id` integer NOT NULL, `account_id` integer NOT NULL, CONSTRAINT `tenant_account_assignments_accounts_creator` FOREIGN KEY (`created_by`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION, CONSTRAINT `tenant_account_assignments_accounts_updater` FOREIGN KEY (`updated_by`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION, CONSTRAINT `tenant_account_assignments_tenants_tenant` FOREIGN KEY (`tenant_id`) REFERENCES `tenants` (`id`) ON DELETE NO ACTION, CONSTRAINT `tenant_account_assignments_accounts_account` FOREIGN KEY (`account_id`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION);
-- create index "tenantaccountassignment_tenant_id_account_id" to table: "tenant_account_assignments"
CREATE UNIQUE INDEX `tenantaccountassignment_tenant_id_account_id` ON `tenant_account_assignments` (`tenant_id`, `account_id`);
-- create index "tenantaccountassignment_account_id_is_default" to table: "tenant_account_assignments"
CREATE UNIQUE INDEX `tenantaccountassignment_account_id_is_default` ON `tenant_account_assignments` (`account_id`, `is_default`) WHERE `is_default` = true;
