-- disable the enforcement of foreign-keys constraints
PRAGMA foreign_keys = off;
-- create "new_system_configs" table
CREATE TABLE `new_system_configs` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `x25519_identity` blob NOT NULL, `is_identity_encrypted_with_passphrase` bool NOT NULL, `s3_endpoint` text NOT NULL, `s3_access_key_id` text NOT NULL, `s3_secret_access_key` blob NOT NULL, `s3_bucket_name` text NOT NULL, `s3_use_ssl` bool NOT NULL DEFAULT (true), `tls_enable_autocert` bool NOT NULL, `tls_cert_filepath` text NOT NULL, `tls_private_key_filepath` text NOT NULL, `tls_autocert_email` text NOT NULL, `tls_autocert_hosts` json NOT NULL, `mailer_host` text NOT NULL DEFAULT (''), `mailer_port` integer NOT NULL DEFAULT (25), `mailer_username` text NOT NULL DEFAULT (''), `mailer_password` blob NULL, `mailer_from` text NOT NULL DEFAULT (''), `mailer_insecure_skip_verify` bool NOT NULL DEFAULT (false), `mailer_use_implicit_ssl_tls` bool NOT NULL DEFAULT (false), `ocr_tika_url` text NOT NULL DEFAULT (''), `initialized_at` datetime NULL, `created_by` integer NULL, `updated_by` integer NULL, CONSTRAINT `system_configs_accounts_creator` FOREIGN KEY (`created_by`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION, CONSTRAINT `system_configs_accounts_updater` FOREIGN KEY (`updated_by`) REFERENCES `accounts` (`id`) ON DELETE NO ACTION);
-- copy rows from old table "system_configs" to new temporary table "new_system_configs"
INSERT INTO `new_system_configs` (`id`, `created_at`, `updated_at`, `x25519_identity`, `is_identity_encrypted_with_passphrase`, `s3_endpoint`, `s3_access_key_id`, `s3_secret_access_key`, `s3_bucket_name`, `s3_use_ssl`, `tls_enable_autocert`, `tls_cert_filepath`, `tls_private_key_filepath`, `tls_autocert_email`, `tls_autocert_hosts`, `mailer_host`, `mailer_port`, `mailer_username`, `mailer_password`, `mailer_from`, `mailer_insecure_skip_verify`, `ocr_tika_url`, `initialized_at`, `created_by`, `updated_by`) SELECT `id`, `created_at`, `updated_at`, `x25519_identity`, `is_identity_encrypted_with_passphrase`, `s3_endpoint`, `s3_access_key_id`, `s3_secret_access_key`, `s3_bucket_name`, `s3_use_ssl`, `tls_enable_autocert`, `tls_cert_filepath`, `tls_private_key_filepath`, `tls_autocert_email`, `tls_autocert_hosts`, `mailer_host`, `mailer_port`, `mailer_username`, `mailer_password`, `mailer_from`, `mailer_insecure_skip_verify`, `ocr_tika_url`, `initialized_at`, `created_by`, `updated_by` FROM `system_configs`;
-- drop "system_configs" table after copying rows
DROP TABLE `system_configs`;
-- rename temporary table "new_system_configs" to "system_configs"
ALTER TABLE `new_system_configs` RENAME TO `system_configs`;
-- enable back the enforcement of foreign-keys constraints
PRAGMA foreign_keys = on;
