// Code generated by ent, DO NOT EDIT.

package entmain

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/simpledms/simpledms/app/simpledms/entmain/account"
	"github.com/simpledms/simpledms/app/simpledms/entmain/mail"
)

// Mail is the model entity for the Mail schema.
type Mail struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy int64 `json:"updated_by,omitempty"`
	// Subject holds the value of the "subject" field.
	Subject string `json:"subject,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// HTMLBody holds the value of the "html_body" field.
	HTMLBody string `json:"html_body,omitempty"`
	// SentAt holds the value of the "sent_at" field.
	SentAt *time.Time `json:"sent_at,omitempty"`
	// LastTriedAt holds the value of the "last_tried_at" field.
	LastTriedAt time.Time `json:"last_tried_at,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount int `json:"retry_count,omitempty"`
	// ReceiverID holds the value of the "receiver_id" field.
	ReceiverID int64 `json:"receiver_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MailQuery when eager-loading is set.
	Edges        MailEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MailEdges holds the relations/edges for other nodes in the graph.
type MailEdges struct {
	// Creator holds the value of the creator edge.
	Creator *Account `json:"creator,omitempty"`
	// Updater holds the value of the updater edge.
	Updater *Account `json:"updater,omitempty"`
	// Receiver holds the value of the receiver edge.
	Receiver *Account `json:"receiver,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MailEdges) CreatorOrErr() (*Account, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// UpdaterOrErr returns the Updater value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MailEdges) UpdaterOrErr() (*Account, error) {
	if e.Updater != nil {
		return e.Updater, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "updater"}
}

// ReceiverOrErr returns the Receiver value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MailEdges) ReceiverOrErr() (*Account, error) {
	if e.Receiver != nil {
		return e.Receiver, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "receiver"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Mail) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case mail.FieldID, mail.FieldCreatedBy, mail.FieldUpdatedBy, mail.FieldRetryCount, mail.FieldReceiverID:
			values[i] = new(sql.NullInt64)
		case mail.FieldSubject, mail.FieldBody, mail.FieldHTMLBody:
			values[i] = new(sql.NullString)
		case mail.FieldCreatedAt, mail.FieldUpdatedAt, mail.FieldSentAt, mail.FieldLastTriedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Mail fields.
func (m *Mail) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mail.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			m.ID = int64(value.Int64)
		case mail.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				m.CreatedAt = value.Time
			}
		case mail.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				m.CreatedBy = value.Int64
			}
		case mail.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				m.UpdatedAt = value.Time
			}
		case mail.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				m.UpdatedBy = value.Int64
			}
		case mail.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				m.Subject = value.String
			}
		case mail.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				m.Body = value.String
			}
		case mail.FieldHTMLBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field html_body", values[i])
			} else if value.Valid {
				m.HTMLBody = value.String
			}
		case mail.FieldSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sent_at", values[i])
			} else if value.Valid {
				m.SentAt = new(time.Time)
				*m.SentAt = value.Time
			}
		case mail.FieldLastTriedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_tried_at", values[i])
			} else if value.Valid {
				m.LastTriedAt = value.Time
			}
		case mail.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				m.RetryCount = int(value.Int64)
			}
		case mail.FieldReceiverID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field receiver_id", values[i])
			} else if value.Valid {
				m.ReceiverID = value.Int64
			}
		default:
			m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Mail.
// This includes values selected through modifiers, order, etc.
func (m *Mail) Value(name string) (ent.Value, error) {
	return m.selectValues.Get(name)
}

// QueryCreator queries the "creator" edge of the Mail entity.
func (m *Mail) QueryCreator() *AccountQuery {
	return NewMailClient(m.config).QueryCreator(m)
}

// QueryUpdater queries the "updater" edge of the Mail entity.
func (m *Mail) QueryUpdater() *AccountQuery {
	return NewMailClient(m.config).QueryUpdater(m)
}

// QueryReceiver queries the "receiver" edge of the Mail entity.
func (m *Mail) QueryReceiver() *AccountQuery {
	return NewMailClient(m.config).QueryReceiver(m)
}

// Update returns a builder for updating this Mail.
// Note that you need to call Mail.Unwrap() before calling this method if this Mail
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Mail) Update() *MailUpdateOne {
	return NewMailClient(m.config).UpdateOne(m)
}

// Unwrap unwraps the Mail entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (m *Mail) Unwrap() *Mail {
	_tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("entmain: Mail is not a transactional entity")
	}
	m.config.driver = _tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Mail) String() string {
	var builder strings.Builder
	builder.WriteString("Mail(")
	builder.WriteString(fmt.Sprintf("id=%v, ", m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", m.UpdatedBy))
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(m.Subject)
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(m.Body)
	builder.WriteString(", ")
	builder.WriteString("html_body=")
	builder.WriteString(m.HTMLBody)
	builder.WriteString(", ")
	if v := m.SentAt; v != nil {
		builder.WriteString("sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_tried_at=")
	builder.WriteString(m.LastTriedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", m.RetryCount))
	builder.WriteString(", ")
	builder.WriteString("receiver_id=")
	builder.WriteString(fmt.Sprintf("%v", m.ReceiverID))
	builder.WriteByte(')')
	return builder.String()
}

// Mails is a parsable slice of Mail.
type Mails []*Mail
