// Code generated by ent, DO NOT EDIT.

package enttenant

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/simpledms/simpledms/enttenant/documenttype"
	"github.com/simpledms/simpledms/enttenant/file"
	"github.com/simpledms/simpledms/enttenant/property"
	"github.com/simpledms/simpledms/enttenant/space"
	"github.com/simpledms/simpledms/enttenant/spaceuserassignment"
	"github.com/simpledms/simpledms/enttenant/tag"
	"github.com/simpledms/simpledms/enttenant/user"
	"github.com/simpledms/simpledms/entx"
)

// SpaceCreate is the builder for creating a Space entity.
type SpaceCreate struct {
	config
	mutation *SpaceMutation
	hooks    []Hook
}

// SetPublicID sets the "public_id" field.
func (sc *SpaceCreate) SetPublicID(et entx.CIText) *SpaceCreate {
	sc.mutation.SetPublicID(et)
	return sc
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (sc *SpaceCreate) SetNillablePublicID(et *entx.CIText) *SpaceCreate {
	if et != nil {
		sc.SetPublicID(*et)
	}
	return sc
}

// SetDeletedBy sets the "deleted_by" field.
func (sc *SpaceCreate) SetDeletedBy(i int64) *SpaceCreate {
	sc.mutation.SetDeletedBy(i)
	return sc
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (sc *SpaceCreate) SetNillableDeletedBy(i *int64) *SpaceCreate {
	if i != nil {
		sc.SetDeletedBy(*i)
	}
	return sc
}

// SetDeletedAt sets the "deleted_at" field.
func (sc *SpaceCreate) SetDeletedAt(t time.Time) *SpaceCreate {
	sc.mutation.SetDeletedAt(t)
	return sc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sc *SpaceCreate) SetNillableDeletedAt(t *time.Time) *SpaceCreate {
	if t != nil {
		sc.SetDeletedAt(*t)
	}
	return sc
}

// SetName sets the "name" field.
func (sc *SpaceCreate) SetName(s string) *SpaceCreate {
	sc.mutation.SetName(s)
	return sc
}

// SetIcon sets the "icon" field.
func (sc *SpaceCreate) SetIcon(s string) *SpaceCreate {
	sc.mutation.SetIcon(s)
	return sc
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (sc *SpaceCreate) SetNillableIcon(s *string) *SpaceCreate {
	if s != nil {
		sc.SetIcon(*s)
	}
	return sc
}

// SetDescription sets the "description" field.
func (sc *SpaceCreate) SetDescription(s string) *SpaceCreate {
	sc.mutation.SetDescription(s)
	return sc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (sc *SpaceCreate) SetNillableDescription(s *string) *SpaceCreate {
	if s != nil {
		sc.SetDescription(*s)
	}
	return sc
}

// SetIsFolderMode sets the "is_folder_mode" field.
func (sc *SpaceCreate) SetIsFolderMode(b bool) *SpaceCreate {
	sc.mutation.SetIsFolderMode(b)
	return sc
}

// SetNillableIsFolderMode sets the "is_folder_mode" field if the given value is not nil.
func (sc *SpaceCreate) SetNillableIsFolderMode(b *bool) *SpaceCreate {
	if b != nil {
		sc.SetIsFolderMode(*b)
	}
	return sc
}

// SetID sets the "id" field.
func (sc *SpaceCreate) SetID(i int64) *SpaceCreate {
	sc.mutation.SetID(i)
	return sc
}

// SetDeleterID sets the "deleter" edge to the User entity by ID.
func (sc *SpaceCreate) SetDeleterID(id int64) *SpaceCreate {
	sc.mutation.SetDeleterID(id)
	return sc
}

// SetNillableDeleterID sets the "deleter" edge to the User entity by ID if the given value is not nil.
func (sc *SpaceCreate) SetNillableDeleterID(id *int64) *SpaceCreate {
	if id != nil {
		sc = sc.SetDeleterID(*id)
	}
	return sc
}

// SetDeleter sets the "deleter" edge to the User entity.
func (sc *SpaceCreate) SetDeleter(u *User) *SpaceCreate {
	return sc.SetDeleterID(u.ID)
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (sc *SpaceCreate) AddFileIDs(ids ...int64) *SpaceCreate {
	sc.mutation.AddFileIDs(ids...)
	return sc
}

// AddFiles adds the "files" edges to the File entity.
func (sc *SpaceCreate) AddFiles(f ...*File) *SpaceCreate {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return sc.AddFileIDs(ids...)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (sc *SpaceCreate) AddUserIDs(ids ...int64) *SpaceCreate {
	sc.mutation.AddUserIDs(ids...)
	return sc
}

// AddUsers adds the "users" edges to the User entity.
func (sc *SpaceCreate) AddUsers(u ...*User) *SpaceCreate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return sc.AddUserIDs(ids...)
}

// AddTagIDs adds the "tags" edge to the Tag entity by IDs.
func (sc *SpaceCreate) AddTagIDs(ids ...int64) *SpaceCreate {
	sc.mutation.AddTagIDs(ids...)
	return sc
}

// AddTags adds the "tags" edges to the Tag entity.
func (sc *SpaceCreate) AddTags(t ...*Tag) *SpaceCreate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return sc.AddTagIDs(ids...)
}

// AddDocumentTypeIDs adds the "document_types" edge to the DocumentType entity by IDs.
func (sc *SpaceCreate) AddDocumentTypeIDs(ids ...int64) *SpaceCreate {
	sc.mutation.AddDocumentTypeIDs(ids...)
	return sc
}

// AddDocumentTypes adds the "document_types" edges to the DocumentType entity.
func (sc *SpaceCreate) AddDocumentTypes(d ...*DocumentType) *SpaceCreate {
	ids := make([]int64, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return sc.AddDocumentTypeIDs(ids...)
}

// AddPropertyIDs adds the "properties" edge to the Property entity by IDs.
func (sc *SpaceCreate) AddPropertyIDs(ids ...int64) *SpaceCreate {
	sc.mutation.AddPropertyIDs(ids...)
	return sc
}

// AddProperties adds the "properties" edges to the Property entity.
func (sc *SpaceCreate) AddProperties(p ...*Property) *SpaceCreate {
	ids := make([]int64, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return sc.AddPropertyIDs(ids...)
}

// AddUserAssignmentIDs adds the "user_assignment" edge to the SpaceUserAssignment entity by IDs.
func (sc *SpaceCreate) AddUserAssignmentIDs(ids ...int64) *SpaceCreate {
	sc.mutation.AddUserAssignmentIDs(ids...)
	return sc
}

// AddUserAssignment adds the "user_assignment" edges to the SpaceUserAssignment entity.
func (sc *SpaceCreate) AddUserAssignment(s ...*SpaceUserAssignment) *SpaceCreate {
	ids := make([]int64, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return sc.AddUserAssignmentIDs(ids...)
}

// Mutation returns the SpaceMutation object of the builder.
func (sc *SpaceCreate) Mutation() *SpaceMutation {
	return sc.mutation
}

// Save creates the Space in the database.
func (sc *SpaceCreate) Save(ctx context.Context) (*Space, error) {
	if err := sc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, sc.sqlSave, sc.mutation, sc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SpaceCreate) SaveX(ctx context.Context) *Space {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SpaceCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SpaceCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sc *SpaceCreate) defaults() error {
	if _, ok := sc.mutation.PublicID(); !ok {
		if space.DefaultPublicID == nil {
			return fmt.Errorf("enttenant: uninitialized space.DefaultPublicID (forgotten import enttenant/runtime?)")
		}
		v := space.DefaultPublicID()
		sc.mutation.SetPublicID(v)
	}
	if _, ok := sc.mutation.IsFolderMode(); !ok {
		v := space.DefaultIsFolderMode
		sc.mutation.SetIsFolderMode(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (sc *SpaceCreate) check() error {
	if _, ok := sc.mutation.PublicID(); !ok {
		return &ValidationError{Name: "public_id", err: errors.New(`enttenant: missing required field "Space.public_id"`)}
	}
	if _, ok := sc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`enttenant: missing required field "Space.name"`)}
	}
	if _, ok := sc.mutation.IsFolderMode(); !ok {
		return &ValidationError{Name: "is_folder_mode", err: errors.New(`enttenant: missing required field "Space.is_folder_mode"`)}
	}
	return nil
}

func (sc *SpaceCreate) sqlSave(ctx context.Context) (*Space, error) {
	if err := sc.check(); err != nil {
		return nil, err
	}
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	sc.mutation.id = &_node.ID
	sc.mutation.done = true
	return _node, nil
}

func (sc *SpaceCreate) createSpec() (*Space, *sqlgraph.CreateSpec) {
	var (
		_node = &Space{config: sc.config}
		_spec = sqlgraph.NewCreateSpec(space.Table, sqlgraph.NewFieldSpec(space.FieldID, field.TypeInt64))
	)
	if id, ok := sc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := sc.mutation.PublicID(); ok {
		_spec.SetField(space.FieldPublicID, field.TypeString, value)
		_node.PublicID = value
	}
	if value, ok := sc.mutation.DeletedAt(); ok {
		_spec.SetField(space.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := sc.mutation.Name(); ok {
		_spec.SetField(space.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := sc.mutation.Icon(); ok {
		_spec.SetField(space.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := sc.mutation.Description(); ok {
		_spec.SetField(space.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := sc.mutation.IsFolderMode(); ok {
		_spec.SetField(space.FieldIsFolderMode, field.TypeBool, value)
		_node.IsFolderMode = value
	}
	if nodes := sc.mutation.DeleterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   space.DeleterTable,
			Columns: []string{space.DeleterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DeletedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.FilesTable,
			Columns: []string{space.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   space.UsersTable,
			Columns: space.UsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &SpaceUserAssignmentCreate{config: sc.config, mutation: newSpaceUserAssignmentMutation(sc.config, OpCreate)}
		_ = createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.TagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.TagsTable,
			Columns: []string{space.TagsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.DocumentTypesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.DocumentTypesTable,
			Columns: []string{space.DocumentTypesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(documenttype.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.PropertiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.PropertiesTable,
			Columns: []string{space.PropertiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(property.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.UserAssignmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   space.UserAssignmentTable,
			Columns: []string{space.UserAssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(spaceuserassignment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SpaceCreateBulk is the builder for creating many Space entities in bulk.
type SpaceCreateBulk struct {
	config
	err      error
	builders []*SpaceCreate
}

// Save creates the Space entities in the database.
func (scb *SpaceCreateBulk) Save(ctx context.Context) ([]*Space, error) {
	if scb.err != nil {
		return nil, scb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Space, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SpaceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SpaceCreateBulk) SaveX(ctx context.Context) []*Space {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SpaceCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SpaceCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}
