// Code generated by ent, DO NOT EDIT.

package enttenant

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/simpledms/simpledms/enttenant/file"
	"github.com/simpledms/simpledms/enttenant/predicate"
	"github.com/simpledms/simpledms/enttenant/tag"
	"github.com/simpledms/simpledms/enttenant/tagassignment"
	"github.com/simpledms/simpledms/model/tagging/tagtype"
)

// TagUpdate is the builder for updating Tag entities.
type TagUpdate struct {
	config
	hooks     []Hook
	mutation  *TagMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TagUpdate builder.
func (tu *TagUpdate) Where(ps ...predicate.Tag) *TagUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetName sets the "name" field.
func (tu *TagUpdate) SetName(s string) *TagUpdate {
	tu.mutation.SetName(s)
	return tu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tu *TagUpdate) SetNillableName(s *string) *TagUpdate {
	if s != nil {
		tu.SetName(*s)
	}
	return tu
}

// SetColor sets the "color" field.
func (tu *TagUpdate) SetColor(s string) *TagUpdate {
	tu.mutation.SetColor(s)
	return tu
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (tu *TagUpdate) SetNillableColor(s *string) *TagUpdate {
	if s != nil {
		tu.SetColor(*s)
	}
	return tu
}

// ClearColor clears the value of the "color" field.
func (tu *TagUpdate) ClearColor() *TagUpdate {
	tu.mutation.ClearColor()
	return tu
}

// SetIcon sets the "icon" field.
func (tu *TagUpdate) SetIcon(s string) *TagUpdate {
	tu.mutation.SetIcon(s)
	return tu
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (tu *TagUpdate) SetNillableIcon(s *string) *TagUpdate {
	if s != nil {
		tu.SetIcon(*s)
	}
	return tu
}

// ClearIcon clears the value of the "icon" field.
func (tu *TagUpdate) ClearIcon() *TagUpdate {
	tu.mutation.ClearIcon()
	return tu
}

// SetType sets the "type" field.
func (tu *TagUpdate) SetType(tt tagtype.TagType) *TagUpdate {
	tu.mutation.SetType(tt)
	return tu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tu *TagUpdate) SetNillableType(tt *tagtype.TagType) *TagUpdate {
	if tt != nil {
		tu.SetType(*tt)
	}
	return tu
}

// SetGroupID sets the "group_id" field.
func (tu *TagUpdate) SetGroupID(i int64) *TagUpdate {
	tu.mutation.SetGroupID(i)
	return tu
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (tu *TagUpdate) SetNillableGroupID(i *int64) *TagUpdate {
	if i != nil {
		tu.SetGroupID(*i)
	}
	return tu
}

// ClearGroupID clears the value of the "group_id" field.
func (tu *TagUpdate) ClearGroupID() *TagUpdate {
	tu.mutation.ClearGroupID()
	return tu
}

// AddChildIDs adds the "children" edge to the Tag entity by IDs.
func (tu *TagUpdate) AddChildIDs(ids ...int64) *TagUpdate {
	tu.mutation.AddChildIDs(ids...)
	return tu
}

// AddChildren adds the "children" edges to the Tag entity.
func (tu *TagUpdate) AddChildren(t ...*Tag) *TagUpdate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.AddChildIDs(ids...)
}

// SetGroup sets the "group" edge to the Tag entity.
func (tu *TagUpdate) SetGroup(t *Tag) *TagUpdate {
	return tu.SetGroupID(t.ID)
}

// AddSuperTagIDs adds the "super_tags" edge to the Tag entity by IDs.
func (tu *TagUpdate) AddSuperTagIDs(ids ...int64) *TagUpdate {
	tu.mutation.AddSuperTagIDs(ids...)
	return tu
}

// AddSuperTags adds the "super_tags" edges to the Tag entity.
func (tu *TagUpdate) AddSuperTags(t ...*Tag) *TagUpdate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.AddSuperTagIDs(ids...)
}

// AddSubTagIDs adds the "sub_tags" edge to the Tag entity by IDs.
func (tu *TagUpdate) AddSubTagIDs(ids ...int64) *TagUpdate {
	tu.mutation.AddSubTagIDs(ids...)
	return tu
}

// AddSubTags adds the "sub_tags" edges to the Tag entity.
func (tu *TagUpdate) AddSubTags(t ...*Tag) *TagUpdate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.AddSubTagIDs(ids...)
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (tu *TagUpdate) AddFileIDs(ids ...int64) *TagUpdate {
	tu.mutation.AddFileIDs(ids...)
	return tu
}

// AddFiles adds the "files" edges to the File entity.
func (tu *TagUpdate) AddFiles(f ...*File) *TagUpdate {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return tu.AddFileIDs(ids...)
}

// AddTagAssignmentIDs adds the "tag_assignment" edge to the TagAssignment entity by IDs.
func (tu *TagUpdate) AddTagAssignmentIDs(ids ...int64) *TagUpdate {
	tu.mutation.AddTagAssignmentIDs(ids...)
	return tu
}

// AddTagAssignment adds the "tag_assignment" edges to the TagAssignment entity.
func (tu *TagUpdate) AddTagAssignment(t ...*TagAssignment) *TagUpdate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.AddTagAssignmentIDs(ids...)
}

// Mutation returns the TagMutation object of the builder.
func (tu *TagUpdate) Mutation() *TagMutation {
	return tu.mutation
}

// ClearChildren clears all "children" edges to the Tag entity.
func (tu *TagUpdate) ClearChildren() *TagUpdate {
	tu.mutation.ClearChildren()
	return tu
}

// RemoveChildIDs removes the "children" edge to Tag entities by IDs.
func (tu *TagUpdate) RemoveChildIDs(ids ...int64) *TagUpdate {
	tu.mutation.RemoveChildIDs(ids...)
	return tu
}

// RemoveChildren removes "children" edges to Tag entities.
func (tu *TagUpdate) RemoveChildren(t ...*Tag) *TagUpdate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.RemoveChildIDs(ids...)
}

// ClearGroup clears the "group" edge to the Tag entity.
func (tu *TagUpdate) ClearGroup() *TagUpdate {
	tu.mutation.ClearGroup()
	return tu
}

// ClearSuperTags clears all "super_tags" edges to the Tag entity.
func (tu *TagUpdate) ClearSuperTags() *TagUpdate {
	tu.mutation.ClearSuperTags()
	return tu
}

// RemoveSuperTagIDs removes the "super_tags" edge to Tag entities by IDs.
func (tu *TagUpdate) RemoveSuperTagIDs(ids ...int64) *TagUpdate {
	tu.mutation.RemoveSuperTagIDs(ids...)
	return tu
}

// RemoveSuperTags removes "super_tags" edges to Tag entities.
func (tu *TagUpdate) RemoveSuperTags(t ...*Tag) *TagUpdate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.RemoveSuperTagIDs(ids...)
}

// ClearSubTags clears all "sub_tags" edges to the Tag entity.
func (tu *TagUpdate) ClearSubTags() *TagUpdate {
	tu.mutation.ClearSubTags()
	return tu
}

// RemoveSubTagIDs removes the "sub_tags" edge to Tag entities by IDs.
func (tu *TagUpdate) RemoveSubTagIDs(ids ...int64) *TagUpdate {
	tu.mutation.RemoveSubTagIDs(ids...)
	return tu
}

// RemoveSubTags removes "sub_tags" edges to Tag entities.
func (tu *TagUpdate) RemoveSubTags(t ...*Tag) *TagUpdate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.RemoveSubTagIDs(ids...)
}

// ClearFiles clears all "files" edges to the File entity.
func (tu *TagUpdate) ClearFiles() *TagUpdate {
	tu.mutation.ClearFiles()
	return tu
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (tu *TagUpdate) RemoveFileIDs(ids ...int64) *TagUpdate {
	tu.mutation.RemoveFileIDs(ids...)
	return tu
}

// RemoveFiles removes "files" edges to File entities.
func (tu *TagUpdate) RemoveFiles(f ...*File) *TagUpdate {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return tu.RemoveFileIDs(ids...)
}

// ClearTagAssignment clears all "tag_assignment" edges to the TagAssignment entity.
func (tu *TagUpdate) ClearTagAssignment() *TagUpdate {
	tu.mutation.ClearTagAssignment()
	return tu
}

// RemoveTagAssignmentIDs removes the "tag_assignment" edge to TagAssignment entities by IDs.
func (tu *TagUpdate) RemoveTagAssignmentIDs(ids ...int64) *TagUpdate {
	tu.mutation.RemoveTagAssignmentIDs(ids...)
	return tu
}

// RemoveTagAssignment removes "tag_assignment" edges to TagAssignment entities.
func (tu *TagUpdate) RemoveTagAssignment(t ...*TagAssignment) *TagUpdate {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.RemoveTagAssignmentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TagUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TagUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TagUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TagUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TagUpdate) check() error {
	if v, ok := tu.mutation.GetType(); ok {
		if err := tag.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`enttenant: validator failed for field "Tag.type": %w`, err)}
		}
	}
	if tu.mutation.SpaceCleared() && len(tu.mutation.SpaceIDs()) > 0 {
		return errors.New(`enttenant: clearing a required unique edge "Tag.space"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tu *TagUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TagUpdate {
	tu.modifiers = append(tu.modifiers, modifiers...)
	return tu
}

func (tu *TagUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(tag.Table, tag.Columns, sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Name(); ok {
		_spec.SetField(tag.FieldName, field.TypeString, value)
	}
	if value, ok := tu.mutation.Color(); ok {
		_spec.SetField(tag.FieldColor, field.TypeString, value)
	}
	if tu.mutation.ColorCleared() {
		_spec.ClearField(tag.FieldColor, field.TypeString)
	}
	if value, ok := tu.mutation.Icon(); ok {
		_spec.SetField(tag.FieldIcon, field.TypeString, value)
	}
	if tu.mutation.IconCleared() {
		_spec.ClearField(tag.FieldIcon, field.TypeString)
	}
	if value, ok := tu.mutation.GetType(); ok {
		_spec.SetField(tag.FieldType, field.TypeEnum, value)
	}
	if tu.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tag.ChildrenTable,
			Columns: []string{tag.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !tu.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tag.ChildrenTable,
			Columns: []string{tag.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tag.ChildrenTable,
			Columns: []string{tag.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tag.GroupTable,
			Columns: []string{tag.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tag.GroupTable,
			Columns: []string{tag.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.SuperTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tag.SuperTagsTable,
			Columns: tag.SuperTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedSuperTagsIDs(); len(nodes) > 0 && !tu.mutation.SuperTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tag.SuperTagsTable,
			Columns: tag.SuperTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.SuperTagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tag.SuperTagsTable,
			Columns: tag.SuperTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.SubTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tag.SubTagsTable,
			Columns: tag.SubTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedSubTagsIDs(); len(nodes) > 0 && !tu.mutation.SubTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tag.SubTagsTable,
			Columns: tag.SubTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.SubTagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tag.SubTagsTable,
			Columns: tag.SubTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tag.FilesTable,
			Columns: tag.FilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedFilesIDs(); len(nodes) > 0 && !tu.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tag.FilesTable,
			Columns: tag.FilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tag.FilesTable,
			Columns: tag.FilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.TagAssignmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tag.TagAssignmentTable,
			Columns: []string{tag.TagAssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tagassignment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedTagAssignmentIDs(); len(nodes) > 0 && !tu.mutation.TagAssignmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tag.TagAssignmentTable,
			Columns: []string{tag.TagAssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tagassignment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.TagAssignmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tag.TagAssignmentTable,
			Columns: []string{tag.TagAssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tagassignment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(tu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TagUpdateOne is the builder for updating a single Tag entity.
type TagUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TagMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (tuo *TagUpdateOne) SetName(s string) *TagUpdateOne {
	tuo.mutation.SetName(s)
	return tuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tuo *TagUpdateOne) SetNillableName(s *string) *TagUpdateOne {
	if s != nil {
		tuo.SetName(*s)
	}
	return tuo
}

// SetColor sets the "color" field.
func (tuo *TagUpdateOne) SetColor(s string) *TagUpdateOne {
	tuo.mutation.SetColor(s)
	return tuo
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (tuo *TagUpdateOne) SetNillableColor(s *string) *TagUpdateOne {
	if s != nil {
		tuo.SetColor(*s)
	}
	return tuo
}

// ClearColor clears the value of the "color" field.
func (tuo *TagUpdateOne) ClearColor() *TagUpdateOne {
	tuo.mutation.ClearColor()
	return tuo
}

// SetIcon sets the "icon" field.
func (tuo *TagUpdateOne) SetIcon(s string) *TagUpdateOne {
	tuo.mutation.SetIcon(s)
	return tuo
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (tuo *TagUpdateOne) SetNillableIcon(s *string) *TagUpdateOne {
	if s != nil {
		tuo.SetIcon(*s)
	}
	return tuo
}

// ClearIcon clears the value of the "icon" field.
func (tuo *TagUpdateOne) ClearIcon() *TagUpdateOne {
	tuo.mutation.ClearIcon()
	return tuo
}

// SetType sets the "type" field.
func (tuo *TagUpdateOne) SetType(tt tagtype.TagType) *TagUpdateOne {
	tuo.mutation.SetType(tt)
	return tuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (tuo *TagUpdateOne) SetNillableType(tt *tagtype.TagType) *TagUpdateOne {
	if tt != nil {
		tuo.SetType(*tt)
	}
	return tuo
}

// SetGroupID sets the "group_id" field.
func (tuo *TagUpdateOne) SetGroupID(i int64) *TagUpdateOne {
	tuo.mutation.SetGroupID(i)
	return tuo
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (tuo *TagUpdateOne) SetNillableGroupID(i *int64) *TagUpdateOne {
	if i != nil {
		tuo.SetGroupID(*i)
	}
	return tuo
}

// ClearGroupID clears the value of the "group_id" field.
func (tuo *TagUpdateOne) ClearGroupID() *TagUpdateOne {
	tuo.mutation.ClearGroupID()
	return tuo
}

// AddChildIDs adds the "children" edge to the Tag entity by IDs.
func (tuo *TagUpdateOne) AddChildIDs(ids ...int64) *TagUpdateOne {
	tuo.mutation.AddChildIDs(ids...)
	return tuo
}

// AddChildren adds the "children" edges to the Tag entity.
func (tuo *TagUpdateOne) AddChildren(t ...*Tag) *TagUpdateOne {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.AddChildIDs(ids...)
}

// SetGroup sets the "group" edge to the Tag entity.
func (tuo *TagUpdateOne) SetGroup(t *Tag) *TagUpdateOne {
	return tuo.SetGroupID(t.ID)
}

// AddSuperTagIDs adds the "super_tags" edge to the Tag entity by IDs.
func (tuo *TagUpdateOne) AddSuperTagIDs(ids ...int64) *TagUpdateOne {
	tuo.mutation.AddSuperTagIDs(ids...)
	return tuo
}

// AddSuperTags adds the "super_tags" edges to the Tag entity.
func (tuo *TagUpdateOne) AddSuperTags(t ...*Tag) *TagUpdateOne {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.AddSuperTagIDs(ids...)
}

// AddSubTagIDs adds the "sub_tags" edge to the Tag entity by IDs.
func (tuo *TagUpdateOne) AddSubTagIDs(ids ...int64) *TagUpdateOne {
	tuo.mutation.AddSubTagIDs(ids...)
	return tuo
}

// AddSubTags adds the "sub_tags" edges to the Tag entity.
func (tuo *TagUpdateOne) AddSubTags(t ...*Tag) *TagUpdateOne {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.AddSubTagIDs(ids...)
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (tuo *TagUpdateOne) AddFileIDs(ids ...int64) *TagUpdateOne {
	tuo.mutation.AddFileIDs(ids...)
	return tuo
}

// AddFiles adds the "files" edges to the File entity.
func (tuo *TagUpdateOne) AddFiles(f ...*File) *TagUpdateOne {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return tuo.AddFileIDs(ids...)
}

// AddTagAssignmentIDs adds the "tag_assignment" edge to the TagAssignment entity by IDs.
func (tuo *TagUpdateOne) AddTagAssignmentIDs(ids ...int64) *TagUpdateOne {
	tuo.mutation.AddTagAssignmentIDs(ids...)
	return tuo
}

// AddTagAssignment adds the "tag_assignment" edges to the TagAssignment entity.
func (tuo *TagUpdateOne) AddTagAssignment(t ...*TagAssignment) *TagUpdateOne {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.AddTagAssignmentIDs(ids...)
}

// Mutation returns the TagMutation object of the builder.
func (tuo *TagUpdateOne) Mutation() *TagMutation {
	return tuo.mutation
}

// ClearChildren clears all "children" edges to the Tag entity.
func (tuo *TagUpdateOne) ClearChildren() *TagUpdateOne {
	tuo.mutation.ClearChildren()
	return tuo
}

// RemoveChildIDs removes the "children" edge to Tag entities by IDs.
func (tuo *TagUpdateOne) RemoveChildIDs(ids ...int64) *TagUpdateOne {
	tuo.mutation.RemoveChildIDs(ids...)
	return tuo
}

// RemoveChildren removes "children" edges to Tag entities.
func (tuo *TagUpdateOne) RemoveChildren(t ...*Tag) *TagUpdateOne {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.RemoveChildIDs(ids...)
}

// ClearGroup clears the "group" edge to the Tag entity.
func (tuo *TagUpdateOne) ClearGroup() *TagUpdateOne {
	tuo.mutation.ClearGroup()
	return tuo
}

// ClearSuperTags clears all "super_tags" edges to the Tag entity.
func (tuo *TagUpdateOne) ClearSuperTags() *TagUpdateOne {
	tuo.mutation.ClearSuperTags()
	return tuo
}

// RemoveSuperTagIDs removes the "super_tags" edge to Tag entities by IDs.
func (tuo *TagUpdateOne) RemoveSuperTagIDs(ids ...int64) *TagUpdateOne {
	tuo.mutation.RemoveSuperTagIDs(ids...)
	return tuo
}

// RemoveSuperTags removes "super_tags" edges to Tag entities.
func (tuo *TagUpdateOne) RemoveSuperTags(t ...*Tag) *TagUpdateOne {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.RemoveSuperTagIDs(ids...)
}

// ClearSubTags clears all "sub_tags" edges to the Tag entity.
func (tuo *TagUpdateOne) ClearSubTags() *TagUpdateOne {
	tuo.mutation.ClearSubTags()
	return tuo
}

// RemoveSubTagIDs removes the "sub_tags" edge to Tag entities by IDs.
func (tuo *TagUpdateOne) RemoveSubTagIDs(ids ...int64) *TagUpdateOne {
	tuo.mutation.RemoveSubTagIDs(ids...)
	return tuo
}

// RemoveSubTags removes "sub_tags" edges to Tag entities.
func (tuo *TagUpdateOne) RemoveSubTags(t ...*Tag) *TagUpdateOne {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.RemoveSubTagIDs(ids...)
}

// ClearFiles clears all "files" edges to the File entity.
func (tuo *TagUpdateOne) ClearFiles() *TagUpdateOne {
	tuo.mutation.ClearFiles()
	return tuo
}

// RemoveFileIDs removes the "files" edge to File entities by IDs.
func (tuo *TagUpdateOne) RemoveFileIDs(ids ...int64) *TagUpdateOne {
	tuo.mutation.RemoveFileIDs(ids...)
	return tuo
}

// RemoveFiles removes "files" edges to File entities.
func (tuo *TagUpdateOne) RemoveFiles(f ...*File) *TagUpdateOne {
	ids := make([]int64, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return tuo.RemoveFileIDs(ids...)
}

// ClearTagAssignment clears all "tag_assignment" edges to the TagAssignment entity.
func (tuo *TagUpdateOne) ClearTagAssignment() *TagUpdateOne {
	tuo.mutation.ClearTagAssignment()
	return tuo
}

// RemoveTagAssignmentIDs removes the "tag_assignment" edge to TagAssignment entities by IDs.
func (tuo *TagUpdateOne) RemoveTagAssignmentIDs(ids ...int64) *TagUpdateOne {
	tuo.mutation.RemoveTagAssignmentIDs(ids...)
	return tuo
}

// RemoveTagAssignment removes "tag_assignment" edges to TagAssignment entities.
func (tuo *TagUpdateOne) RemoveTagAssignment(t ...*TagAssignment) *TagUpdateOne {
	ids := make([]int64, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.RemoveTagAssignmentIDs(ids...)
}

// Where appends a list predicates to the TagUpdate builder.
func (tuo *TagUpdateOne) Where(ps ...predicate.Tag) *TagUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TagUpdateOne) Select(field string, fields ...string) *TagUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Tag entity.
func (tuo *TagUpdateOne) Save(ctx context.Context) (*Tag, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TagUpdateOne) SaveX(ctx context.Context) *Tag {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TagUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TagUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TagUpdateOne) check() error {
	if v, ok := tuo.mutation.GetType(); ok {
		if err := tag.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`enttenant: validator failed for field "Tag.type": %w`, err)}
		}
	}
	if tuo.mutation.SpaceCleared() && len(tuo.mutation.SpaceIDs()) > 0 {
		return errors.New(`enttenant: clearing a required unique edge "Tag.space"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (tuo *TagUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TagUpdateOne {
	tuo.modifiers = append(tuo.modifiers, modifiers...)
	return tuo
}

func (tuo *TagUpdateOne) sqlSave(ctx context.Context) (_node *Tag, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tag.Table, tag.Columns, sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`enttenant: missing "Tag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tag.FieldID)
		for _, f := range fields {
			if !tag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("enttenant: invalid field %q for query", f)}
			}
			if f != tag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Name(); ok {
		_spec.SetField(tag.FieldName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Color(); ok {
		_spec.SetField(tag.FieldColor, field.TypeString, value)
	}
	if tuo.mutation.ColorCleared() {
		_spec.ClearField(tag.FieldColor, field.TypeString)
	}
	if value, ok := tuo.mutation.Icon(); ok {
		_spec.SetField(tag.FieldIcon, field.TypeString, value)
	}
	if tuo.mutation.IconCleared() {
		_spec.ClearField(tag.FieldIcon, field.TypeString)
	}
	if value, ok := tuo.mutation.GetType(); ok {
		_spec.SetField(tag.FieldType, field.TypeEnum, value)
	}
	if tuo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tag.ChildrenTable,
			Columns: []string{tag.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !tuo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tag.ChildrenTable,
			Columns: []string{tag.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tag.ChildrenTable,
			Columns: []string{tag.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tag.GroupTable,
			Columns: []string{tag.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   tag.GroupTable,
			Columns: []string{tag.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.SuperTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tag.SuperTagsTable,
			Columns: tag.SuperTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedSuperTagsIDs(); len(nodes) > 0 && !tuo.mutation.SuperTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tag.SuperTagsTable,
			Columns: tag.SuperTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.SuperTagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tag.SuperTagsTable,
			Columns: tag.SuperTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.SubTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tag.SubTagsTable,
			Columns: tag.SubTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedSubTagsIDs(); len(nodes) > 0 && !tuo.mutation.SubTagsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tag.SubTagsTable,
			Columns: tag.SubTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.SubTagsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   tag.SubTagsTable,
			Columns: tag.SubTagsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tag.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tag.FilesTable,
			Columns: tag.FilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedFilesIDs(); len(nodes) > 0 && !tuo.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tag.FilesTable,
			Columns: tag.FilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   tag.FilesTable,
			Columns: tag.FilesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.TagAssignmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tag.TagAssignmentTable,
			Columns: []string{tag.TagAssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tagassignment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedTagAssignmentIDs(); len(nodes) > 0 && !tuo.mutation.TagAssignmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tag.TagAssignmentTable,
			Columns: []string{tag.TagAssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tagassignment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.TagAssignmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   tag.TagAssignmentTable,
			Columns: []string{tag.TagAssignmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tagassignment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(tuo.modifiers...)
	_node = &Tag{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
