name: 'GolangCI-Lint'

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v6
        with:
          go-version: '1.26'

      # pin commit hash instead of version (v9.2.1) for safety (supply chain attacks)
      - uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee
        with:
          version: v2.12.2
          args: ./...
